### ISSUE TITLE
/PART Unfinished for UTF-8 strings in APPEND, INSERT, CHANGE

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#1005]
?? reword "ò$a" reduce ['a ""]
=>
"^@"

**Comment by hostilefork** [comment]
It looks like somehow APPEND/PART didn't get finished, it's using the limit as a byte count and not a character count :-(

    >> append/part "" "ò" 1
    == "^@"

The code has a comment saying it's wrong, so it must have just gotten overlooked to come back and fix!

https://github.com/metaeducation/ren-c/blob/bf792914b21170b22ffaec038d0d7cb1ccebda34/src/core/f-modify.c#L447

I tried working on it tonight but I think it's probably necessary to go over this and clean it up more thoroughly.

**Comment by hostilefork** [comment]
Some progress looking at this, and the reword case works, at least...so long as it's partial string into string.  The way /PART works is weird but maybe there is a point to it:

https://github.com/rebol/rebol-issues/issues/2096

*however* there is a bug making it so that using /PART to limit output of a BINARY! from an ANY-STRING! gets clipped...same bug causes problems with BLOCK!:

https://github.com/rebol/rebol-issues/issues/2383

Hopefully it's not too hard and I'll be able to get to it...!

**Comment by hostilefork** [comment]
Okay this [should be fixed now](https://github.com/metaeducation/ren-c/commit/2673fac76a057d218dc4de9db812facc5222802d), along with some more features coming along:

https://forum.rebol.info/t/as-binary-view-of-a-string-is-back-now-with-utf-8-thats-only-part/1186

If you feel like writing more tests that is great, otherwise keep being the bug finder/maker!  :-)
