### ISSUE TITLE
<static> does not work with func

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#1013]
````
>> f: function[val <static> accum ([])][]
== make action! [[val] [...]]

>> f: func[val <static> accum ([])][]     
** Script Error: invalid function definition: <static>
** Where: func console
** Near: [... func [val <static> accum ...] [] ~~]
** Line: 1
````

**Comment by hostilefork** [comment]
There were some technical and philosophical reasons for this happening.  It sort of resulted from a carrying forward of R3-Alpha-isms where some features that were only available in FUNCTION and not FUNC (like /EXTERN or /WITH).  That's because FUNC tried to be very optimal and simple, and FUNCTION was a heavier+newer+usermode function.

But I certainly have felt it has been increasingly hard to put together justifications for why there were some things FUNC could do that FUNCTION could not.

**This will hopefully cease to be an issue when we switch to where [FUNC and FUNCTION are synonyms](https://forum.rebol.info/t/abbreviations-as-synonyms/1211?u=hostilefork)**.  We'll have shifted away from encouraging locals-gathering (at least unless you specifically ask for it), because it has turned out to have a lot of bad properties.  So [LET would be used instead](https://forum.rebol.info/t/rethinking-auto-gathered-set-word-locals/1150).

It means optimizations will have to be done differently, something like:

     func: function: make action! [
         [spec body]
         [either find spec tag! [ 
             ; do complex function creation work
             ; that would be a pain to write all as native code 
         ][
             function-no-tag spec body
         ]
     ]

In the meantime, if you conveniently want statics you would have to use FUNCTION, and then manually <with> any SET-WORD!s that you don't want gathered.

**Comment by IngoHohmann** [comment]
Ok, makes sense.
I would call this closed, then.

**Comment by hostilefork** [comment]
I've taken a sort of first step on the plan, and you should be able to use `<static>` with FUNC now:

https://github.com/metaeducation/ren-c/commit/11a1cdd6ce7120249c0589ff43465b76b13c297e
