### ISSUE TITLE
"ENSURE failed with argument of type text!" error while using ODBC

### ISSUE THREAD

**Issue by orr721** [metaeducation/ren-c#1017]
hello,

I have been using the ODBC extension successfully since 2017. Recently I've tried to upgrade to a current build of ren-c but the above error shows-up after the insert db-conn statement.

full transcript:

```
>> db-p: open [scheme: 'ODBC target: "Driver={Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)};DBQ=C:\PCSPOJ\pokus.xlsx;"]
== #[port! [...] [...]]                                                         
                                                                                
>> db-conn: first db-p                                                          
== #[port! [...] [...]]                                                         
                                                                                
>> insert db-conn "select * from [Sheet0$]"                                     
(i) Info: use WHY for error information                                         
** Error: ENSURE failed with argument of type text!                             
** Where: fail _ ensure insert-odbc _ insert console                            
** Near: [                                                                      
    fail [                                                                      
        "ENSURE failed with argument of type"                                   
 ... 
```

this happens using the most recent posted build:
```
**    Version:   2.102.0.3.1                                            **      
**    Platform:  Windows win32-x86                                      **      
**    Build:     5-Oct-2019/1:37:51+0:00                                **      
**    Commit:    762961b4ce50f574aa59a36d1f39a4128dec4233
```

the last build that I have where it works for me is:
```
**    Version:   2.102.0.3.1                                            **      
**    Platform:  Windows win32-x86                                      **      
**    Build:     5-Sep-2017/15:55:59                                    **      
**    Commit:    e6718d6e36fdc11dfaba586dd4920d906cce0b40
```

what can be done to fix the problem? I can continue to use the old build but I will not be able to use the recent changes in ren-c..

thank you very much for your excellent work!

orr721

**Comment by hostilefork** [comment]
Interesting to hear you have been using it (!)

It is timely for you to mention this.  Recently I am trying to get people to put code they care about up so that it is tested on Travis.  If the code has been published and I know where it is, I can attend to breakages that show up.  An example is what we've done with the HTTPD http server.

There is a stress test: [%stress.reb](https://github.com/metaeducation/rebol-httpd/blob/master/tests/stress.reb)

Which is run by a test script in the repository: [%.travis.yml](https://github.com/metaeducation/rebol-httpd/blob/master/.travis.yml)

And if anything breaks [we find out about it on the build matrix](https://travis-ci.org/metaeducation/rebol-httpd)

I've been thinking that rebol-odbc should be set up as such a project.  It would be very helpful if you had a test which exercised what your program needs--ideally your program itself--to share as part of the tests which were run.

When I get a chance I will see if I can rig up some way of setting up a Linux container with enough ODBC on it to test.  It looks like Windows containers are available as well, but I don't have experience setting that up:

https://blog.travis-ci.com/2018-10-11-windows-early-release

**Comment by orr721** [comment]
Well, I would like to help and I can certainly prepare a simple testing script. What I do with ODBC and REBOL/R3-RenC is typical glue work. I run a relatively simple batch job once per month to process a bunch of Excel files which are generated by other software I use. I have found that this setup is the most simple one - one script file, one executable (r3-renc) and it gets the work done. No massive IDEs, multitudes of libraries, etc. to install and manage.

Unfortunately, travis, docker, .. is really out of my league. I am sorry I just write simple scripts. This is above my abilities. I had to google around to get an idea what these things mean. ¯\_(ツ)_/¯  Thanks again.

**Comment by hostilefork** [comment]
I'm going to try and schedule in working on ODBC as soon as I can.  But regarding there being a lot to do, I've sent you a private message on [forum.rebol.info](https://forum.rebol.info/)...if you would log in and check there, with a rough cut of my talk on the low dependency nature of ["Amish Programming"](http://2019.reb4.me/talks)...

If you are up for the idea of being a user of the tool, it's pretty important to weigh in on the changes.  And if you can publish the code so I can look at it, that helps a lot in terms of knowing what people are doing and being able to offer advice...

**Comment by orr721** [comment]
I have replied to you in the forum, there was some delay on my side, sorry..

Meanwhile today I have checked commit e0786d06b533ccfb5189984ff8fb2bfa9ef263fa and you have made **amazing progress**! I can successfully connect to the database and insert the SQL statement. The problem for me is that my files contain accented characters and the copy db-connect fails with

```
>> copy db-connect
** Internal Error: invalid UTF-8 byte sequence found during decoding               
** Where: copy-odbc _ copy console                                                 
** Near: [                                                                         
    copy-odbc port/locals part ~~]                                                 
** Line: 113    

```
Fields with unaccented characters work correctly. How can I help you to test it further? The same file / script works correctly in the 2017 ren-c version.

Thank you very much!

**Comment by hostilefork** [comment]
> Meanwhile today I have checked commit e0786d0 and you have made amazing progress! I can successfully connect to the database and insert the SQL statement. 

Great!  Yes, I took the last two days to work on it...and tried to fix pretty much everything I could, including the leaks.  (It's easier to track those down on Linux due to Address Sanitizer and Valgrind, so having a working setup with unixodbc helped a lot with that.)

But most importantly, it is now tested on Travis, and so it will be easier to see when it goes wrong:

https://travis-ci.org/metaeducation/rebol-odbc/jobs/596429561#L502

That's just a start to the tests, and so the more tests we can get the better.

> my files contain accented characters [...] The same file / script works correctly in the 2017 ren-c version.

R3-Alpha had commented out UTF-8 validity checking of various kinds, and Ren-C has [tightened the rule to require valid UTF-8](https://github.com/metaeducation/ren-c/commit/210f3cd7801cf87d610aa9844e35bb418f498f6b).  I believe the reasoning behind the choice to comment out the check was flawed, and this is the right thing to do.

One of Ren-C's "future bets" in reigning in complexity is that UTF-8 has won the format war.  So if you have text files or fields that aren't in UTF-8 my best advice would be to convert those files.  If you can't do that, then you have to work with it as BINARY!.

> How can I help you to test it further?

For any issues you have, please create a [minimal self-contained repro case](https://stackoverflow.com/help/minimal-reproducible-example) and raise it as an issue in the **new repository** for ODBC specifically:

https://github.com/metaeducation/rebol-odbc/issues

Anything you can think of that makes the ODBC extension more useful in design or a test that keeps it working better would be welcome.
