### ISSUE TITLE
Bug in PARSE when modifying the parsed string

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#1032]
Code:

        s: {abcdefghijklmnopqrst}
        for n 2 20 1 [
                -- n
                ?? t: copy/part s n
                parse t [any [
                        remove skip
                        insert "-"
                ]]
                ?? t
        ]

Output:

        -- n: 2
        "ab"
        "--"
        -- n: 3
        "abc"
        "---"
        -- n: 4
        "abcd"
        "----"
        -- n: 5
        "abcde"
        "-----"
        -- n: 6
        "abcdef"
        "------"
        -- n: 7
        "abcdefg"
        "-------"
        -- n: 8
        "abcdefgh"
        "--------"
        -- n: 9
        "abcdefghi"
        "---------"
        -- n: 10
        "abcdefghij"
        "----------"
        -- n: 11
        "abcdefghijk"
        "-----------"
        -- n: 12
        "abcdefghijkl"
        "------------"
        -- n: 13
        "abcdefghijklm"
        "-------------"
        -- n: 14
        "abcdefghijklmn"
        "--------------"
        -- n: 15
        "abcdefghijklmno"
        "---------------"
        -- n: 16
        "abcdefghijklmnop"
        "----------------"
        -- n: 17
        "abcdefghijklmnopq"
        "----------------c" ; c ??
        -- n: 18
        "abcdefghijklmnopqr"
        "-----------------c" ; c ??
        -- n: 19
        "abcdefghijklmnopqrs"
        "------------------c" ; c ??
        -- n: 20
        "abcdefghijklmnopqrst"
        "-------------------c" ; c ??

Note the anomalies starting with n=17

**Comment by hostilefork** [comment]
I'm not seeing this on Windows or Linux builds, only on the web build.  :-/

Is there a repro of this anywhere besides emscripten'd code?

**Comment by giuliolunati** [comment]
yes, in Android build.
(maybe 32-bit related?)

Il Gio 12 Dic 2019, 08:32 Brian Dickens <notifications@github.com> ha
scritto:

**Comment by giuliolunati** [comment]
I can confirm, that's a 32-bit issue.
An Android arm-64 build works well, an arm-32 doesn't.

**Comment by hostilefork** [comment]
A-ha.  On a 64-bit build it happens with n=33.

    s: {abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ}
    for n 2 50 1 [
            -- n
            print ["BEFORE:" mold t: copy/part s n]
            parse t [any [
                    remove skip
                    insert "-"
            ]]
            print ["AFTER:" mold t]
    ]

(Note: Unfortunately the **`--`** doesn't show the long details, so you have to print a molding.  I was thinking that **`---`** could be a version that shows more.  In any case...I'm glad to see you're using the features of `--`, including the SET-WORD! form...pretty cool to be able to add that to a language, huh?!)*

I wonder if it is related to series expansion.  There's a point when the string is short enough to live in the [space which would otherwise be used to track an allocation](https://github.com/metaeducation/ren-c/blob/797240e95f3c07bb2c3555aa62e63c411ae7cedf/src/include/sys-rebser.h#L515).  But I'm confused as to why it would be happening at 16 and 32 instead of 32 and 64.

Puzzling...looking into it now.  Haven't done 32-bit debug builds for a while, so having to bring those up to date...

**Comment by giuliolunati** [comment]
I'm bisecting to find the blamed commit

**Comment by hostilefork** [comment]
Don't stress on it!  A repro is going to be enough, I've just been busy (had appointments).

**Comment by giuliolunati** [comment]
no stress, the phone make the job ;-)

**Comment by giuliolunati** [comment]
no stress, the phone make the job ;-)

**Comment by giuliolunati** [comment]
the first bad commit is
075a24b519ae11fead8dfa8154414f9a9cabedf

**Comment by hostilefork** [comment]
> the first bad commit is
> 075a24b

Great, thanks!  That definitely is a smoking gun.

**Comment by hostilefork** [comment]
Sorry this took so long!

https://github.com/metaeducation/ren-c/commit/34aab36b8ebd4076bbcf993319a81f29168dd0d5

**Comment by giuliolunati** [comment]
NP, very good thx!
