### ISSUE TITLE
url!s are cut at curly braces when reading

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#1046]
````
>> to text! read to url! {https://httpbin.org/anything?a={"x":"y"}} 
== {{
  "args": {
    "a": ""
  }, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Charset": "utf-8", 
    "Host": "httpbin.org", 
    "User-Agent": "REBOL", 
    "X-Amzn-Trace-Id": "Root=1-5e3b13d1-1b00ba3c41d343bcd6626578"
  }, 
  "json": null, 
  "method": "GET", 
  "origin": "134.101.146.93", 
  "url": "https://httpbin.org/anything?a="
}
}
````
It works, if it is run through ENHEX.
````
>> to text! read to url! enhex {https://httpbin.org/anything?a={"x":"y"}}
== {{
  "args": {
    "a": "{\"x\":\"y\"}"
  }, 
  "data": "", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Charset": "utf-8", 
    "Host": "httpbin.org", 
    "User-Agent": "REBOL", 
    "X-Amzn-Trace-Id": "Root=1-5e3b13ea-462eb19c983b8d68a906994c"
  }, 
  "json": null, 
  "method": "GET", 
  "origin": "134.101.146.93", 
  "url": "https://httpbin.org/anything?a={\"x\":\"y\"}"
}
}
````
According to https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding braces do not need to be encoded.

**Comment by IngoHohmann** [comment]
I don't know how to _move_ to rebol-issues, but added my comment to https://github.com/rebol/rebol-issues/issues/2381 and marked some related issues there.

**Comment by hostilefork** [comment]
There's actually the ability to transfer issues within an organization or account's repository now in GitHub, but adding it there is probably best.

Because I believe in Plan -4, I think we can go ahead and start moving that direction.  "Redbol" can use an advanced form of loading which tries to LOAD and if it fails on a violation of Plan -4 then it can massage the remaining portion to put in enough spaces to try and retry the load.

I can probably hack this particularly request in shortly (once I take care of the things I'm trying to take care of), but like I say, we need a bigger picture "philosophy of URL! and encoding" story all written down in one place.  I'm pretty sure I've had some realizations here and there, but with the number of things I do it's hard to keep them all on the top of my head.

**Comment by hostilefork** [comment]
All right, you got it:

https://github.com/metaeducation/ren-c/commit/3139b41b90ae5d80470326c13f59fc19b29dbd68

We still need that comprehensive big-picture-philosophy about how we're going to be part of the solution to escaping URLs, and not more of the problem.  :-/

(Also need your matrix chat, getting off of StackOverflow is a priority for the next months!)
