### ISSUE TITLE
call/error to false panics on windows

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#1059]
```
>> call/error "gpg --help" false
C Source File ../extensions/process/call-windows.c, Line 368, Pointer 00000000035AA968
At evaluator tick: 282612
kind_byte=4
Containing series for value pointer found, panicking it:
managed series was likely created during evaluator tick: 282516
C Source File ../src/core/m-series.c, Line 500, Pointer 00000000007AA728
At evaluator tick: 282612
Rebol Internal Error
If you need to file a bug in the issue tracker, please give thorough
details on how to reproduce the problem:

    https://github.com/metaeducation/ren-c/issues

Include the following information in the report:


Executable not built with DEBUG_SERIES_ORIGINS, no more info
```

**Comment by hostilefork** [comment]
It worked on POSIX, but Shixin apparently never tested that particular feature on Windows.

Microsoft didn't quite document how to do it, but I've changed it and done a bit of factoring:

https://github.com/metaeducation/ren-c/commit/dd5d9742c7bb32a76bdda4e55a4e08c5e4f263dd

While I was testing it, I noticed the pesky appearance of the ^M in the TEXT! output.  So I chaged it so that if you're not targeting a BINARY!, then your DELINE-ing is implicit.

https://github.com/metaeducation/ren-c/commit/38c4e339b9788683ea715e32bc53e82809975fcc

Also changed the protocol to use INSERT instead of APPEND to match Rebol2's behavior when redirecting to a string or binary.
