### ISSUE TITLE
SPACED and char!

### ISSUE THREAD

**Issue by no-e-in** [metaeducation/ren-c#1070]
```
‌>> spaced [#"a" #"b"]
== "ab"
‌
‌>> unspaced [#"a" #"b"]
== "ab"
```

Is it a bug?

**Comment by hostilefork** [comment]
It's by design that DELIMIT (of which SPACED and UNSPACED are specializations) do not put the delimiters around single-characters.

The main motivator for this is newline.  If you consider something like:

    spaced ["abc" "def" newline "ghi" "jkl"]
    
Then you'd get:

     abc<space>def<space><newline>
     <space>ghi<space>jkl

An exception could be made for just newline.  But saying that CHAR! is in a class that doesn't need delimiting was favored.

The argument would be that CHAR! is worked with rarely enough that the cases where it is are usually used are as often intended to assemble string bits one piece at a time.
