### ISSUE TITLE
Problem with latest-of 0.3.40 (and 0.3.1)

### ISSUE THREAD

**Issue by no-e-in** [metaeducation/ren-c#1078]
```
>> 	latest-of 0.3.40
searching ...
‌file: r3-eaee946.exe doesn't exist, it may still be being deployed
‌
‌
‌>> 	latest-of 0.4.40
searching ...
‌File size: 2.05 Mb Date: 28-Sep-2020/2:43:17+0:00
‌
https://dd498l1ilnrxu.cloudfront.net/travis-builds/0.4.40/r3-eaee946
‌
‌>> 	latest-of 0.2.40
searching ...
‌File size: 1.75 Mb Date: 28-Sep-2020/2:41:20+0:00
‌
https://dd498l1ilnrxu.cloudfront.net/travis-builds/0.2.40/r3-eaee946
‌
‌>> 	latest-of 0.13.2
searching ...
‌File size: 2.25 Mb Date: 28-Sep-2020/2:53:58+0:00
‌
https://dd498l1ilnrxu.cloudfront.net/travis-builds/0.13.2/r3-eaee946
‌File size: 5.08 Mb Date: 28-Sep-2020/2:52:01+0:00
‌
https://dd498l1ilnrxu.cloudfront.net/travis-builds/0.13.2/r3-eaee946-debug
```

**Comment by hostilefork** [comment]
We aren't using cloudfront (the reason is that cloudfront caches files, and that's a problem for some of the mechanism as written to use single URLs that change their content, this would require explicit expiration, so s3 is easier).

Hence this LATEST-OF...wherever you are finding that command...is providing the wrong URLs.  The correct prefix is `http://metaeducation.s3.amazonaws.com/travis-builds/`

http://metaeducation.s3.amazonaws.com/travis-builds/0.13.2/r3-eaee946

But I will reiterate that binary downloads are not something I personally support!  So if people create URLs to make it convenient to download debugging-oriented builds, and wander off, when I couldn't fix the download site even if I wanted to... well... there's not much I can do about that.

I've made the [table stakes clearer in the README](https://github.com/metaeducation/ren-c/blob/master/README.md):

> While Rebol 3 built for many platforms, Ren-C extends those to everything from OpenBSD to HaikuOS and WebAssembly. But the experimental nature of the project and limited resources mean there isn't support for packaging and distribution of native binaries. So the table stakes for participating is building your own native interpreter (see instructions below)
>
> The current sole focus for deploying a prebuilt experience to users is via WebAssembly in the web browser. See the demo of the Web Console that was shown at the Rebol 2019 Conference.

Lots of interesting things happening, however.

https://forum.rebol.info/

**Comment by no-e-in** [comment]
> Hence this LATEST-OF...wherever you are finding that command

At http://hostilefork.com/media/shared/replpad-js/ : 
```
DO <downloads>
LATEST-OF 0.3.40
```
[LATEST-OF](https://raw.githubusercontent.com/gchiu/rebol-misc/master/latest-of.reb) is a program of Graham Chiu
