### ISSUE TITLE
Compile failure (clang-9.0.1, @9708455)

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#1081]
In file included from ../src/core/a-globals.c:33:
../src/include/sys-core.h:132:10: error: "<stdio.h>
      included prior to %sys-core.h in release build"

**Comment by giuliolunati** [comment]
Smoking gun is 9708455e

**Comment by hostilefork** [comment]
The comments explain the motivation... it's to try and catch compilations of the core that link to things like printf without having to go to the `nm` and looking at symbols.

But it does seem there are compilers where the inclusion of stdio.h is unavoidable (like you do `#include <stdlib.h>` and it includes stdio).  I think this is unfortunate...it basically makes all standard library functions reserved words in the language.

Perhaps exempting Android is good enough.  Try this:

https://github.com/metaeducation/ren-c/commit/8766228abd55ca56f6f34d712b33391709968498

**Comment by giuliolunati** [comment]
Don't exempt Android! The cross compilation with gcc works well, the issue is restricted to clang, that I use for native compilation on Termux. I can manage to switch to gcc...

**Comment by hostilefork** [comment]
Well, we can exempt clang then...

**Comment by hostilefork** [comment]
I force pushed over top of the last commit with __clang__ as the exemption:

https://github.com/metaeducation/ren-c/commit/0fc26acde2f67a5c77be4584bd4b700b9bef9a81

It is probably recent clang that is the problem, because it only showed up in the most recent OS X.  So that's probably the better check.

BTW: please do give any comments on the [generic tuple](https://github.com/metaeducation/ren-c/pull/1080)... as I intend to merge it soon.

**Comment by hostilefork** [comment]
Assuming the __clang__ worked (it worked on the builds for the latest OS X)...

**Comment by giuliolunati** [comment]
Yes, it works, thanks!

Il mer 7 ott 2020, 20:53 Hostile Fork <notifications@github.com> ha scritto:
