### ISSUE TITLE
Should it be possible to 'join issues?

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#1085]
````
>> help join
USAGE:
    JOIN head value 

DESCRIPTION:
    Concatenates values to the end of a copy of a value
    JOIN is an ACTION!

RETURNS: [<requote> any-series! any-path! tuple! port!
    map! object! module! bitset!]

ARGUMENTS:
    head [<dequote> any-series! any-path! tuple! port! map! object! module! bitset!]
    value [<opt> any-value!]
````

The help of join states, that it appends to a copy of the value, so it could create a new token! as the concatenation of the 2 values.

**Comment by hostilefork** [comment]
The behavior of immutable types involves work, since they have no APPEND functionality.

So what the usermode JOIN does is explicitly converts to a mutable type for the duration of the work, and then aliases it back to the target type at the end.

I've improved that JOIN somewhat...building it on **reduce .identity** so it can take care of NULLs in the way that REJOIN expects, and then built REJOIN on top of it:

https://github.com/metaeducation/ren-c/commit/406b7acb96fbf7de4d906387a8c38e8359b6d612

*(Note that because I wanted this I went ahead and added the REDUCE predicate, so REDUCE now errors on NULLs by default... use .voidify for getting #[void], .try to get blanks, .identity to dissolve, etc.)*

I'd like to get the behavior of the joiners understood as well as possible before writing any of this as natives; the base set of functions still feels "off" to me.  Since it's all usermode, people are free to try out variations to build the ideal behavior.
