### ISSUE TITLE
Bug in MAX and MIN

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#1107]
max 0 1 => 0
min 0 1 => 1

**Comment by hostilefork** [comment]
Sadly, some of these things just never got in the basic tests!  :-/

https://github.com/metaeducation/ren-c/commit/4fd6b06e615b1be7b0afa85d0e631f8114d759d6

Hope you are having as good a new years as possible!  New Year summary on the forum:

https://forum.rebol.info/t/a-brighter-2021-with-virtual-binding-good-riddance-2020/1451

This made binding case-sensitive for the moment.  I'm thinking it probably isn't going to stay that way (!).  But...now is a good time to talk about any case-oriented concerns.

So if you hit problems with it, please add them to this thread, so that when the solution is put together it can account for it:

https://forum.rebol.info/t/case-insensitivity-vs-case-preservation-cant-have-both/1439/19?u=hostilefork
