### ISSUE TITLE
Bug in IMPORT 'MODULE

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#1124]
`r3 --do "import 'module"`
=>
** Error: Cannot FIND evaluative values w/o QUOTE
** Where: find switch load-module applique import do catch then _ do console
** Near: [*** system/modules source 2 ** else [
    return blank
]

(tested with Android nodebug 92171dcf)

**Comment by hostilefork** [comment]
I don't know what that's supposed to do (load something called %module.reb ?)

If so, perhaps this addresses it:

https://github.com/metaeducation/ren-c/commit/6dfe294be4c5663f9d5de0e2dd87d678f30ba529

**Comment by giuliolunati** [comment]
It's supposed to search %modules.reb in system/options/module-paths.
I use it a lot.

**Comment by hostilefork** [comment]
Hopefully you see the gist of what ^ does.  It is like QUOTE but a bit different...

     >> x: 10

     >> ^ x
     == '10

     >> ^x
     == 10

     >> ^(x + 20)
     == '30

     >> ^[a b c]
     == '[a b c]

Because QUOTED! values now append the value without the quote, you have some nice ways of doing things "as is"

     >> append [a b c] ^[d e]
     == [a b c [d e]]

But there's an important twist...

    >> ^(null)
    ; null

And there's actually other twists with **^()** which are about making it possible to write usermode code like UPARSE which chains invisibles.  Feel free to ask any questions on Signal if you find anything confusing...
