### ISSUE TITLE
FYI "$R3_MAKE" ../make.r --help

### ISSUE THREAD

**Issue by OneArb** [metaeducation/ren-c#1155]
```"$R3_MAKE" ../make.r --help```

** Script Error: commands/2 has no value
** Where: if _ _ old-do _ do _ iterate if do catch either else _ do
** Near: [
    help commands/2 ~~
    quit]
** File: ../make.r
** Line: 1089

```$R3_MAKE" ../make.r --help TARGETS```

definitions: ["NDEBUG"
    "OS_STACK_GROWS_DOWN" "ENDIAN_LITTLE" "HAS_LL_CONSTS" "USE_PIPE2_NOT_PIPE" "__LP64__"]
includes: [%/home/ura/Documents/,,%20backup%20need%20level-2/dev/ren-c/src/include/ %prep/include/]
libraries: [make object! [
    [class output flags]
    [
        class: #dynamic-extension
        output: <gnu:m>
        flags: _
    ]
] make object! [
    [class output flags]
    [
        class: #dynamic-extension
        output: "dl"
        flags: _
    ]
]]
cflags: [<gnu:-fvisibility=hidden>]
ldflags: [<gnu:-fvisibility=hidden> <gnu:-rdynamic>]
debug: false
optimization: 2
BUILTIN EXTENSIONS:
[Network Stdio Locale View UUID Crypt Time Filesystem Process Console Debugger DNS UTF]
DYNAMIC EXTENSIONS:
[]
** Error: 

UNSUPPORTED TARGET --help TARGETS
TRY --HELP TARGETS

** Where: fail else for-each3 for-each do catch either else _ do
** Near: [
    fail [
        newline
        newline
        "UNSUPP...
** File: ../make.r
** Line: 2094

```"$R3_MAKE" ../make.r --HELP TARGETS```

definitions: ["NDEBUG"
    "OS_STACK_GROWS_DOWN" "ENDIAN_LITTLE" "HAS_LL_CONSTS" "USE_PIPE2_NOT_PIPE" "__LP64__"]
includes: [%/home/ura/Documents/,,%20backup%20need%20level-2/dev/ren-c/src/include/ %prep/include/]
libraries: [make object! [
    [class output flags]
    [
        class: #dynamic-extension
        output: <gnu:m>
        flags: _
    ]
] make object! [
    [class output flags]
    [
        class: #dynamic-extension
        output: "dl"
        flags: _
    ]
]]
cflags: [<gnu:-fvisibility=hidden>]
ldflags: [<gnu:-fvisibility=hidden> <gnu:-rdynamic>]
debug: false
optimization: 2
BUILTIN EXTENSIONS:
[Network Stdio Locale View UUID Crypt Time Filesystem Process Console Debugger DNS UTF]
DYNAMIC EXTENSIONS:
[]
** Error: 

UNSUPPORTED TARGET --HELP TARGETS
TRY --HELP TARGETS

** Where: fail else for-each3 for-each do catch either else _ do
** Near: [
    fail [
        newline
        newline
        "UNSUPP...
** File: ../make.r
** Line: 2094

**Comment by hostilefork** [comment]
Sigh.  Thanks for reporting it.  Though Rebmake is nightmare fuel.  Explanation of how it got that way:

  https://forum.rebol.info/t/new-build-executables-new-build-strategy/1432

The upside of it has been that since it is a sprawling codebase written by someone else that has to be kept working, it's taught a lot of lessons about what's needed.  Unintentional splicing ran wild, and it was way too easy to wind up appending `#[none]` (blank) to places it shouldn't be that it drove the design for NULL (and none as the "new #[unset]", e.g. **~**).

  https://forum.rebol.info/t/shades-of-distinction-in-non-valued-intents/1604

Anyway... that --help code was a noble effort grafted on by Giulio.  In the spirit of "there's something to learn by keeping it working" I've patched it and added a call to help in the CI to test it... running **`--help`** and **`--help all`**

  https://github.com/metaeducation/ren-c/actions/runs/6254770515/job/16982924616#step:18:61
