### ISSUE TITLE
to-string read

### ISSUE THREAD

**Issue by gregit** [metaeducation/ren-c#155]
I'd like to rewrite rebelBB forum using R3. As a very first step, I'm trying to load all the messages that are currently stored in a file, using **R2**, this way:
```
; to read
threads: do read config/path-forum
; to save
write config/path-forum mold threads
```
But this is what I get, so far, using **Ren-C**:
```
>> do read %threads.txt
** Syntax error: invalid "word-get" -- ":"
** Where: to case load function! do
** Near: (line 14) suivi: join calcul :  i

** Note: use WHY? for more error information

>> to-string read %threads.txt
** Script error: missing or unsupported encoding marker
** Where: to to-string
** Near: string! :value
```

a threads.txt sample is currently available here: http://r3al.org/threads.txt

What should be the correct way to load it?

**Comment by hostilefork** [comment]
Rebol2 had byte-sized characters, and strings and binaries were "the same".  In terms of source code and string conversions, Rebol3 speaks UTF-8.  Once a string is loaded it is an abstract series of "codepoints".

If you're not familiar with UTF-8 it is a way of encoding multi-byte characters where the low 128 (0x00 => 0x7F) are the same as ASCII, and then it gets kind of weird about the way the high bit set chars work...for technically interesting reasons.

To load your file you'd have to convert it.  e.g. if it's not pure ASCII and uses some "other encoding" giving meanings to the higher valued bytes, you have to translate that.  Over time there have been all kinds of different uses for those 0x80 - 0xFF bytes... on some old PCs they did things like use those numbers for characters that draw boxes--for instance:

https://en.wikipedia.org/wiki/Code_page_437

But on others they did other things.  What you need to do is find out what format your file is in, and then convert it to UTF-8.

I tried converting it with a web form and guessing the format, but it didn't work the first time I tried it because the file was too big...and also I'd be guessing from the drop-down of what format it's in!  So the main thing you need to do is find out what character encoding you're using and then get it to UTF-8.  If you need assistance w/that please use StackOverflow Q&A + chat!

**Comment by hostilefork** [comment]
Also...

> I'd like to rewrite rebelBB forum using R3 [...] using Ren-C:

That is very exciting news, though it may not be easy!  Do be aware that Ren-C's current goals are very much about solving giant design problems, so it does not have a proper ["git flow"](http://nvie.com/posts/a-successful-git-branching-model/) system by which releases are vetted for users.  The group of people using it are very aware *they're part of a living experiment*, and that it really is about solving the big big things, for instance:

http://chat.stackoverflow.com/transcript/message/26915159#26915159

This is why you find no binary downloads.  I'm pleased you've already taken step 1 of being part of the living experiment by cloning and building it!  Day to day support and excitement is in chat, and we have a big exciting thing going on right as we speak which is going to tie up my whole day I think.  :-)

*(Not trying to scare you, but I'm just letting you know what you're getting into.  :-)  And that I am unable to provide support for R3-Alpha, which is now officially light-years behind Ren-C in terms of implementation.  I can only support the vision I have, which is a tremendous amount of work in its own right!  I will say though, that [I am working with Atronix Engineering](http://www.atronixengineering.com/downloads) so that we both use the same core, and they will use Ren-C in their GUI build...there's no specific deadline for that transition, but it's what they want to do.)*

But we do try and provide support as we're working.  Most problems are answered and closed in chat quickly.

**Comment by gregit** [comment]
Thanks for the advice!
I did:
```
iconv -f LATIN1 -t UTF-8 threads.txt > threads.utf8
```

then:
```
>> threads: to-block read %threads.utf8
== [[[[20t...

>> length? first threads
== 809
```

It works!


I'm now closing this issue :)

**Comment by hostilefork** [comment]
Very cool.  But please, I do urge you, that as you find new and bizarre behaviors to ask why that thing was changed, and learn why.

I have had some *very* tough and bitter arguments with those who would rather live in the universe where Rebol2 was maintained as-is, and who are not ready to see the necessary corrections.  I think that it's now probably important for people to look at the schematics and decide if they want to go with Red or Ren-C-based Rebol.  I'm willing to talk about it.

But there will be differences!

**Comment by gregit** [comment]
I understood the purpose of Ren-C to get back in a more clean and modulari approach than the R3/View from Saphirion then Atronix. It's very good if in the end Atronix can just use a Ren-C dll and everyone on R3 get back on a common Core project.

About R2 vs R3 vs Red: everyone must know there are differences, but I don't want to choose. They all belong to the Rebol community and we should remain unified around this single community. Loosing R2 folks means loosing R3 or Red folks.

Agreed SO is, maybe, a better place for my issues/questions. I have indeed too little time and doing some Rebol in between things and I can't follow-up with all channels (AltMe, SO, github, forums, ...)

Please see this RebelBB port to R3 as a test case. I might hit real bugs or not. In the end it is testing anyway.

**Comment by hostilefork** [comment]
> It's very good if in the end Atronix can just use a Ren-C dll and everyone on R3 get back on a common Core project.

Yes, this is my goal.  That is why I started Ren-C from their code *but* with the GUI ripped out.  I didn't want a lot of it... it wasn't in "my interest".  But I wanted it to be easy to re-uptake, which means everything like FFI was needed, and people needed https, etc.  So I bit the bullet and grafted what I wanted to do on the Saphirion=>Atronix code instead of starting from what was open sourced 12-Dec-2012.

And I'm bending over backward in many ways to maintain legacy compatibility.  There is something called `do <r3-legacy>`.  If you missed that card:

https://trello.com/c/LAAI9pdo

> Please see this RebelBB port to R3 as a test case. I might hit real 
> bugs or not. In the end it is testing anyway.

I am thrilled so please don't hear it otherwise.  I'm just doing expectation-setting and hoping you are ready for a potentially bumpy ride.  :-)
