### ISSUE TITLE
Difference in behavior regarding SELF object member setting

### ISSUE THREAD

**Issue by kealist** [metaeducation/ren-c#157]
In rebolsource.net:

    >> b: object [a: 1 b: func [][self/b: 2]] b/b
    ==2

In Ren-C:

	>>  do <r3-legacy>
	== none

	>>  b: object [a: 1 b: func [][self/b: 2]] b/b
	** Script error: cannot set/unset self - it is protected
	** Where: b
	** Near:

	** Note: use WHY? for more error information

**Comment by hostilefork** [comment]
Many things involving SELF are now "different", because SELF is now very different... and no longer a hardcoded binding hack.  *(Though it's a hardcoded generator hack until the next phase, which will come after the current changes have had a chance to shake out.)*

In any case, this *particular* issue should now work as expected, with the same behavior in `<r3-legacy>` or not:

    >> b: object [a: 1 b: func [][self/b: 2]] b/b
    == 2
