### ISSUE TITLE
Problem with lenght

### ISSUE THREAD

**Issue by no-e-in** [metaeducation/ren-c#159]
In Linux 32-bit x86
```
>> length 'a
r3: ../src/core/m-stacks.c:314: DSF_VAR_Debug: Assertion `n <= call->num_vars' failed.
Annullato (core dump creato)
```

**Comment by hostilefork** [comment]
Thank you for the report!  The assertion is a protective one for the debug build.  This relaxes the situation a little for that case:

https://github.com/metaeducation/ren-c/commit/0a79a1303fe2eb518146521e38d8782f249fa982

There was a bug in the handling of length of a word before, and it was a bit weird.  Here's the problem that removing the ability to take the length was trying to address.  Look at [the original open source A_LEN action for getting the length of a WORD!](https://github.com/rebol/rebol/blame/25033f897b2bd466068d7663563cd3ff64740b94/src/core/t-word.c#L87). Then try this:

    >> length? to-word to-string to-char 126 
    == 1

    >> length? to-word to-string to-char 128 
    == 2

It's giving you a UTF-8 byte length back for the symbol. That's not right.  I thought the best answer was to back off, for now, on allowing word length to be taken... because **length quote foo:** is a little ambiguous... do you want 4 or 1?  It's one word, it has three characters in its "spelling", four when formed... it's a bit of a challenge.

Your input is welcomed going forward, here or [in chat](http://chat.stackoverflow.com/rooms/291/rebol-and-red).  But I'm closing the issue as "should have just given an error", which it now does!  Thanks!

**Comment by hostilefork** [comment]
Also, what doesn't have an e in it?
