### ISSUE TITLE
Use of the term `module` should be disambiguated in source and documentation

### ISSUE THREAD

**Issue by asampal** [metaeducation/ren-c#161]
Currently, the source uses the word `module` to refer to 3 things: a C source file, a Rebol extension, and Rebol 3 modules, as defined by the namespace subsystem implemented by BrianH.

I propose that these uses be disambiguated so that newcomers to the source can simply search for `module` (case insensitive) and be certain that any results will refer to the namespace subsystem.

The question is what to call the other "modules". I'll propose some alternatives here:
C source module => `c_unit`, `source_unit`
Rebol extension module => `rxt_unit` (`RXT_MODULE` is sometimes used for these currently), extension unit (when spelled out fully)
I'd prefer not to rename these two to `module` with a prefix or suffix, but to change away from the word `module` altogether when not referring to namespaces, to make for straightforward searching.

Another possibility might be to change the use of `module` to `namespace` when referring to BrianH's construct. Given that there's not much code out there using these, the impact should be minimal.

One criteria in renaming might be to try and use the same terminology that developers are used to while keeping in mind that down the road we'll probably need a word to refer to a downloadable bundle of namespaces (along with other resources). Here's what some of the popular languages are using:

Language | namespace | bundle
--------------|-----------------|-----------
Python | module | package
JavaScript | module | package
Java | package | jar/library
Clojure | namespace | jar/library
Common Lisp | package | library
Ruby | module | gem
C++ | namespace | 

Any opinions?

**Comment by hostilefork** [comment]
In C and C++, unit most directly evokes the technical term "translation unit"

http://stackoverflow.com/questions/1106149/what-is-a-translation-unit-in-c

So if you're referring to a C file *and* its includes, taken together as the thing that makes a single object file, that might make sense to call a "unit".  But I think the uses you are referring to like:

    **  Module:  a-stubs.c
    **  Summary: function stubs
    **  Section: environment
    **  Author:  Carl Sassenrath
    **  Notes:

...that would be better served just by following Rebol conventions in general, e.g. `File: %a-stubs.c`, or whatever.  We have an upcoming shift where we're going to keep rolling with the changes from @Brett's conversion and actually have Rebol-loadable data in the comments at the top of the files, so we need to look at that all holistically as to what the module notes would be like in the module repository.  The one that doesn't allow ASCII 9 characters in it, and all that other good stuff.  :-)

As for what to call the RXTs... hum.  Ask @zsx.  I agree it would likely be a good idea to not call them "modules".

I think module is an okay name for what the BrianH-implemented-"module pattern" is, better than "namespace".  Maybe just because "namespace" is such a loaded term in C++ and Rebol is coming from a C/C++ implementation, so it matters.  Though as I have said lately it may be the case that there is no MODULE! type, that it's just OBJECT!.  We need to take the insights from definitional return and apply them to that question.

If you want to switch out the C module with File, and consult with @zsx and get an answer on an rxt change he can live with, I'll accept the PR.

**Comment by hostilefork** [comment]
@codebybrett has swapped out "Module" => "File" in the header conversion:

https://github.com/codebybrett/rebol-source-scripting/issues/1#issuecomment-169917927

I'll consider this issue to be closed for now, with the understanding that we only use the word **module** specifically for the userspace implemented-in-Rebol-itself definitionally-scoped module system, which hopefully will be further reigned in as things move along here.
