### ISSUE TITLE
host-table.inc should be renamed to host-table.h

### ISSUE THREAD

**Issue by asampal** [metaeducation/ren-c#162]
When using syntax coloring, file type detection is usually based on extensions. I noticed in Code::Blocks that this file isn't using the intended theme. Is there a good reason that the extension is .inc for this one file?

**Comment by hostilefork** [comment]
This is intentional, and idiomatic in C/C++

What it means is that something is a file meant to be #include'd but that contains variable definitions, hence any project must include it at most once in the overall link.

So this would be an "illegal" header, and cued by the .inc name:

    /* foo.inc */
    int x;

Whereas this would be okay as a header:

    /* foo.h */
    extern int x;

Of course, it's just a convention, the C preprocessor doesn't know the difference.  If you #include something it just pastes it in.
