### ISSUE TITLE
codepoint 128169 too large for current interpreter

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#165]
>> to string! read https://matrix.org:8448/_matrix/client/api/v1/publicRooms?access_token=...
    ** Internal error: codepoint 128169 too large for current interpreter
    ** Where: to
    ** Near: string! read https://matrix.org:8448/_matrix/client/api/v1/p...

on the other hand

    >> print read https://matrix.org:8448/_matrix/client/api/v1/publicRooms?access_token=...

works OK

**Comment by hostilefork** [comment]
Interestingly, this is an artifact of what was deemed a misguided decision with PRINT *(although it's on the right path of what will be done)*.

The "misguided decision" was that PRINT of a BINARY! would do "unfiltered" output.  Whatever you gave it as binary would just be thrown out to your native console as those binary bytes.  I think this is going to be the behavior of **write stdout #{...}** but not of PRINT, which will be effectively such that **print x** is **print form x**, with a potential slight exception.

So anyway, this is why you aren't getting a problem with the **print read**.  It's just spewing those bytes out without going through a conversion to Rebol strings first.  Currently there is a limit to the codepoints that they can only go up to 0xFFFF and be represented in Rebol strings internally.

What will likely happen here is that you will get the same error either way... as FORM of a BINARY! will not be "MOLDing it", rather it will be considered a request to convert from UTF-8 bytes.

**Comment by hostilefork** [comment]
I should point out that longer term, if-and-when such resources are available, the plan for the high unicode points such as these is the same as Red's, which is the same as Python's:

http://www.red-lang.org/2012/09/plan-for-unicode-support.html

e.g. it will adjust the internal sizing to wider character points on an as-needed basis if that string instance requires it.  (Similar to how it uses byte-sized characters if it can get away with it today, bumping it up to 2-bytes per character on demand.)  But UTF-8 will remain the standard for the APIs and data exchange.

**Comment by hostilefork** [comment]
So in the realm of our current thinking, the bug here *is actually that print isn't giving an error*.  PRINT will be willing to accept BINARY! as UTF-8 and will interpret it as a string.  WRITE STDOUT of a BINARY! will be raw and "full transport" so there will be no interpretation of the byte string, giving you the non-erroring behavior here.

But that's already known and being tracked elsewhere.  To mitigate problems here I've updated the error message to be clearer.  Odds are that you didn't have a high codepoint in UTF-8 encoded data, but rather you had non-UTF-8 encoded data that when looked at as UTF-8 *would* reflect a very high codepoint.  I doubt you're working with archaeological analyses that have Egyptian Linear B in them, so you probably just have something in a non-UTF8 byte format.  See @rgchris's cleaning script for something that may help:

http://reb4.me/r3/clean

Because the case of using non-UTF-8 is more likely I've changed the message to hint that (though still mentioning the codepoint, just in case).  Also changed another generic message that really only means "bad UTF-8" right now to say exactly that.

https://github.com/metaeducation/ren-c/commit/7920880819dea97bf6d0206a72dfbf42381ab982

Hopefully that will help with issues like this in the near term!
