### ISSUE TITLE
C Source File ../src/core/c-error.c, Line 209

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#166]
```
>> to-string read {"start":"START","chunk":[{"name":null,"world_readable":false,"topic":null,"num_joined_members":1,"room_id":"!AFTBMxxxx:matrix.org","guest_can_join":false,"aliases":["##????::matrix.org:matrix.org"]},
.... 
{       
{       
{       {       
{       
{       
{       }}}}

*** NO "SAVED STATE" - PLEASE MENTION THIS FACT! ***
Rebol Internal Error:
If you need to file a bug in the issue tracker, please give thorough
details on how to reproduce the problem:

    http://github.com/rebol/rebol-issues/issues

Include the following information in the report:

C Source File ../src/core/c-error.c, Line 209
** Special error: halted by user or script
```

I accidentally pasted part of of a long json string into the console.
I was left with the console showing several open { strings.
I tried ^C, and then just typed several } to close the string.
Then I got that error.

**Comment by hostilefork** [comment]
Thank you for the report, I will look into it.

The multi-line extensions to the console were a [recent contribution](https://github.com/metaeducation/ren-c/pull/58) and could certainly use more testing, so glad you are doing so!  However, the main goal of Ren-C is to support the cross-platform GUI console experience of [Ren Garden](https://youtu.be/0exDvv5WEv4?t=243).

(So if you happen to know any C++ and want to dig in and work with that, that would be great :-))

**Comment by hostilefork** [comment]
Motivated by the idea of getting Ren-C to no issues reported, for this I stopped to look at my favorite code...the R3 console...

*(Note: In the FAQ I wrote up an explanation of the vision of [what should ACTUALLY be happening for a text console](https://github.com/metaeducation/ren-c/wiki/FAQ#if-ren-c-is-a-library-why-does-it-have-an-r3-console).  If that interests you, it's a place where Rebol programming is needed.  The short example should be motivating of just how much better the console could be if it were pushed out of this part that has no good reason to be written in C.)*

https://github.com/metaeducation/ren-c/commit/ed0ea34795b2c2e4b7c1d4263a626da42bad0439

I had a repro case and doing this made it go away.  Let me know if you can reproduce it, otherwise I'll consider this closed...
