### ISSUE TITLE
segfault in make object!

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#171]
This crashes for me:

    make object [a: 1] object [b: 2]

**Comment by zsx** [comment]
I just ran into this same crash. The problem is in Merge_Frames: https://github.com/metaeducation/ren-c/blob/master/src/core/c-frame.c#L809. Because `Collect_Frame_Inner_Loop` looks for `ANY_WORD` (https://github.com/metaeducation/ren-c/blob/master/src/core/c-frame.c#L418), while the key words in a frame have a type of TYPESET (https://github.com/metaeducation/ren-c/blob/master/src/core/c-frame.c#L425), none of the keys is added to `binds`, which causes an assert failure at https://github.com/metaeducation/ren-c/blob/master/src/core/c-frame.c#L418

**Comment by zsx** [comment]
No idea why you changed the datatype of keywods in a frame to typeset, but the following patch fixes this problem.
```
diff --git a/src/core/c-frame.c b/src/core/c-frame.c
index 6114933..d5a23eb 100755
--- a/src/core/c-frame.c
+++ b/src/core/c-frame.c
@@ -415,18 +415,21 @@ void Collect_Context_Keys(REBFRM *prior)
 static void Collect_Frame_Inner_Loop(REBINT *binds, REBVAL value[], REBCNT modes)
 {
     for (; NOT_END(value); value++) {
-        if (ANY_WORD(value)) {
-            if (!binds[VAL_WORD_CANON(value)]) {  // only once per word
-                if (IS_SET_WORD(value) || modes & BIND_ALL) {
+        if (ANY_WORD(value) || ((modes & BIND_TYPESET) && IS_TYPESET(value))) {
+                       REBCNT sym = ANY_WORD(value) ? VAL_WORD_CANON(value) : VAL_TYPESET_CANON(value);
+            if (!binds[sym]) {  // only once per word
+                if (IS_SET_WORD(value)
+                    || ((modes & BIND_TYPESET) && IS_TYPESET(value))
+                    || modes & BIND_ALL) {
                     REBVAL *typeset;
-                    binds[VAL_WORD_CANON(value)] = ARRAY_LEN(BUF_COLLECT);
+                    binds[sym] = ARRAY_LEN(BUF_COLLECT);
                     EXPAND_SERIES_TAIL(ARRAY_SERIES(BUF_COLLECT), 1);
                     typeset = ARRAY_LAST(BUF_COLLECT);
                     Val_Init_Typeset(
                         typeset,
                         // Allow all datatypes but UNSET (initially):
                         ~FLAGIT_64(REB_UNSET),
-                        VAL_WORD_SYM(value)
+                        ANY_WORD(value) ? VAL_WORD_SYM(value) : VAL_TYPESET_SYM(value)
                     );
                 }
             } else {
@@ -806,7 +809,7 @@ REBFRM *Merge_Frames(REBFRM *parent1, REBFRM *parent2)
     Collect_Context_Keys(parent1);
     // Add parent2 words to binding table and BUF_COLLECT:
     Collect_Frame_Inner_Loop(
-        binds, FRAME_KEYS_HEAD(parent2), BIND_ALL
+        binds, FRAME_KEYS_HEAD(parent2), BIND_ALL | BIND_TYPESET
     );

     // Allocate child (now that we know the correct size):
diff --git a/src/include/sys-core.h b/src/include/sys-core.h
index 75d6234..404dba4 100644
--- a/src/include/sys-core.h
+++ b/src/include/sys-core.h
@@ -230,7 +230,8 @@ enum {
     BIND_GET = 8,       // Lookup :word and use its word value
     BIND_NO_DUP = 16,   // Do not allow dups during word collection (for specs)
     BIND_FUNC = 32,     // Recurse into functions.
-    BIND_NO_SELF = 64   // Do not bind SELF (in closures)
+    BIND_NO_SELF = 64,  // Do not bind SELF (in closures)
+    BIND_TYPESET = 128  // Bind words of TYPESET!
 };

 // Modes for Rebind_Values:
```

**Comment by hostilefork** [comment]
Thanks for the change, I'll get it in shortly...

> No idea why you changed the datatype of keywords in a frame to typeset

I've explained this before, for reasons both forward-looking and present-crashing.

The present-crashing reason was because an "UNWORD" contained a symbol and the information for a typeset, where a binding would be.  This meant that if an UNWORD ever leaked out into userspace, the information in its typeset bits would be interpreted as a binding.  There were countless cases of this, and hard to spot because you really had to put assertions all over of a "word" not being an "unword" to start catching them.  One R3-Alpha example:

     >> foo: func [x [series! any-object!]] []
     >> bind? select to-object try [foo 1] 'arg2
     == Segmentation fault: 11

The future-forward reason is because the "64" (63, actually) type limit is not a viable long-term strategy for a language.  User-defined types will need to be in a series.  Hence typesets of the optimized "only system types" will use their 64 bits for a bitset (as today), whereas typesets which are lists of type objects will use their bits differently.  How they interpret the bits will be based on flags in the header.  This functionality would need to apply to keys in frames and params in function arglists.

So all told it is more sensible to call them "typesets with a symbol in them" than UNWORD.  Trying to explain what an UNWORD is ("It's a word, but it isn't") has an intrinsically poor quality, and it makes the code harder to learn.  There's already a name for the thing that can be used--which is typeset--and that helps the present and the future.  As a fringe benefit, a typeset with a symbol that leaks into user code acts like a typeset.

Of course, it's a speedbump for those expecting it to be a word, but as with all things it's an ongoing process.  There's a debug check to alert incorrect uses of VAL_TYPESET_SYM when VAL_WORD_SYM was intended or vice versa which was supposed to catch as many wrong assumptions as possible, but it looks like this one didn't get caught in that.

**Comment by zsx** [comment]
OK, now I remember. Thanks.

Here is an updated version:
```
diff --git a/src/core/c-frame.c b/src/core/c-frame.c
index 6114933..d15589f 100755
--- a/src/core/c-frame.c
+++ b/src/core/c-frame.c
@@ -406,6 +406,23 @@ void Collect_Context_Keys(REBFRM *prior)
         binds[VAL_TYPESET_CANON(keys)] = n++;
 }

+//  Collect_Symbol: C
+//
+// Collect a symbol
+//
+static void Collect_Symbol(REBINT *binds, REBCNT canon, REBCNT sym)
+{
+    REBVAL *typeset;
+    binds[canon] = ARRAY_LEN(BUF_COLLECT);
+    EXPAND_SERIES_TAIL(ARRAY_SERIES(BUF_COLLECT), 1);
+    typeset = ARRAY_LAST(BUF_COLLECT);
+    Val_Init_Typeset(
+        typeset,
+        // Allow all datatypes but UNSET (initially):
+        ~FLAGIT_64(REB_UNSET),
+        sym
+        );
+}

 //
 //  Collect_Frame_Inner_Loop: C
@@ -418,16 +435,7 @@ static void Collect_Frame_Inner_Loop(REBINT *binds, REBVAL value[], REBCNT modes
         if (ANY_WORD(value)) {
             if (!binds[VAL_WORD_CANON(value)]) {  // only once per word
                 if (IS_SET_WORD(value) || modes & BIND_ALL) {
-                    REBVAL *typeset;
-                    binds[VAL_WORD_CANON(value)] = ARRAY_LEN(BUF_COLLECT);
-                    EXPAND_SERIES_TAIL(ARRAY_SERIES(BUF_COLLECT), 1);
-                    typeset = ARRAY_LAST(BUF_COLLECT);
-                    Val_Init_Typeset(
-                        typeset,
-                        // Allow all datatypes but UNSET (initially):
-                        ~FLAGIT_64(REB_UNSET),
-                        VAL_WORD_SYM(value)
-                    );
+                    Collect_Symbol(binds, VAL_WORD_CANON(value), VAL_WORD_SYM(value));
                 }
             } else {
                 // If word duplicated:
@@ -804,10 +812,14 @@ REBFRM *Merge_Frames(REBFRM *parent1, REBFRM *parent2)
     Collect_Keys_Start(BIND_ALL);
     // Setup binding table and BUF_COLLECT with parent1 words:
     Collect_Context_Keys(parent1);
+
     // Add parent2 words to binding table and BUF_COLLECT:
-    Collect_Frame_Inner_Loop(
-        binds, FRAME_KEYS_HEAD(parent2), BIND_ALL
-    );
+    key = FRAME_KEYS_HEAD(parent2);
+    for (; NOT_END(key); key++) {
+        if (!binds[VAL_TYPESET_CANON(key)]) {
+            Collect_Symbol(binds, VAL_TYPESET_CANON(key), VAL_TYPESET_SYM(key));
+        }
+    }

     // Allocate child (now that we know the correct size):
     keylist = Copy_Array_Shallow(BUF_COLLECT);

```

**Comment by hostilefork** [comment]
Since I was "in the neighborhood" I went ahead and folded the fix to this in with what I was already doing with SELF.  The solution more resembles the second patch, in that the code which walks arbitrary Rebol value structures deeply and the code that collects from existing keylists stays separate--so there's no need to handle both typesets and words in the same function.  It just expands the frame collection to be able to check for dups:

https://github.com/metaeducation/ren-c/blob/4039cb660bd40384e4d851d71d9d7aa4f9d7ac0b/src/core/c-frame.c#L393

Thanks for the report/code...
