### ISSUE TITLE
typo in b-init.c

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#182]
[This comment](https://github.com/metaeducation/ren-c/blob/master/src/core/b-init.c#L876) would be "Create system/catalog/*natives* block" ?

**Comment by hostilefork** [comment]
Yup, longstanding since R3-Alpha:

https://github.com/rebol/rebol/blob/25033f897b2bd466068d7663563cd3ff64740b94/src/core/b-init.c#L606

...and I'm sure not the only incorrect comment. :-)  I'll slip in a change to it with something else.  We'd simply have too many commits in the log to be able to read them if every comment change got its own!

At some point, if manpower ever is available, each file should be given to a person to go over line by line to make sure it is all coherent.  So let's hope it gets good enough that the future where such attention is warranted exists!

**Comment by hostilefork** [comment]
Addressed by https://github.com/metaeducation/ren-c/commit/2fbd1c2faf0b0e88d2fb26593b6a2b0d2a9e6448
