### ISSUE TITLE
CALL (without /SHELL) does not work the same way as Rebol 2 CALL

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#19]
The following is interpreted as a path to a command:

    >> call {curl http://rebol.info}
    ** Access error: external process failed: "No such file or directory"
    ** Where: call
    ** Near: call "curl http://rebol.info"

Tested on 3.0.99.2.5

**Comment by hostilefork** [comment]
Just looking at the code, it seems that's in the sense that if it were a file name with spaces in it, then it would be calling it...

    call {My Cool Program.exe}

But what we might prefer would be if that be the behavior if it took a FILE!

    call %"My Cool Program.exe"

And then assume that if you pass it a string, you want it to go to the shell to process it...but if you pass it a block that means you want the individual elements to go into process call slots as ARGV[].

Then we get rid of /SHELL refinement as just what we presume if you get a string.

What say you, @ShixinZeng?

**Comment by earl** [comment]
Should write up a more reasoned response, but as that day may never come, I'll just cross-post my remarks from chat:

One major hassle is the divergence in calling interfaces in process creation. Windows: a single "command-line" string. POSIX: argv. We'll have to come up with a sensible cross-platform abstraction over that, eventually. I'm currently leaning towards standardising something argv-like, that means a i.e. a block with executable + arguments as @hostilefork describes as well. On top of that, we add some polish to transmogrify that block into a workable command-line string in the Windows world (that'll probably entail join + some escaping).

And if we go that route, implied `/shell` for a single string be, I think, a nice idea.

I wouldn't completely drop `/shell` even with that default behaviour, because there are more reasons than command-line splitting that might lead you to want to wrap your command in a shell (set up of a full environment, for example). And doing that, abstracted over platform-specifics with `/shell` is still nice.

**Comment by zsx** [comment]
Yes, the main idea is to make it work across POSIX and windows, and try to do as little  work as possible in terms of disassembling and reassembling arguments. 

For "call {curl http://rebol.info}" to work on POSIX systems, the interpreter needs to first break it down to ["curl" "http://rebol.info"], and pass it to exec*. It becomes complex, inefficient and inconvenient when the argument contains spaces (quotes would be needed to make them a one argument). e.g. "call {cmd this an argument with spaces and quotes ^"}". This puts burden on both the interpreter programmers (need to parse the argument) and script programmers (need to remember how to group the arguments) for no good.

When a block of arguments is passed in, it becomes very easy to handle the spaces in the arguments: "call [{this is an argument with spaces and quotes "}], the arguments are passed as-is to the underlying executable on POSIX systems (easy and efficient). On windows, quotes needs to be added and escaped when needed, and all of this can be handled by the interpreter without much performance penalty.

As for the /shell, it's very clear what it means when it's specified (running the command through the shell), but what it means when it's not? I take it as the opposite of "running through the shell": running the executable directly.

**Comment by hostilefork** [comment]
Migrated to Rebol Issues, as we don't want design discussions getting mixed up with Ren/C bug reports:

https://github.com/rebol/rebol-issues/issues/2225
