### ISSUE TITLE
PARSE with misplaced "??" crashes

### ISSUE THREAD

**Issue by gregit** [metaeducation/ren-c#190]
Granted it is not relevant to place a debug "??" at the end of a parse rule, but this crashes violently:

```
parse "1234" [any ["1" | "2" | "3" | "4"] ??]
Assertion failed: NOT_END(v), file ../src/core/n-data.c, line 1254
```
If a fix can be made for the console not to crash? This is anyway a low priority.

**Comment by hostilefork** [comment]
As crashes go, assertions actually aren't violent crashes... they're the less violent case.  "Somewhat anticipated" and point to what the problem is.  Some of them can even recover in release builds *(but we get much more information from debug builds, so please continue running a debug build if at all possible.)*

This pertains to a change in the internal rules regarding whether the marker inside memory that communicates the end of a series is reached is an "end value" (and hence you can ask it what its type is, and it will say END!) or if it's something "other" that does not have a value type.  There are many good reasons why the type was removed--besides simply that END! is not something that you should see in the list.  Here you see a part of parse that advanced an index and asked for a type before doing an explicit check to see if it is an END, and it's saying the END check should have preceded asking it anything about the TYPE! of that slot.

Anyway, this should hopefully resolve it:

https://github.com/metaeducation/ren-c/commit/6e5a9ec930f3e15e97268e16facb4228a5f5a13f

**Comment by hostilefork** [comment]
Believed to be closed...
