### ISSUE TITLE
or~ charset "a" charset "b"

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#196]
./src/core/c-do.c:742: Dispatch_Call_Throws: assertion "Is_Value_Managed(((REBVAL * const)((call_)->out)), TRUE)" failed

**Comment by hostilefork** [comment]
Fixed in https://github.com/metaeducation/ren-c/commit/661fbc31b9e7dde43ad3be5daef283a332be9015

Explanation: as you may have gathered... a series is in a manual memory managed state when it is first made.  This means the GC does not see it, and will not collect it.  You must either Free_Series() on it, or MANAGE_SERIES() to give it over to the GC at the end of a command to keep from being considered a leak.

To reduce the number of explicit calls to MANAGE_SERIES(), an assumption is made.  That assumption is that if you ever put a series into a REBVAL, you are doing so because you wish it to be taken by the garbage collector.  This is done by all the `Val_Init_XXX()` routines... so when you initialize a REB_BLOCK value it will ensure the series is shared if it is not already.

However, if you poke a series into a REBVAL as a field and do not use the Val_Init_XXX macros, you will bypass the code that ensures the code is managed.  Here we see that the Xandor_Binary() was doing just that... it tried to reuse the existing value cell and didn't go through the managed'ness.

Note that the very concept of "managed and unmanaged" was introduced by Ren-C.  In R3-Alpha, a series was GC-able from the moment of its creation.  Hence you could create a series and then free it, and it could wind up being a race as to whether the GC beat you to the punch or not.  If it didn't beat you then you might think you got away okay with your Free_Series(), but then another time you might not be so lucky...

**Comment by giuliolunati** [comment]
Ok, thank you also for clarification!
