### ISSUE TITLE
backtrace in script causes assertion failure

### ISSUE THREAD

**Issue by codebybrett** [metaeducation/ren-c#199]
Assertion failure when running a script containing breakpoint - see:
![breakpoint-assertion-failure](https://cloud.githubusercontent.com/assets/4524508/11991658/e797414c-aa70-11e5-8c89-f74b4e4413d6.png)

Steps to replicate:

do %breakpoint-test.reb ; uploaded as [txt](https://github.com/metaeducation/ren-c/files/71548/breakpoint-test.txt) here.
type backtrace at the breakpoint prompt.

**Comment by hostilefork** [comment]
Interim solution to the problem here:

https://github.com/metaeducation/ren-c/commit/08fdd3b15b93dc1957780a70098b5c4464a976aa

Also added it so that backtrace prints out, to avoid truncating long output:

https://github.com/metaeducation/ren-c/commit/57edc47143daae6a0b1b1987c996388b9e979788

Guinea pig, you may proceed.  :-)

**Comment by codebybrett** [comment]
Works!
