### ISSUE TITLE
PARSE returns false when using remove keyword

### ISSUE THREAD

**Issue by gregit** [metaeducation/ren-c#212]
Using remove keyword when parsing should not return false, but true instead:
```
>> str: "1234"
== "1234"

>>  parse str [any ["1" | [remove "2"] | "3" | "4"]]
== false

>> str
== "134"
```
Similar issue is found when using change with empty string:
```
>> str: "1234"
== "1234"

>> parse str [any ["1" | [change "2" only "6"] | "3" | "4"]]
== true

>> str
== "1634"

>> parse str [any ["1" | [change "6" only ""] | "3" | "4"]]
== false

>> str
== "134"
```

**Comment by hostilefork** [comment]
This is a pre-existing issue in R3-Alpha.

What's being run up against is that there is a "no progress rule" which applies to the looping construct ANY.  It is supposed to be "helpful" by making your PARSE less likely to infinite loop.  I do not consider it helpful, and would rather have good ways of debugging infinite loops by breaking into the parse, stepping...etc.

The workaround I've been offered in the past is to use the WHILE construct instead of ANY.  It does not have this *"no progress in the index will fail the rule"* clause:

    >> str: "1234"
    == "1234"

    >>  parse str [while ["1" | [remove "2"] | "3" | "4"]]
    == true

    >> str
    == "134"

I will suggest that for now.  But more importantly, to hang around in chat and elsewhere to register your vote on if this is reasonable, or if you think the no-progress rule is more harmful than helpful.  For instance: Red did not adopt it, I am opposed to it, Ladislav is opposed to it.  If there are enough votes against it and none for, then I say we drop the "feature".

**Comment by hostilefork** [comment]
I'm going to close this for now because there are a lot of things to tend to, and Ren-C doesn't seek to singlehandedly answer every ticket from CureCode (!).  There are enough "big issues" requiring systemic redesign...not to mention Ren-C's own bugs like the one you've hit that need to be repro'd and fixed.  This PARSE issue is just a simple mechanical question nearly any C developer could see where it is failing... remove the check or keep, etc.  So it's really a question more of public opinion than of coding.

But a note on that: in the future, please do be sure to test to find out if a behavior is pre-existing!  There is an online service to test R3-Alpha code quickly if you do not have a build handy at any particular moment:

http://tryrebol.esperconsultancy.nl/

Generally speaking, the right place to bring up design changes vs. addressing a crash would be chat, if possible (and CureCode once the GitHub import is finished)...because it's chatty and other people can jump in to help.
