### ISSUE TITLE
Non-ASCII words

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#221]
æ: 1 æ
 *** Script error: æ has no value

**Comment by hostilefork** [comment]
Okay I've taken a look, but this is right at the center of what you're working on, I'll give you a first crack at it... :-)

What I did was I went and looked at [Make_Word](https://github.com/metaeducation/ren-c/blob/938491cdf8e0d3f4ad5d71bb178131746efb4762/src/core/c-word.c#L183).  This routine is supposed to take in some UTF-8 bytes of a certain length and make a symbol out of it.  It should do so uniquely each time the case is different, but not when it is the same.

There is a situation here where Make_Word is giving back different numbers for the same bytes.  So if you add this right before the return:

    Debug_Fmt("Canon is %d len is %d", VAL_SYM_CANON(w), len);
    if (len == 2)
        Debug_Fmt("%d %d %d", str[0], str[1], str[2]);

You will get for the ae example above (run as %test.reb) something out like this before you get the error:

    Canon is 1838 len is 2
    195 166
    Canon is 1839 len is 2
    195 166

So somehow that hashing process above knows the length is two, knows the bytes are the same, yet they are getting hashed differently.  Perhaps given what you have been looking at you would know why this would be?

**Comment by giuliolunati** [comment]
When æ (c3 a6) word is first encountered,  it's stored as it was Ã¦ (c3 a3 c2 a6).
More general, hashing code expect strings encoded in utf8, but this is changed, right?

**Comment by hostilefork** [comment]
An ANY-WORD! should never change from UTF8.  It is not (currently) stored via a REBSER and a data pointer there.  It is stored in the symbol table.

An ANY-STRING! always has a REBSER and there are REBYTE and REBUNI variations.  You should never be seeing a STRING!'s data as UTF-8, because when it is being Scan_XXX loaded it is turned into either a REBYTE-size or REBUNI-size string, to make it more convenient for accessing directly a specific character at a position and to modify where each character is the same size.

I would not be all that surprised if there were bugs in the way things are done, because one thing to remember is that Rebol2 had no unicode support.  A STRING! and a BINARY! were the same thing.  so it was added after the fact, and because the types were not all that well differentiated and there were no assertions there were mistakes.

So if you are finding a hash that is making bad assumptions you are probably going where no one has gone before :-) and being a hero in fixing it if you find problems... because you are helping a lot for what I'd like to do with that, because of the plan I told you about to make STRING! able to do UTF-8 as another encoding (read-only, then decoded on demand if anyone tries to get a position into that string other than at the head...)

**Comment by hostilefork** [comment]
Thanks for the report, the investigation, the fix, and all the work you are doing!
