### ISSUE TITLE
Error "words has no value" in make prep

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#235]
Starting with commit 61f8c507, `make prep` fails with that error, then make r3 fails at b-ino.c -- I'm using ren-c as r3-make.

**Comment by hostilefork** [comment]
While we try to keep Ren-C working as building itself with its current version, there's no guarantee that if you keep a snapshotted older Ren-C that it will still work to use in a build.  It would be too hard to maintain %r2r3-future.r otherwise:

https://github.com/metaeducation/ren-c/blob/master/src/tools/r2r3-future.r

This is why we have the "anchor point" of R3-Alpha to work from.  So be sure to keep a copy of r3-alpha around to use as an r3-make if you run into trouble.  *(It will also be much faster if you are not running a debug build!... you could also build Ren-C with `-O2` and `-DNDEBUG` but generally I ask people not to do this!)*  You should be able to use the versions from either `http://rebolsource.net` or `http://rebol.com`.

If after you build with R3-Alpha as R3-Make and *then* build with the resulting Ren-C and it does not work, we have a problem that needs fixing.

**Comment by hostilefork** [comment]
I did notice one error message go by though, that wasn't causing a problem but needed fixing:

https://github.com/metaeducation/ren-c/commit/a60db6546db6cc731b994f901e1504abfcb6dbbb

Notice the behavior change, there... probably doesn't affect you, but it's the kind of thing that Ren-C isn't afraid to modify.

**Comment by giuliolunati** [comment]
Thank you, solved!

>.... you could also build Ren-C with -O2 and -DNDEBUG ...

Must manually edit makefile?

Giulio :-)

**Comment by hostilefork** [comment]
There are 3 pending alternative build systems... 2 CMake, one Rebol-based... but no one has set it up to make it work and fully support any of them!  There's a lot for me to do so I don't know what's up but you might be interested in:

[%build.reb](https://gist.github.com/earl/180d761ce5d27e411a6f)

That is one of the things we'd hope to use, to not need make or CMake at all (!)
