### ISSUE TITLE
Mismatch between systems.r and platforms.r

### ISSUE THREAD

**Issue by zsx** [metaeducation/ren-c#25]
0.3.02 is for windows-x64 in systems.r: https://github.com/metaeducation/ren-c/blob/master/src/tools/systems.r#L52, while in platform.r it's for dec-alpha: https://github.com/metaeducation/ren-c/blob/master/src/boot/platforms.r#L19

Mismatches for other platforms also exist.

**Comment by hostilefork** [comment]
Here is the list of the "historic" platform IDs for Rebol2:

http://www.rebol.com/release-archive.html

So as far as Rebol2 was concerned, 0.3.2 belonged to Windows NT on a DEC Alpha.

I am interested in seeing Rebol run on older systems and used by people who are hobbyists, because when you are loading up emulators it might be nice to have a modern tool that works in them.  Who knows what information might be locked up in old computers and archives.  But Windows NT DEC Alpha was fairly short-lived.

*(I had a copy of the install discs because it came in some NT pack back when MSDN had a subscription where they sent you basically every developer product that Microsoft made, but no DEC Alpha to run it on... possibly before your time.  :-P)*

I would have said it's a balance between whether we want to cause disruption of the ID numbers for the 64-bit builds from Atronix or not, and err on the side that DEC Alpha in the history just doesn't matter much.  Except @earl really thought we needed to have Ren/C go back to the [numbering scheme that hadn't declared 3.0 yet](https://github.com/metaeducation/ren-c/commit/89a75c71eb0c9d3a4a25e6924ac0c13761602e91).

In light of that already-disruption, I think Ren/C might go ahead and move the 64-bit windows build number out of the way.  Perhaps to 0.3.40 so all the 64-bit builds end in .40.  But @earl pointed out it could be better not to do that to keep people from "feature-testing" for 64-bit with `system/version/5 == 40`.  My vote would be to not worry about that and do it for consistency.

So my leaning would be change Windows 32-bit in Ren/C to 0.3.40.  But my stronger vote is to let @earl decide these issues.

**Comment by zsx** [comment]
Whatever decision it is, systems.r and platforms.r should agree. Right now, I've got this for a Windows x86_64 build (system/platform says it's dec-alpha):

**************************************************************************
**                                                                      **
**  REBOL 3.0                                                           **
**                                                                      **
**    Copyright: 2012 REBOL Technologies                                **
**               All rights reserved.                                   **
**    Website:   www.REBOL.com                                          **
**                                                                      **
**    Version:   2.102.0.3.2                                            **
**    Platform:  Windows dec-alpha                                      **
**    Build:     21-Jul-2015/14:31:30                                   **
**                                                                      **
**    Language:  English                                                **
**    Locale:    United States                                          **
**    Home:      Z:\r3.git\make\debug\                                  **
**                                                                      **
**************************************************************************

**Comment by hostilefork** [comment]
I wonder if there's any real reason for platforms.r to be distinct from systems.r anyway.  Couldn't it all be in the same table?

**Comment by zsx** [comment]
I think the reason is platforms.r contains information to be embedded into the interpreter, and systems.r contains information to build the interpreter.

**Comment by earl** [comment]
Fixed it to 3.3 for now, to be in line with [Atronix](https://github.com/zsx/r3/blob/atronix/make/makefile-mingw-64#L5), [Rebolsouce](https://github.com/rebolsource/r3/blob/b062bbbb0b09a0394c9a1345c6c29dd228f5de37/src/tools/systems.r#L28), and Saphirion.
