### ISSUE TITLE
boot error in commit 375fcf

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#268]
Commit 375fcf introduces this runtime error (natively compiled for Android5):
Rebol Internal Error
If you need to file a bug in the issue tracker, please give thorough
details on how to reproduce the problem:

    http://github.com/rebol/rebol-issues/issues

Include the following information in the report:

C Source File ../src/core/b-init.c, Line 113
PANIC #111
** Boot Error: (string table not decompressed yet)

**Comment by hostilefork** [comment]
Hm, I spotted at least one problem, and I don't know how it got past me.  So let me know if this is enough to fix it:

https://github.com/metaeducation/ren-c/commit/aba507c741c0e1ca293fe50efccc17c409860c16

**Comment by giuliolunati** [comment]
Same error, in line 113

**Comment by hostilefork** [comment]
@giuliolunati Hm, well the error says what's wrong... the REBVAL is supposed to be a certain size and it's not.  Something is throwing it off that's unique to Android, because the travis builds for other platforms are working:

https://travis-ci.org/metaeducation/ren-c

Could you [try that SHOW_SIZEOFS define](https://github.com/metaeducation/ren-c/blob/master/src/core/b-init.c#L69) and see if you can figure out why it's not coming out to the right size?

For this structure:

https://github.com/metaeducation/ren-c/blob/master/src/include/sys-rebval.h#L701

On 32-bit platforms it expects a 32-bit header, a 32-bit "extra", and a 64-bit payload...

**Comment by giuliolunati** [comment]
Hi, got this:
8 any_word
8 any_series
8 integer
8 decimal
2 char
8 datatype
8 typeset
8 symbol
8 time
8 tuple
8 function
8 any_context
8 pair
12 event
4 library
8 struct
8 gob
12 money
8 handle
8 all
Rebol Internal Error
If you need to file a bug in the issue tracker, please give thorough
details on how to reproduce the problem:

```
http://github.com/rebol/rebol-issues/issues
```

Include the following information in the report:

C Source File ../src/core/b-init.c, Line 113
PANIC metaeducation/ren-c#111
*\* Boot Error: (string table not decompressed yet)

**Comment by hostilefork** [comment]
Ok... well, darn.  Why are none of the other builds getting this error?  :-/

Thanks, I am on it...!

**Comment by giuliolunati** [comment]
Note: 
sizeof(void *) == 4
sizeof(REBVAL) == 20

**Comment by hostilefork** [comment]
Ok, well this involves two of my least favorite types... the money type and the event type...and I'm not overly concerned about them over the long term.  But here's an attempt to workaround the issue for now:

https://github.com/metaeducation/ren-c/commit/01699d7b198518d20fff3da50bb7c0be69d7b2df

**Comment by giuliolunati** [comment]
It works! :-)
