### ISSUE TITLE
Internal error: codepoint xxx too large (or data is not UTF-8)

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#271]
```
>> test-data: #{22646973706C61796E616D65223A224A6F6E20F09F98BA22} 
== #{22646973706C61796E616D65223A224A6F6E20F09F98BA22}

>> print test-data
** Internal error: codepoint 128570 too large (or data is not UTF-8)
** Where: print
** Near: ... #{22646973706C61796E616D65223A224A6F6E20F09F98BA22} ??
```

**Comment by hostilefork** [comment]
Is what you expect to get out of this data ["Smiling Cat With Open Mouth"](http://www.fileformat.info/info/unicode/char/1f63a/index.htm)?

If so, then that is indeed a limit of the system.  The error is correct that it decodes to that codepoint, and is too large for the current method to handle (decoding the strings into 16-bit wide codepoints to manipulate)--though otherwise it is valid UTF-8

It would be supported in the [UTF-8 Everywhere](http://utf8everywhere.org/) transition, as strings would never be decoded into the 16-bit codepoints.  This would mean that processing strings would have to do "on-the-fly" decoding for the purposes of seeking around within strings.  But though it adds a bit of overhead for that, the overall picture is a win--I believe--as way too much time and space is wasted converting the strings.  (The UTF-8 manifesto makes the arguments)

If this is a blocking problem for you and your data streams frequently have such characters you want to filter out, we could add a "forgiving" version of TO-STRING which takes a character (or character sequence) to substitute for decoding errors, and just keeps going.

**Comment by IngoHohmann** [comment]
Yes, I guess it is "smiling cat with open mouth".

The data comes from matrix.org chat, where data like this is indeed frequent (mostly to find problems in UTF-8 handling, but sometimes just for fun).

Now, that I can read https on my raspberry, this problem has been promoted to blocking for me. And I would really appreciate to have the forgiving TO-STRING, until UTF-8 everywhere is there.

**Comment by hostilefork** [comment]
> I would really appreciate to have the forgiving TO-STRING, until UTF-8 everywhere is there.

Ok, will do...

**Comment by hostilefork** [comment]
Added `/ASTRAL` refinement to TO-STRING:

https://github.com/metaeducation/ren-c/commit/57860742d3ffc9972ef5c244240c75cba34278e8

You can pass it a function that receives the integer value of the codepoint, and returns what string to substitute.  Or you can just use a string or character literal for all such codepoints.

**Comment by hostilefork** [comment]
Reopened due to hopefully being able to close it in the not-infinitely-far future.

![image](https://user-images.githubusercontent.com/20440/36060349-c6427394-0e15-11e8-94c0-fa3489cbaad3.png)

**Comment by hostilefork** [comment]
[...and...here we go! 😺](https://forum.rebol.info/t/realistically-migrating-rebol-to-utf8-everywhere/374/5?u=hostilefork)

    >> test-data: #{22646973706C61796E616D65223A224A6F6E20F09F98BA22} 
    == #{22646973706C61796E616D65223A224A6F6E20F09F98BA22}

    >> print as text! test-data
    "displayname":"Jon 😺"
