### ISSUE TITLE
test: copy/part tail [1] -1 fails on arm

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#283]
```
>> copy/part tail [1] -1
== []

>> copy/part tail [1] -2147483647
== []

>> copy/part tail [1] -2147483648
== []
```

(should have been [1] in all 3 cases)

**Comment by hostilefork** [comment]
I've added a /TEST refinement...

https://github.com/metaeducation/ren-c/commit/76e89ab30f2038925cffd01d16bc87d6b036e8db

So if you could try these with `copy/part/test` and let me know what they print, that would help.

Nothing fancy going on AFAICT in this "Partial1" routine...

**Comment by zsx** [comment]
I think this was caused by the fact that [call to Copy_Array_Core_Managed](https://github.com/metaeducation/ren-c/blob/master/src/core/t-block.c#L881) depends on the undefined behavior: [Partial1](https://github.com/metaeducation/ren-c/blob/master/src/core/t-block.c#L885) has to run before passing of [VAL_INDEX ](https://github.com/metaeducation/ren-c/blob/master/src/core/t-block.c#L883). Because there is no sequence points between argument evaluations, this order is not guaranteed.

On x86 where it gives correct result, `copy/part tail [1] -1` results in a call like:
`Copy_Array_Core_Managed (original=0x7ffff7ea7648, index=0, specifier=0x0, tail=2, extra=0, deep=FALSE, types=0)`
while on ARM, it's like:
`Copy_Array_Core_Managed (original=0x7fb7c66698, index=1, specifier=0x0, tail=2, extra=0, deep=FALSE, types=0)`

Notice different values for **index**.
