### ISSUE TITLE
Passing empty varargs!

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#298]
Don't know if its a bug:

        f: func [x [any-value! <...>]] [probe tail? x]
        g: func [x [any-value! <...>]] [probe tail? x f x]
        g

gives

        true
        false

**Comment by hostilefork** [comment]
This is related to what I mentioned in chat...

http://chat.stackoverflow.com/transcript/message/32741785#32741785

When I was originally formulating this, I was thinking that you could either include VARARGS! as one of the types explicitly or not.  If it was explicitly in the list that would mean something different than if it wasn't.  If you said you didn't take VARARGS! then it would chain, but if you did take VARARGS! then you would feed variadic varargs-es.

But I think I agree here that the _more likely_ intent with a variadic ANY-VALUE! parameter that gets passed a VARARGS! is to chain.  So this should be rethought.  As I say in the chat message, I need to figure out if the place to rethink it is at the mechanical MAKE FUNCTION! level or to leave it as it is and adjust FUNC/FUNCTION/PROC/PROCEDURE...

**Comment by hostilefork** [comment]
This turns out to be tricky.

TAIL? is not supposed to advance or evaluate the input for VARARGS!.  But if varargs act in a chained fashion when they are the product of evaluation... e.g. if **f: func [x [any-type! <...>]]** and **g: func [return: [varargs!]]**, then for TAIL? to be answerable in **f g** then it has to invoke G and see if it evaluates to a VARARGS! or not, and then ask _that_ varargs about its TAIL? status.  :-/

One option would be to remove the ability to query independently for TAIL?, and instead have TAKE coming back with a void be the way to see if you're at the end.  That makes the TAKE/TAIL? test one atomic operation...the evaluation and the answer happen at the same time, so more consistent.

What do you think?

**Comment by giuliolunati** [comment]
Not sure to understand.
Consider this:

f: func [x [integer! <...>]] [
   loop 2 [print tail? x take x]
   true
]
g: func [x [integer! <...>]] [f x]
do [f]
print "---"
do [g]
print "==="
do [f 1]
print "---"
do [g 1]

Note that the anomalous behavior is limited to empty case...

Il 09/set/2016 17:53, "Brian Dickens" notifications@github.com ha scritto:

**Comment by hostilefork** [comment]
@giuliolunati Yes...at first I was just saying that the chaining was "related".  When I looked closer it turned out that TAIL? detection is a special concern with chaining.  It is still related though.

If you chain, and the VARARGS! you are chaining is empty, and the source of the VARARGS! was an evaluation... then you have to evaluate to know the correct answer to TAIL?.  Yet evaluation is necessary to know you have a varargs (e.g. **f x** is taking a WORD!, but you intend to chain a VARARGS!, so you need to evaluate...)

So this is why I am wondering what the impact would be if there was only one operation, TAKE, which might return void.

**Comment by giuliolunati** [comment]
I agree with that proposal: no more `tail?`, check if `take` returns void.

Il 10/set/2016 08:34, "Brian Dickens" notifications@github.com ha scritto:

**Comment by hostilefork** [comment]
Sigh... checking for void won't work, because variadics are allowed to have void evaluations that don't end the sequence.  For instance, **|>** is a variadic operator which evaluates to the expression on its immediate right:

```
>> print "first" |> 10 + 20 | print "second" | "ignored value"
first
second
== 30
```

It's a variadic "infix" (enfixed) operator.  So its left hand side is `print "first"`, then it keeps taking expressions on the right.  Those expressions can be void and it doesn't count as an end of the variadic input.  Being able to do that is important... more important than chaining.  :-(

The answer may be that the way to chain is to use an APPLY, but otherwise you will just get a VARARGS! value (not chained, e.g. your TAKE will give back another VARARGS!):

```
f: func [x [any-value! <...>]] [probe tail? x]
g: func [x [any-value! <...>]] [probe tail? x | apply :f [x: x]]
g
```

So that would give `true/true`.  The reason is that you've clearly pointed out that there is a single value being passed to that argument--which is the VARARGS! to chain.  You can only chain one this way, though maybe some operation that deliberately ties together multiple VARARGS! into one could be made.  How is that?

**Comment by hostilefork** [comment]
In the grand scheme of things, there's no way to make `take` and `tail?` work consistently with this chaining...and it's critical that they do work consistently.  More critical than the chaining feature.  _(Which was already on thin ice because VARARGS! are legitimate values...so what if you don't want them to chain?)_

In light of that, I'm pulling back chaining to something that has to be done explicitly with APPLY...which should cover most of the common cases:

https://github.com/metaeducation/ren-c/commit/9fc5dd3f033b1803fd530d63bffc8558cea4d857

Thanks for noticing this!!!
