### ISSUE TITLE
PANIC VALUE called from f-series.c:204 

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#300]
Found this error:

        END marker or garbage/trash in VAL_TYPE()
        Pointer found in freed tail capacity of series
        PANIC VALUE called from ../src/core/f-series.c:2
        04
        Kind=0
        Containing series for value pointer found, panic
ing it:

Not simple repro found, sorry...

**Comment by hostilefork** [comment]
Any repro is helpful ... doesn't matter if it's simple!

**Comment by giuliolunati** [comment]
Not-so-simple repro:

Install
https://github.com/giuliolunati/rebol-lib/blob/master/usr/lib/r3/recode.reb
as module

then do
https://github.com/giuliolunati/rebol-lib/blob/master/usr/share/scripts/test-recode.reb

Il 23/set/2016 07:07, "Brian Dickens" notifications@github.com ha scritto:

**Comment by hostilefork** [comment]
Ok, that repros for me...should be enough to find it!

**Comment by hostilefork** [comment]
This is one of those we haven't seen in a while...which is really just not testing for END before a comparison.

_(Once upon a time the END! and REB_END were casually-treated types, but for safety you can no longer VAL_TYPE() them...so comparing against an END marker is fundamentally different.)_  QUOTE in parse just hadn't been bulletproofed against it, so if you said `parse [] [quote 2]` it crashes instead of failing the match.

Fixed in https://github.com/metaeducation/ren-c/commit/5738a5fc84dcae4dd15a9fd3faab87911e3b90c3
