### ISSUE TITLE
poke in decimal vector fails

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#319]
`a: make vector! [decimal! 32 3]
poke a 1 1.0
print a/1`

prints

`4.6071824188000174e18`

**Comment by giuliolunati** [comment]
Ok, probably a 32-bit issue: needs INIT_DECIMAL_BITS when setting decimal value See https://github.com/metaeducation/ren-c/pull/320

**Comment by hostilefork** [comment]
I actually introduced this problem by abbreviating a header reset and init bits by a simple SET_DECIMAL, which was incorrect for this.  :-/

To keep it from happening again, I made the C++ build ensure you don't pass integers to SET_DECIMAL.  If you try to do so, rather than implicitly converting it to a decimal it will resolve to an undefined overload.

Integrated as:

https://github.com/metaeducation/ren-c/commit/325720d5077ca17b942e291dd4de052734574974
