### ISSUE TITLE
in make-make.r: macro++ must be procedure

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#334]
in commit https://github.com/metaeducation/ren-c/commit/2db8e04db7e12bf4ec87de7232de74ca6b9a7169 macro+ was changed to proc, but this requires same for macro++

**Comment by hostilefork** [comment]
Ah yes, sorry.  :-/  Added here:

https://github.com/metaeducation/ren-c/commit/9150008bfc046a71b696c430c240cfd5972aec05#diff-792db244e01a94bc3c2de50fc2b369afR338

I'm trying to simplify the build process, and how extensions work...and hopefully we can get the Travis updated to use a new build process as well as the CMake.  And one thing we will want to add there is something to guarantee it can run the whole build process with the bootstrapped executable.

If you want to see it happen sooner rather than later and learn some Travis, feel free to chip in... I haven't really messed with that much since earl set it up.
