### ISSUE TITLE
make-zlib.r failed

### ISSUE THREAD

**Issue by zsx** [metaeducation/ren-c#352]
The reason that I need this to work is that I need to apply these patches such that it will build for Android with DEBUG:
```
--- a/src/core/u-zlib.c
+++ b/src/core/u-zlib.c
@@ -2441,10 +2441,10 @@ local uInt longest_match(
 /* ===========================================================================
  * Check that the match at match_start is indeed a match.
  */
-local void check_match(s, start, match, length)
+local void check_match(
     deflate_state *s,
     IPos start, IPos match,
-    int length
+    int length)
 {
     /* check that the match is indeed a match */
     if (zmemcmp(s->window + match,
diff --git a/src/include/sys-zlib.h b/src/include/sys-zlib.h
index f7f558c..85080d5 100644
--- a/src/include/sys-zlib.h
+++ b/src/include/sys-zlib.h
@@ -39,6 +39,10 @@
 // AUTO-GENERATED FILE - Do not modify. (From: make-zlib.r)
 //

+#ifndef NDEBUG
+#include <stdio.h>
+#endif
+
 #define NO_DUMMY_DECL 1
 #define Z_PREFIX 1
```

The changes to u-zlib.c are to convert `check_match` from old style to new style.

However, I just found that make-zlib.r is out-of date, with ren-c:
```
** Script error: incompatible or duplicate refinement: lines
** Where: function! read for-each do either either either --anonymous--
** Near: ... make port! [
    [self: spec scheme actor awake state da...
```

with R3-alpha, it initially failed with:
```
$ ../r3-build/win64/r3-make.exe src/tools/make-zlib.r
** Access error: protocol error: "Redirect to other host - requires custom handling"
```

After fixing the URL, it failed with:
```
$ ../r3-build/win64/r3-make.exe src/tools/make-zlib.r
** User error: {Not all headers inlined by make-zlib: [%trees.h %inffixed.h %crc32.h]}
```

**Comment by hostilefork** [comment]
As it turns out, R3-Alpha didn't support read/lines on URL!.  The error in Ren-C is doing a favor by pointing out that the refinement isn't supported vs just ignoring it (!).  (The port code really had a lot of unanswered questions about how such things were supposed to work.)

But I went and moved /STRING and /LINES implementation into the port dispatch code so it will work for any port:

https://github.com/metaeducation/ren-c/commit/9b5e025d4eaf442396d881c4f01decd40a267a46

As for your patch...make-zlib is something I did to try and address a bug in the snapshot of zlib Rebol was using.  It was done right around when R3-Alpha was open sourced.  It predated the C++ build.  So despite what the file says, the conversion from old-style to new style was done by hand--%make-zlib.r doesn't do it.  :-/  It should be done automatically, of course.

Getting a fresh zlib with any patches isn't a bad idea, and having make-zlib.r do that work would be nice...but it's not the highest priority (and it's something another person who isn't me could do).  So why don't you just make the changes you need for now, and cross the auto conversion bridge when we come to it...

**Comment by zsx** [comment]
Fixed by https://github.com/metaeducation/ren-c/commit/a20b4f3f02b5960d79355e2a94256ff678177a5a
