### ISSUE TITLE
Pick map -> assertion

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#371]
`pick make map! [1 1] 1`

../src/include/sys-array.h:335: VAL_ARRAY: assertion "ANY_ARRAY(v)" failed

**Comment by hostilefork** [comment]
Hmmm...whose fault is this?  ;-)

https://github.com/metaeducation/ren-c/commit/70f0f3585eaaf8d9f714ec3d394f967f3a8880e8

The idea behind maps in R3-Alpha was that they aren't supposed to be positionally accessed--the underlying block is an implementation detail.  This is different from Rebol2's HASH! data type, which was an accelerated index on top of what was fundamentally a block.

http://www.rebol.net/cgi-bin/r3blog.r?view=0014

If you allow indexing into the map block directly, then the user can wind up seeing random implementation details...deleted keys, etc.

The argument Ladislav gives for why map was needed instead of hash was:

> I think, that INDEX? is O(1) on hashes, while FIND is "almost O(1)". CHANGE/ONLY is O(1) too as well as SKIP. As opposed to these, both INSERT and REMOVE are "slow" (slower than for blocks). (...) sorry, CHANGE/ONLY cannot be O(1), my error.

In any case: my proposal for the meaning of PICK is that it be the "path step operator".  If you write **pick a/b/c** that would be the same as **(pick (pick (pick a) quote b) quote c)**.  It might even allow equivalence with **pick a 'b/c**.  (I'm considering that **pick :append 'dup/only** might be the mechanism for getting a "refined" version of a function, where it has refinements picked in a specific order without specializing the arguments to the refinements.)

With that rule, since in the above case, you want **m: make map! [1 x] | m/1** to be x, **pick m 1** would also be x.

**Comment by giuliolunati** [comment]
I agree with that, so we can revert pick to select.

I love also the pick=/ idea.
(And would fantastic if the user could customize path/separator behaviour!)


Il 20/gen/2017 18:05, "Brian Dickens" <notifications@github.com> ha scritto:

**Comment by hostilefork** [comment]
Resolved by unification of PICKing and PATHing...

    >> m: make map! [1 x]

    >> m/1
    == x

    >> pick m 1
    == x
