### ISSUE TITLE
recursion with variadic function

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#372]
`f : func [:look [block! <...>]] [
 apply 'f [look: make varargs! take look]
 ] f [x]`

SER_AT_RAW asked 1 on width=255
Kind=38

`f: func [:look [block! <...>]] [
   apply 'f [look: make varargs! take look]
 ]
 g: func [x] [f [x]]  g 1`

Relative item used with SPECIFIED
Kind=4

`f: func [:look [block! <...>]] [
   first look
   apply 'f [look: make varargs! take look]
 ]
 g: func [x] [f [x]]  g 1`

sys-rebval.h:908: KNOWN: assertion "IS_SPECIFIC(value)" failed

**Comment by hostilefork** [comment]
All three of these examples should give an error, which would say:

> ** Script error: f does not allow word! for its look argument

That's because your first recursion's take here gets a block (**[x]**), but your second recursion will get a word (**x**).  A type error should being reported on the second recursion of the TAKE due to not receiving the parameter's BLOCK! type.

But interestingly, each one of them doesn't do this for a different reason.  :-)

   f: func [:look [block! <...>]] [ apply 'f [look: make varargs! take look] ] f [x]

Here there's a bug in the error that gets made, which tries to take its label from the feeding frame (anonymous, since the feed is make varargs!) instead of the parameter's frame.

    f: func [:look [block! <...>]] [ apply 'f [look: make varargs! take look] ] g: func [x] [f [x]] g 1

This doesn't get to the point of the above error...it's first affected by a bug which ignored that the array wasn't copied and hence may be relative to its original source.

   f: func [:look [block! <...>]] [ first look apply 'f [look: make varargs! take look] ] g: func [x] [f [x]] g 1

Affected by a similar bug as the previous...

All 3 should be addressed here:

https://github.com/metaeducation/ren-c/commit/e740772a10c3534faf5364e47f68e603f1bcd5f7

Thanks for the continued testing, and please feel free to add more varargs tests to the %tests/ as you come up with them!  Recursive examples are good, but would need a few that don't error (though good if some do).

**Comment by giuliolunati** [comment]
Oh, thanks!
About adding tests: better PR to you or directly add? And, tests must print anything?

**Comment by hostilefork** [comment]
Tests aren't really supposed to print anything...just return true or false.

A PR to the repository is the best way to get things reviewed...doesn't have to be to me in particular, though I'll be the one who reads it.  :-)

I split out the varargs tests into their own file since the automated split didn't do that.  I also split the little single sad tests for things like CHAIN and ADAPT into their own files too.  If you take that as a challenge and want to add more, that would be great!  :-)

https://github.com/metaeducation/ren-c/commit/7156752503f2986268073fe4a70e66e54adb3f27
