### ISSUE TITLE
enfix in object => RE_MISC error

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#380]
`o: make object! [+: _ ] o/+: enfix :add`
=> ** Internal error: RE_MISC error ...

**Comment by giuliolunati** [comment]
Also
`make object! [set/lookback 'a 1]`
fails.

**Comment by hostilefork** [comment]
Hm, I must have told you about why this doesn't work in chat.  Didn't have a solution to the general problems until, maybe, today?

https://forum.rebol.info/t/enfix-dispatch-via-path-a-solution/254

What do you think?

**Comment by hostilefork** [comment]
While enfixed *dispatch* via PATH! is not available yet, this commit lets you do enfixing via PATH!

https://github.com/metaeducation/ren-c/commit/fa96060342ee320d0e25019545a57ff1a7b523cf

So your first example should work: `o: make object! [a: _] o/: enfix :add`.  However, note that you will only see it dispatch as enfix through a word, such as with `do in o [10 a 20]`.

Again, your second example can't work because there's no `a` in the object to set.  But you should be able to do either:

     make object! [a: _ | set/enfix 'a :add]

...or...

    make object! [a: enfix :add]

Enfixed path dispatch is a hope for the future, but not likely to happen too soon!
