### ISSUE TITLE
Wrong time reported

### ISSUE THREAD

**Issue by codebybrett** [metaeducation/ren-c#397]
For a time of 5:17pm, NOW reports the time with a 1 hour difference:

    >> now
    == 27-Feb-2017/18:17:41+11:00

I built using Ubuntu 16.04 (virtualbox on windows). Builds with these OS_IDs exhibit the problem:

* 0.4.2
* 0.4.3
* 0.4.4
* 0.4.40

Building on windows for windows did not show this problem.

Running the tests for OS_ID=0.4.2 shows these two failures:

    [0.6 == round/half-down/to 0.55001 0.1] "failed"
    [-0.6 == round/half-down/to -0.55001 0.1] "failed"

**Comment by johnk-** [comment]
Seems to be working for me.

Tested ren-c built on 30-Aug-2016
```
>> now
== 28-Feb-2017/14:13:40+11:00

>> quit
$ date
Tue Feb 28 14:13:44 AEDT 2017
```

**Comment by hostilefork** [comment]
Think I found the problem, if people can make sure it's still giving them the answer they expect for `now/utc` (compare with [https://time.is/UTC](https://time.is/UTC)) and `now` (compare with your computer's display clock)...

https://github.com/metaeducation/ren-c/commit/bd55c877ffed5f247944c6ebb3f368b712af667a

Note that because of how things work, your apparent "time zone" (the GMT-7 or GMT-8 or whatever) will be different dependent on whether you're in daylight savings time or not.  Because Rebol stores times as the UTC value plus this offset as the zone, the zone has to change when daylight savings time changes, or the local time will be an hour off.

**Comment by draegtun** [comment]
I can confirm exact same problem running Ubuntu 16.04.2 (32-bit) on VMWare.

The fix above from @hostilefork  has now correctly the problem.

@codebybrett - The rounding issue has already been logged #547  So looks like this confirms its a virtualisation issue!   Is your Ubuntu 16.04 32 or 64 bit?

**Comment by codebybrett** [comment]
@hostilefork the fix resolves the time issue:

    >> ; Time now.
    >> now/utc     
    == 22-Jun-2017/21:35:56
    >> now         
    == 23-Jun-2017/7:35:59+10:00
    >> ; Change time to earlier daylight saving period.
    >> now/utc                                  
    == 22-Jan-2017/21:36:23
    >> now                                      
    == 23-Jan-2017/8:36:26+11:00
