### ISSUE TITLE
assert failure by parse

### ISSUE THREAD

**Issue by zsx** [metaeducation/ren-c#406]
```
>> parse [1][do [quote 1]]
src/core/u-parse.c:161: REBOOL Subparse_Throws(REBOOL*, Reb_Specific_Value*, Reb_Value*, REBSPC*, const Reb_Value*, REBSPC*, REBCNT): Assertion `IS_END(out)' failed.
Aborted (core dumped)
```

**Comment by hostilefork** [comment]
So I addressed that particular bug you're getting an assert about.  But the bigger issue is that the implementation of Do_Eval_Subrule is pretty crappy.  It breaks the flow of the parsing process because it can't quite reuse the main loop--it is effectively "injecting" a parse rule into the block that isn't actually there.  If it tried to just switch the parse rule over to the evaluation product and continue the loop, then the loop would try and increment the pointer of the faked in rule...not resume where it left off at the "real rules".

But good news regarding foresight from the Fork... :-)

Since PARSE is frame-based now, it iterates its rules using the same FETCH_NEXT logic as Do_Core uses for code it evaluates.  That means the mechanic used by EVAL to cheat a virtual value into the feed can be used here.  All Do_Eval_Subrule has to do is put the evaluated rule into the frame cell, splice the evaluation product into the source feed, and keep going.  Since everything is written to use FETCH_NEXT it should work, and work more generically (in loops and such).

So if we're lucky, Do_Eval_Subrule goes away.  For that matter, QUOTE should be using this same technique too, to splice in a virtual rule.

**Comment by hostilefork** [comment]
On another note, are you sure what you are saying would do what you want?

Shouldn't `parse [1] [do [quote 1]]` behave the same as `parse [1] [1]`?  This would not match, because integers are used to specify repetition counts.

Currently, if you want to match a literal, yet evaluate the thing you are literally matching, you use `parse [2] [quote (1 + 1)]`.  I've complained that I don't like this, because I think `parse [(1 + 1)] [quote (1 + 1)]` is what should match if being coherent with how QUOTE is applied in the regular evaluator.

**Comment by hostilefork** [comment]
I'm remembering now that I totally don't understand what DO in R3-Alpha was for.  It does code on the *input* series, and then applies the rule to the result.  :-/

So QUOTE (...) is the behavior I'm thinking of.

**Comment by zsx** [comment]
I don't know what the code does. :-/ All I wanted to do was to come up with some code that could test [the fix](https://github.com/metaeducation/ren-c/commit/35f4e0fa843c4c6e9b6d95b114ea16e2e2fe4c93), and then I came across this assert failure, and figured that whatever the code does, it shouldn't crash.

**Comment by hostilefork** [comment]
Do_Eval_Rule has always been scary, but now hopefully I'll at least remember what it does.  :-/

PARSE needs a bit of an overhaul in order to actually support a feature like DO rigorously:

https://github.com/rebol/rebol-issues/issues/2270

But I simplified the code quite a bit, so it doesn't even make a new frame.  Also I added a lot of comments, and a couple of tests:

https://github.com/metaeducation/ren-c/commit/8b9631e5ffb1f16af67a71af7b3a70956f586d7d#diff-a583c2c8c40f905c828831af14c3fd92L1120

I've really not spent time trying to think about how to redesign PARSE.  Everything has been kind of a matter of maintenance, keeping it in working order as things changed, and twisting it around so it used Reb_Frame.  But I feel like it's at least becoming pretty clear how it works (or is trying to work).
