### ISSUE TITLE
Assert failure on MacOS

### ISSUE THREAD

**Issue by zsx** [metaeducation/ren-c#413]
Haven't found a simple test case yet, but It failed to run tools/make-natives.r on MacOS, with the assert error:
```
IS_END() called on garbage
Rebol Internal Error
```
The assert happened at [here](https://github.com/metaeducation/ren-c/blob/master/src/core/c-error.c#L296), and the reason it's failing is because the D_OUT is invalidated by [SINK](https://github.com/metaeducation/ren-c/blob/master/src/include/sys-series.h#L633) on [this](https://github.com/metaeducation/ren-c/blob/master/src/core/l-scan.c#L2104) line, and Scan_Array is erroring out because it [detects a syntax error](https://github.com/metaeducation/ren-c/blob/master/src/core/l-scan.c#L1882).

Breaking it into two statements fixed the issue:
```
diff --git a/src/core/l-scan.c b/src/core/l-scan.c
index ca7b91a..39b44cd 100755
--- a/src/core/l-scan.c
+++ b/src/core/l-scan.c
@@ -2101,7 +2101,8 @@ REBNATIVE(transcode)
     // If the source data bytes are "1" then it will be the block [1]
     // if the source data is "[1]" then it will be the block [[1]]
 
-    Init_Block(D_OUT, Scan_Array(&scan_state, 0));
+    REBARR *array = Scan_Array(&scan_state, 0);
+    Init_Block(D_OUT, array);
 
     // Add a value to the tail of the result, representing the input
     // with position advanced past the content consumed by the scan.
```

The reason why we didn't see this on Linux/Window is probably the difference in sequence of parameter evaluation, i.e. Scan_Array is called before SINK?

But I think a better fix is to remove such traps, like this:
```
diff --git a/src/include/sys-series.h b/src/include/sys-series.h
index cb1a79d..c1e702d 100644
--- a/src/include/sys-series.h
+++ b/src/include/sys-series.h
@@ -629,8 +629,12 @@ inline static REBYTE *VAL_RAW_DATA_AT(const RELVAL *v) {
     return SER_AT_RAW(SER_WIDE(VAL_SERIES(v)), VAL_SERIES(v), VAL_INDEX(v));
 }
 
-#define Init_Any_Series_At(v,t,s,i) \
-    Init_Any_Series_At_Core(SINK(v), (t), (s), (i), SPECIFIED)
+inline static void Init_Any_Series_At(RELVAL *out,
+    enum Reb_Kind type,
+    REBSER *series,
+    REBCNT index) {
+    Init_Any_Series_At_Core(SINK(out), type, series, index, SPECIFIED);
+}
 
 #define Init_Any_Series(v,t,s) \
     Init_Any_Series_At((v), (t), (s), 0)
```

**Comment by hostilefork** [comment]
I see the problem, and I do not feel the macro is at fault.  The problem is that trash is being used in a slot visible to the GC over a duration where the GC will run.

I was actually thinking that trash cells (e.g. NODE_FLAG_CELL is set, but not NODE_FLAG_VALID) should probably be the standard for how output slots are formatted when natives run.

The reason that END was used for this purpose before was because there was no guaranteed formatting, and the GC would crash on arbitrary bits.  Now that DECLARE_LOCAL exists, all cells will have some formatting.

In order for the debug build to distinguish between unwritten cell trash and something coming from sink, there could be a difference in the type bits... e.g. REB_MAX_VOID is written in SINK-style trash (garbage promised to be overwritten) vs. REB_0 for a cell that is merely not written to, like the END was used.

**Comment by zsx** [comment]
OK. Sounds like plan.

**Comment by zsx** [comment]
[Here] is the first attempt to implement what you suggested. Haven't changed the comments yet, but I want to know how you think about it first.

**Comment by hostilefork** [comment]
I appreciate you looking at this, but I'm not totally sure exactly what I want to do yet.  This is tied up with some of the new things I'm trying.  I'm still thinking about it.  :-/

**Comment by hostilefork** [comment]
I think what I want to do, as a short term fix, is just have GC tolerate trash in the out slot.  It will check for NODE_FLAG_CELL but not worry about NODE_FLAG_VALID.

When I say it's more complex than this, it's because of my local changes, which are painting a different picture of what the future of frames will look like.

**Comment by hostilefork** [comment]
Okay, after a little change it's good enough to build the OS X bootstrap now.  That's cool.  And really nice to have a clang build in there also.

**Comment by hostilefork** [comment]
> Here is the first attempt to implement what you suggested. Haven't changed the comments yet, but I want to know how you think about it first.

Thanks again, but I think my idea was a bad one (which I started worrying about a bit when I started thinking about it more).  We get a lot of mileage out of trash cells being trash, and the GC tolerating them is not good.

So I came up with a better/simpler answer that I think makes the best sense, and keeps all the checks going:

https://github.com/metaeducation/ren-c/commit/0f831cb728a5beda7e63b798ce1311ff0b37c8bb

This way, the END will be turned into an unreadable blank.  That will prevent it from being used to signal the native didn't write it's output after that, but that's exactly what you want.  Enough code will barf on an unreadable blank that it's basically as good as trash.
