### ISSUE TITLE
Assertion failed in Make_Error_Managed_Core

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#424]
Running r3-017a1343-debug (Android5 0.13.2):

    f: func [x t:][
      either 1 = x/1 [
        f x/2
      ][
        forall x [f x/1]
      ]
    ]

    f [[1 [0]]]

../src/core/c-error.c:979: Make_Error_Managed_Core: assertion "FALSE" failed
Aborted

**Comment by hostilefork** [comment]
Shorter repro:

     x: 0
     print x/1

If you add a probe you'll see you are path selecting out of an integer.

The assertion is due to the lack of type-checking on C variadics; which is something that the C++ build could make up for, but just hasn't been done yet.  I looked through all the error variadic generators and found another case as well:

https://github.com/metaeducation/ren-c/commits/master
