### ISSUE TITLE
Parse and remove

### ISSUE THREAD

**Issue by no-e-in** [metaeducation/ren-c#427]
In  Ren-c (Version:   2.102.0.3.40 | Platform:  Windows win32-x64 | Build:  22-Mar-2017/5:49:03):

```
>> parse  "a<bbb>" [ some [remove ["<" thru ">"] | skip]]
== true

>> parse  "<bbb>a" [ some [remove ["<" thru ">"] | skip]]
== false
```

**Comment by hostilefork** [comment]
This behavior exists in R3-Alpha, and was apparently purposeful, summarized in rebol issues 1401:

https://github.com/rebol/rebol-issues/issues/1401

So that would mean the problem is that "some" requires a positional advancement.  You were at index 1, then you removed <bbb> and were still at index 1.  The first example works because you removed at the tail, so you wound up at the end of the parse.

If you use WHILE you get the result you are expecting:

    >> parse  "<bbb>a" [ while [remove ["<" thru ">"] | skip]]
    == true

Red doesn't make this distinction.  If you want to weigh in on it, the issue above would be the place...or chat, as Ren-C issues are for things specific to Ren-C.
