### ISSUE TITLE
help => doesn't work

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#432]
>> help =>
{

and no help is returned.

**Comment by hostilefork** [comment]
Bug was due to a failure of the REPL to correctly interpret an "invalid word" error as not being the kind of error that entering more lines of text might help turn the input into being loadable.  So it fetched another line.

Resolved in soon-to-be-merged commit, Travis is being slow:

https://github.com/hostilefork/rebol/commit/2ceaaf5d48eb0ea76d3d6a959c6c089364a65a38

*(=> should be a valid word, but so should many other things, and that's its own issue... where a solution that allows ==> and =>>, etc, should be studied)*
