### ISSUE TITLE
help on all lib words errors

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#434]
**    Version:   2.102.0.3.40                                           **
**    Platform:  Windows win32-x64                                      **
**    Build:     23-Mar-2017/17:13:58                                   **

for-each [key val] lib [help :val]

make typeset! [path! set-path! get-path! lit-path! group! block!] is a typeset
true is a logic
false is a logic
** Script error: type-name does not allow function! for its value argument
** Where: delimit either either print if help for-each
** Near: "is" type-name :word ??

**Comment by hostilefork** [comment]
Two problems here.

One, it's legal for object values to be void, to indicate the variable is unset.  In which case :val can be void here and HELP doesn't take voids.

But more "profoundly", HELP has trouble if you try to use it generically, since it treats WORD! specially due to quoting.  You can't say **for-each x [1 12-Dec-2012 foo] [help x]** and have it tell you "1 is an INTEGER!, 12-Dec-2012 is a DATE, and FOO is a WORD!" because it looks up foo.

So either HELP needs an /ONLY refinement or some way of telling you want it to tell you "hey that's a WORD!", or there needs to be a HELP-CORE which implements the fundamentals of HELP, likely giving you structured information...leaving it to HELP to do the console-friendly behavior and quoting of arguments.

Anyway, until that day, you have to ask for help on the key.  The keys are bound to the object they live in, and since HELP soft-quotes its argument you can do

    for-each [key val] lib [help :key]

There were a couple reasons that wasn't working, patched here:

https://github.com/metaeducation/ren-c/commit/92cbbcf12617526243c5a6d7114a9c2744e65b36
