### ISSUE TITLE
Problem with trace

### ISSUE THREAD

**Issue by no-e-in** [metaeducation/ren-c#436]
In ren-c on win64:
```
>> trace on
    <-- trace == &void
    --> --anonymous--
         1: source:
         2: copy : function! [value /part limit /deep /types kinds]
             3: ""
        --> copy
        <-- copy == ""
         4: code:
         5: copy : function! [value /part limit /deep /types kinds]
             6: []
        --> copy
        <-- copy == []
     ......................................   
```

**Comment by hostilefork** [comment]
Sigh, one of the consequences of a userspace console.  The REPL itself is getting traced!  Not what most people want.  While the debugger influences were isolated by having the REPL return the code to be executed vs. executing itself, that doesn't cover TRACE, because it's just a couple of global flags.

Very basic way of dealing with the problem, for now:

https://github.com/metaeducation/ren-c/commit/4fdd85411c5b17afebd886713188846fae954e15
