### ISSUE TITLE
Assertion failed in sys-do.h:366

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#460]
f: func [
      args [any-value! <opt> <...>]
      ][
      take args
    ]
    x: make varargs! [_]
    apply :f [args: x]

../src/include/sys-do.h:366: assertion "parent->eval_type == REB_FUNCTION || parent->eval_type == REB_SET_WORD || parent->eval_type == REB_SET_PATH" failed
Aborted

**Comment by hostilefork** [comment]
This turned out to be an informative assert, because it was showing a way in which doing a vararg TAKE was being inefficient.  I knew varargs were being a little excessive with making a frame when it didn't need to (e.g. a quote, applied on a block).  But this assert was pointing out it was creating *two* frames per TAKE.

Since there was no particularly easy answer, I went ahead and tuned up variadics in general...they've needed a review.  This should fix some bugs too (it wasn't type checking all the time).

https://github.com/metaeducation/ren-c/commit/3a0d8430152551baa1b56ad6d2d57362969f1de2

I've added this to the tests, but *please, please* feel free to just try random things and see if you can generate any problems!  I should be better about writing tests, but there's quite a lot to do, so any help is much appreciated.

https://github.com/metaeducation/ren-c/blob/master/tests/datatypes/varargs.test.reb
