### ISSUE TITLE
Assertion when using first on a map!

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#461]
```
>> m: make map! [a: 1]
== make map! [
    a: 1
]

>> first m
r3: ../src/include/sys-array.h:356: VAL_ARRAY: Assertion `ANY_ARRAY(v)' failed.
fish: “r3” terminated by signal SIGABRT (Abort)
```

**Comment by hostilefork** [comment]
This shouldn't be legal, and never should have been...but it was in R3-Alpha, presumably because the HASH!/MAP! code was originally sort of the same:

https://github.com/rebol/rebol/blob/25033f897b2bd466068d7663563cd3ff64740b94/src/core/t-map.c#L496

Turned into an error!

https://github.com/metaeducation/ren-c/commit/9232b3ba77bc1215911564d428c3302545703d9d

Accelerated lookup on blocks doesn't seem like a bad thing, but making it a different type is a bad thing.  So you might say **hint block [index: hash]** or something.

**Comment by IngoHohmann** [comment]
I didn't want to imply that it should, just that I noticed the assert there, and that could be something you might want to know about.

**Comment by hostilefork** [comment]
Interestingly, by the revised rules of the system, this "works" now, in the sense that it has meaning.

    >> m: make map! [1 x 10 y]

    >> m/1                     
    == x

    >> pick m 1
    == x

    >> first m
    == x

    >> tenth m
    == y

These operations are defined in terms of each other.  **pick a b** is defined as **a/(b)**, and **first a** is the specialization **pick a 1**.

Is this good?  Is this bad?  At least there's a logic to it...

**Comment by giuliolunati** [comment]
Bad, because suggests an order.

**Comment by hostilefork** [comment]
@giuiliolunati Well, you might use a map as a "sparse block" in which case in your mind you think of it as having an order.  It could be a usage model that someone has where the domain is all integers, and the range is all values, and they are using it instead of a block because they think padding with blanks would take too much space.

So the meaning could be in the eye of the beholder.

**Comment by giuliolunati** [comment]
Oh! Right, absolutely.

**Comment by hostilefork** [comment]
@giuliolunati Still I suppose we can ask if this suggests that **pick map 1** and **map/1** is a mistake vs. forcing you to use SELECT on maps.  Because in a BLOCK! you have the same problem... you could mean SELECT or you could mean use the order.  And in that case, the order wins.

I don't think, though, that this is the fault of **pick a b** being the same as **a/(b)**, or **first a** being **pick a 1**.  If we always want order to win out, then map/1 should be an error and you need to use select for that...

**Comment by giuliolunati** [comment]
I prefer current behaviour: m/1 = select m 1

**Comment by asampal** [comment]
Initially, I was with you, @hostilefork, on the "sense" behind having ordinal functions applicable to maps, but on second thought I think the meaning behind these is pretty ingrained with people. Maybe there could be something like a "th" ;-) operator that essentially does `select m key` with the corresponding key, e.g. `"city"th m`. Only half joking...
