### ISSUE TITLE
r3 crashes under (Ubuntu) Linux 

### ISSUE THREAD

**Issue by xqlab** [metaeducation/ren-c#499]
./r3-012c4ae 
Script: User Preferences Version: Date: 3-Nov-2015/10:23:49+1:00
Rebol Internal Error:

valid series

and with debug version it shows
./r3-012c4ae-debug-cpp
```    ./r3-012c4ae-debug-cpp 
Script: User Preferences Version: Date: 3-Nov-2015/10:23:49+1:00
C Source File ../src/os/host-main.c, Line 865
Series VARLIST detected.
...and that VARLIST is of an ERROR!...
** PROBE() tick 270659 ../src/core/d-crash.c:126
make error! [
    [self: code type id message near where file line]
    [
        code: _
        type: _
        id: _
        message: "Error in user.r script"
        near: [...
            fail "Error in user.r script" ??
        ]
        where: [fail --anonymous-- trap if if --anonymous--]
        file: _
        line: _
    ]
]

managed series was likely created during evaluator tick: 270654
series guard didn't trigger ASAN/Valgrind trap
:
either not a REBSER, or you're not running ASAN/Valgrind
```

There is no user.r file in the same directory, as the former R3 files did not need one

**Comment by gchiu** [comment]
What's in your %user.r script that might be causing this issue?

**Comment by hostilefork** [comment]
@draegtun - the startup code needs to be responsible for delivering its own errors, printing the messages etc.  It cannot fail out because there's no way for the C code to know how far it got, or if it's ready to run a REPL, or what.  It's where the buck stops, basically.  So rather than fail here, it has to figure out how it wishes to notify the user:

https://github.com/metaeducation/ren-c/blob/012c4ae6c9ec2187cbad777fe58779996f6673fc/src/os/host-start.r#L550

**Comment by hostilefork** [comment]
@xqlab As you can see from the above, the console is usermode now (with more being pushed out, hopefully the history will be a Rebol structure, etc.)

If you try running the user.r directly you should be able to get the precise error.

**Comment by xqlab** [comment]
I have no user.r file in the same directory, just a user,r file under my $HOME/ directory.  There is $HOME/.rebol/user.r.

**Comment by gchiu** [comment]
Yes, it's now found in $HOME/.  Check out system/options/bin .. if there's a %user.r script there it will run it. 

But we are going to rename the file to %user.reb so the problem will go away.

**Comment by gchiu** [comment]
Ok, all references to user.r and rebol.r now changed to *.reb
Travis now running.

**Comment by xqlab** [comment]
I will check with the new version and close it.

**Comment by hostilefork** [comment]
The crash is still at issue... errors should be reported gracefully.  I'll let @draegtun decide how (or if) an error goes through a skin, or if it stops the process, etc.

**Comment by draegtun** [comment]
I'll make the following changes:

* prints the error message if finds in `%user.r`

* return error code 1 instead of `fail`   NB. @hostilefork - shout if I need to use different error code!

So above should stop gracefully when `%user.r` throws an evaluation error.

And I'll do the same for `%rebol.r`.    As it stands no changes are required for `%console-skin.reb` (already traps and reports gracefully).

NB. Will close this once PR for above is in place & proven.

**Comment by hostilefork** [comment]
@draegtun We could perhaps have FAIL be a local function to the startup, which actually does something like:

     fail: func [reason <with> return] [
         print ["Startup encountered an error!"]
         print reason
         return 1
     ]

That would only really apply to fails that were directly issued from the startup code.  The name overloading might cause more confusion than it resolves.  But, just mentioning it...

**Comment by draegtun** [comment]
Like it!   

Going to call it `die` to avoid any confusion.  Also adding little extra glitter :)

    die: func [reason /error e <with> return] [
        print "Startup encountered an error!"
        print ["**" reason]
        if error [
            print either o/verbose [e] ["!! use --verbose for more detail"]   
        ]   
        return 1
    ]   

Then in `host-start` can do `die "error msg"`, or also send on error object, `die/error "error msg" error-object` which can be seen if `--verbose` switch is given at command-line

**Comment by draegtun** [comment]
@xqlab - Let me know if above PR fixes your problem.

**Comment by draegtun** [comment]
@xqlab 

Hopefully this or a bug-squash in #502 have fixed your issue.

So closing this but please re-open if problem persists.
