### ISSUE TITLE
can't find r3.exe when running tests

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#500]
C:\Users\Graham\rebol3\ren-c\tests>..\..\r3 run-recover.r
Can't check for embedded code in Rebol path: /C/Users/Graham/rebol3/r3
** Access Error: cannot open: %/C/Users/Graham/rebol3/r3 reason: -3
** Where: read-binary case do-core-tests do catch either either --anonymous-- do trap either --anonymous--
** Near: checksum/method read-binary system/options/boot ?? 'sha1
** File: ../src/core/p-file.c
** Line: 144

Commit f14b5a3

Goes away if I use C:\Users\Graham\rebol3\ren-c\tests>..\..\r3.exe run-recover.r

**Comment by hostilefork** [comment]
Note this is just another example of this issue:

https://github.com/metaeducation/ren-c/issues/499

Anything that can FAIL which is in the startup code needs to TRAP, and make a decision.   (Print the error, keep going, return an exit code and don't run the REPL, etc.) The C code simply doesn't know what it's supposed to do otherwise.

(If it *does* happen release build should gracefully exit and say "couldn't start", but we need to treat any case where it can possibly happen as a bug.)

**Comment by hostilefork** [comment]
Oops, I misunderstood where the hashing is being done, that code isn't in startup it's in the test.

So this is really an issue for @zsx and I.  Firstly, to improve the heuristics of finding the binary path, and then I guess to probably be willing to run the tests even if you can't find it.

**Comment by draegtun** [comment]
Despite no longing being assigned to this an interesting thought just came to me which we need to remember when running `make`, `r3-make` & running tests.

If you're using a new `r3` then remember it maybe running `%user.r` from your resources directory (under HOME) and so could introduce side effects.

Ditto for `%rebol.r` (though that would be sitting next to `r3` executable).

At this moment `r3-make` is (usually?) r3-alpha binary.  If switch to ren-c based r3-make then need to remember to include `--suppress "*"` in makefile.

Phew... got that off my chest :)

**Comment by zsx** [comment]
Please check if it's fixed with [this commit](https://github.com/metaeducation/ren-c/commit/9fd50b6e6120e496d75d790f8a764eb3c35b7187)

**Comment by gchiu** [comment]
Fixed for me
