### ISSUE TITLE
Startup Error: Script Error: cannot access :system/console/name in path name

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#506]
** Script Error: cannot access :system/console/name in path name
** Where: lib-get apply either* get subparse subparse subparse subparse parse make-banner about do catch either --anonymous-- do trap if --anonymous--
** Near: ...
** File: ../src/core/c-path.c
** Line: 50

Revision: 6d8a0a9169e9e96d80d253cc2f4eef762fa22d91
On Linux, 64 Bit

**Comment by draegtun** [comment]
Hi @IngoHohmann ,

Couple of questions:

* Did you use any command-line switches when you got above error?

* And what happens if you use `--quiet --suppress "*"` command-line switch?

**Comment by IngoHohmann** [comment]
Sorry, I should have tested a little more. The problem happens with

```
./r3 --do "about"
```

Which is part of my semi automated compile script.

And this seems to be the only problematic command.

**Comment by draegtun** [comment]
The error you're getting is because `system/console` is set to `_` (blank!) by default.   Only when the console is invoked is the `system/console` set to a `console!` object.

So because of this ABOUT throws that `system/console/name' error because it can only (now) be run from inside the console and not from a script or `--do`.     

Is this a issue for you?   Let me know because I was planning (in future) of changing ABOUT into a console shortcut.   But if there is a need for ABOUT in script/do world then I can amend accordingly.

**Comment by IngoHohmann** [comment]
No, it's not really a problem for me. I just use it as a quick "OK, it at least starts up alright"-test. 
I can just as well use "print {OK}".
It just took me by surprise.
