### ISSUE TITLE
voids leak to user space and cause crash

### ISSUE THREAD

**Issue by zsx** [metaeducation/ren-c#526]
Voids are only allowed in arrays reified from a va_list or values of a context, however, both of which can be leaked to user space, and thus cause GC to [panic](https://github.com/metaeducation/ren-c/blob/master/src/core/m-gc.c#L844)

Here's some sample code:
```

>> a: make object! [i: 1]
== make object! [
    [self: i]
    [
        i: 1
    ]
]

>> append a 'j
== make object! [
    [self: i j]
    [
        i: 1
        j: &void
    ]
]
>> v: copy values-of a
== [1 &void]

>> recycle

```

**Comment by hostilefork** [comment]
The reified va_list isn't so much a problem, as that array is kind of just for display purposes... it already uses "..." to indicate partial capture, so it could use a similar substitution for voids, e.g. `--void--` or whatever.

So the actual issue would be MAKE ARRAY! operation on a VARARGS! where there's an `<opt>`.  We could simply say you can't MAKE ARRAY! VARARG  if the argument has the `<opt>` annotation, which means that you have to go one item at a time and make your own decision about what to do with voids (placeholders, etc.)

VALUES-OF is annoying.  :-/  I've always been skeptical of the operation itself, because it sort of suggests an ordering of the keys.  Other higher level languages don't expose that.

https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

Is this motivated by abstract thinking, or do you have a specific use case in mind for VALUES-OF on objects which have voids?

**Comment by hostilefork** [comment]
This at least will stop the crashes:

https://github.com/metaeducation/ren-c/commit/2f6cbfac59261c5386c15e7941f6966e0b58c59a

**Comment by zsx** [comment]
It's purely by abstract thinking, inspired by your post about void vs unset

**Comment by hostilefork** [comment]
When first thinking about this, I wondered if unsetting fields in an object actually should delete them completely:

    >> foo: make object! [a: 10 b: 20]
    >> unset 'foo/a
    >> probe words-of foo
    == [b]

But the notion of "in the object but not set to a value" vs. "not in the object" is very tied up with binding, in both an underlying mechanical way (how would the above invalidate references, when the index has been hard coded?) and the slippery way that binding gets set up in the first place.

We really just can't have a world where you are looking at **[a #[unset!] b]** and enumerating that, where you can't tell the difference between the enumerating variable being not set vs. set to an unset.  Placeholders are fine, but your enumeration variable can't get confused of whether it's looking at a placeholder or the variable is not set.  :-/
