### ISSUE TITLE
ODBC extension doesn't release file lock

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#528]
Refers to ODBC branch

When the connection to the ODBC datasource is closed, this should release the lock on the database.  But it doesn't.

**Comment by hostilefork** [comment]
There doesn't seem to be an issue with MySQL or SQLite to run the [insert and select](https://github.com/metaeducation/rebol-odbc/blob/master/tests/odbc-test.reb) test multiple times; e.g. any locks are released so the new process is able to run.  If you're seeing something different, that would need to be more explicit. 

In any case, several improvements have been made to the ODBC extension.  If this issue is still relevant, please list steps to reproduce it on the specific database in question, and file it on the new issue database for the [rebol-odbc GitHub](https://github.com/metaeducation/rebol-odbc/issues).
