### ISSUE TITLE
Unicode support variable with ODBC

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#529]
This may be a limitation of the various ODBC drivers but

1. Firebird 3.0
2. Interbase 2017

I wasn't able to retrieve Unicode characters inserted into the DB ( can't check to see if they were inserted correctly as alternative possible issue )

3. DB2 Express Edition - no problems with Unicode characters

**Comment by hostilefork** [comment]
Unicode and ODBC are a bit of a mess, and I wouldn't be surprised if support for it in older databases was lacking.  They likely expect encoded data to be stored as binaries/blobs.  Also note that fields must be declared as NCHAR or NVARCHAR typically to accept wide characters...at least historically, though one wonders if the regular CHAR/VARCHAR fields are going to drift to carrying encoded UTF-8 bytes.

Anyway...many changes have happened in the implementation of the ODBC extension, and some issues of this nature may have been fixed in the process.  If this issue is still relevant more than 2 years later, please re-file it at the [rebol-odbc extension GitHub](https://github.com/metaeducation/rebol-odbc/issues)
