### ISSUE TITLE
Left-Quoting Enfix Outranks Right-Quoting Prefix Dispatched by Path

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#574]
>> help/docs default
    ** Script Error: default does not allow path! for its target argument
    ** Where:
    ** Near: ... help/docs default ??

**Comment by hostilefork** [comment]
The problem here is DEFAULT is enfix and hard quotes left, while HELP soft quotes right.  Though left-quoting right has priority over right-quoting-left all things being equal, the hard quote gets higher priority than the soft quote...so it's not equal.

The reason HELP soft quotes is because you probably don't want to know that **help (...)** is a GROUP!...you're trying to duck the quoting and get help about the result of an evaluation.  I was also thinking it would bypass any of the recent "abuses", like **help #whatever** looking up bookmarks... so **help (#whatever)** might tell you that's an issue.  But then again, if you get used to HELP working a certain way, this might frustrate you because you actually wanted to HELP on an expression that returned a bookmark and have it act as help would have.  :-/

*O, what a tangled web...*  Maybe there should be a `HELP` and a `HELP*` where `HELP*` is more pedantic and thinks you actually want to know `help* #whatever` is an issue with 8 characters or somesuch.

Anyway, here's a trick to solve the case.  HELP can simulate soft quoting by hard quoting and then doing the handling of GROUP!, GET-PATH!, and GET-WORD! itself...this way it will outrank DEFAULT.

**Comment by draegtun** [comment]
Perhaps `HELP` should be a console dialect?

**Comment by hostilefork** [comment]
Okay, my bad on not solving the HELP/DOC problem.  What is going on there has to do with inability to "sniff" paths for what they look up to, due to the wiliness of path dispatch as well as the potential presence of groups.

I made a workaround which is pretty much aimed at just the HELP/DOC problem, and the commit outlines the technical problem:

https://github.com/metaeducation/ren-c/commit/eb1803a3c63ee776c4b90e64bb66dcd7e7b3cb68

A big question on how to resolve all this is going to come from--I think--ruling out GROUP! in ordinary path dispatch.  If you want to use groups within a path, you will have to **eval :a-get-path/(which has)/(the groups)/(in it)**.  That way, you know it won't be a candidate for infix dispatch of a function (or for overriding a left enfix dispatch).  When there are no groups, it should also mean that the lookup of a path done for infix processing can be cached...as it is for words.

**Comment by hostilefork** [comment]
**...ANOTHER BUG BYTES THE DUST...**

The resolution on this issue is that left-quoting enfix always wins, *unless* it is at the end of a series.  While it may seem somewhat counter-intuitive at first to have right-quoting-left beat left-quoting-right, it's a rule for breaking the contention that you can spot with only one array unit's distance of eyeball.

https://forum.rebol.info/t/the-beta-one-enfix-covenant/1023/6?u=hostilefork
