### ISSUE TITLE
Error processing NEEDS header in scripts.

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#577]
The following error occurs when running a script (not a module) with a NEEDS header:

```
>> do {Rebol [Needs: [<json>]] 1234}
** Script Error: do-needs must return value (use PROC or RETURN: <opt>)
** Where: do-needs either --anonymous-- do
** Near: ... do-needs hdr ?? intern code result: catch/quit/with ...
** File: ../src/core/c-function.c
** Line: 1833
```

[DO-NEEDS](https://github.com/metaeducation/ren-c/blob/master/src/mezz/sys-load.r#L411) currently returns VOID under some circumstances such as the above.

**Comment by hostilefork** [comment]
This happens because [this case](https://github.com/metaeducation/ren-c/blob/c7cf1b177fb9efeb0d3d9a4d6c877be0265a9921/src/mezz/sys-load.r#L411) doesn't handle every possibility explicitly:

    case [
        block [mods] ; /block: return block of modules
        not empty? to-value :mixins [mixins] ; else return mixins, if any
    ]

Under R3-Alpha rules this would be blank, now it's void.  So it needs to be TO-VALUE'd or ELSE [BLANK]'d or CASE [... TRUE [BLANK]].

*(As mentioned, I think the use of conditionals-returning-void is underestimated if one is encountering it strictly through the slog of old compatibility cases.  There's a large system of balances, which ranges everywhere from **append block case [...]** opting out vs. needing a version of APPEND that will append blanks vs one that cannot... to being firm in the commitment that blanks are intrinsically falsey in logic as opposed to signifying a desire to opt-out of a vote.  Still pretty confident about this change.)*

I'm less passionate about prohibiting void results from FUNCTIONs unless you specify it.  Note again that I've opened the discussion on changes-like-this:

https://forum.rebol.info/t/should-function-arguments-to-functions-be-disallowed-by-default/167

Pointing out the existence of the PROC/PROCEDURE I think helps *mostly* because many times, routines that return void aren't meant to *ever* return a value, so you wind up with leaking values.  I've really moved away from thinking this has much to do with security and that it has more to do with helping making problems easier to debug; giving people a bit of a nudge to use a construct that makes them deliberately void their results tightens the bolts.

That to me is the more compelling argument.  But if it's more annoying than it is helpful, maybe it should go.

**Comment by hostilefork** [comment]
Easy fix, so...

https://github.com/metaeducation/ren-c/commit/e9ca69de0721d770386c4300035926bcef1c1575

...but, do remember your vote counts on the discussion points!  While there are a lot of experiments that have gone along, there needs to be a point where they're decided good or bad /etc.  Things like not allowing functions to drop out voids by default are definitely on the table.
