### ISSUE TITLE
REMOVE-EACH modifies 'locked' series

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#612]
REMOVE-EACH overrides a series' *locked* state and modifies contents regardless.

```
>> block: [1 2 3]
== [1 2 3]

>> remove block
** Access Error: series is source or permanently locked, can't modify
** Where: remove
** Near: ... remove block ??
** File: ../src/include/sys-series.h
** Line: 507

>> remove-each item block [item = 1]
== 1

>> block
== [2 3]
```

This also affects map keys:

```
>> mp: make map! []                  
== make map! [
]

>> foo: "abc"
== "abc"

>> poke mp foo "Bar"
== "Bar"

>> remove-each char foo [char = #"b"]
== 1

>> mp
== make map! [
    "ac" "Bar"
]
```

**Comment by hostilefork** [comment]
Resolved by:

https://github.com/metaeducation/ren-c/commit/2460020c26af512a222eed3d8a9a34db57632eb0

We might be able to catch this kind of mistake at compile time with distinguishing `REBSER*` from `const REBSER*`, where getting mutable access would go through a different operation that did the check before giving back the mutable pointer.  I'd considered this long ago, at a time when the code was not under as much control as it is now to make such a dramatic change.  But it's probably worth reviewing now.

**Comment by hostilefork** [comment]
@zsx Early on I found that distinguishing interfaces for `const REBVAL*` was useful (just to help catch cases where routines you didn't expect to modify were doing modifications).  But using a `const REBARR*` or `const REBSER*` seemed to make less sense.  There was no direct tie between the constness of a REBVAL* representing an array and the array itself, so it wasn't clear how to make use of it.

But because there's a lot of ways the issue represented in this bug can come up, I've wondered if there's a smart way to use `const REBSER*` to mean *"series whose protection/frozen/running status has not been checked"*.  Then you would have to use an operation which did the check and failed if it was read only, in order to transition from const to non-const.

The C++ build can help here, as we don't want two different versions of every operation like `ARR_AT()`.  So imagine something like:

    #ifndef __cplusplus
        inline static RELVAL *ARR_AT(const REBARR *a, REBCNT n)
            { return SER_AT(RELVAL, SER(a), (n)); }
    #else
        inline static const RELVAL *ARR_AT(const REBARR *a, REBCNT n)
            { return SER_AT(RELVAL, SER(a), (n)); }

        inline static RELVAL *ARR_AT(REBARR *a, REBCNT n)
            { return SER_AT(RELVAL, SER(a), (n)); }
    #endif

In other words, the C build merrily gives back mutable values even if the input array is const...so it doesn't enforce the check.  It's the C++ build that won't give you back a mutable value unless you've taken care of the "proof" that you've run the array through a lock check first.

It's not perfect, in terms of this information going stale... if you're running a native, and call out to user code that can-do-anything, and that code protects something that wasn't protected before.  Given this bug, consider something like:

    >> block: copy [1 2 3]

    >> remove-each item block [
        protect block
        item = 1
     ]

*(Note: This isn't the only reason that remove-each kind of sucks...it has to slide all the data down for each removal in order to keep the array coherent in case code in the body accesses it...it's probably better to map-each and then swap out the data arrays.)*

Anyway, it seems to me that a systemic solution to the problem would be better, and I think letting the C++ build catch it would be good.  It's not the highest priority task, but wondering what you think of the concept of `const` on REBSER/REBARR/etc. meaning "runtime flags haven't been checked yet".

**Comment by zsx** [comment]
@hostilefork I like the idea of letting C++ build do the checking.

**Comment by hostilefork** [comment]
Reopening because changing the PROTECT status *during* the enumeration isn't respected; it checks before enumerating, then runs arbitrary user code.

    block: copy [1 2 3]
    remove-each item block [
        protect block
        item = 1
     ]

Please see discussion:

https://forum.rebol.info/t/remove-each-x-for-each-map-each-remove-each-x-remove-each/262

**Comment by hostilefork** [comment]
Okay, I think this is a pretty good answer for the moment:

https://github.com/metaeducation/ren-c/commit/2f6ac057f8e9123ae99b59a3a5fd609120059d42

And I think we have a plan going forward for what to do to stomp this category of bug out for good.  But that "right answer" involves `const`, and once you add const in one place, you have to go around making the other places correct.  This is what makes const so useful since it pushes the check all the way through...but it means getting a lot of merge conflicts...and I have branches outstanding I want to get in first that are more important.
