### ISSUE TITLE
FOR-SKIP returns BAR! on a non-empty series where body returns VOID.

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#615]
Example:

```
>> foo: [1]
== [1]

>> type-of for-skip foo 1 []
== bar!
```

**Comment by hostilefork** [comment]
Glad you commented.  This is intentional, so please do a design review with me...

If a loop doesn't run its body, it returns void.

    x: 10
    while [x > 20] [
        print "x is greater than 20"
    ] else [
       print "the loop body didn't run even once"
    ]

Cool, huh?  Mix it with your THEN and even cooler.

If a loop BREAKs, then it will be a blank.

But if it completes, it always produces a truthy value.  BAR! was chosen as the oddest truthy value.

This permits all kinds of interesting chaining, and if you don't remember that, I'll dig it up.

**Comment by hostilefork** [comment]
With the rise of `did` and `not`, I am more confident that things which return BLANK! on failure should use BAR! when synthesizing truthy values, instead of #[true].

The feature of synthesizing truthy values--and reserving voids for "loop body never ran"...seems a good one to me...

    for-each item vars [
        ...
    ] else [
        ... stuff to do if vars is empty ...
    ]

If you have code you want to run if the body never runs, or if there's a break, then TO-VALUE or its even better TRY could merge those both to BLANK!, which is falsey so you could use with OR:

    try for-each item vars [
        ...
    ] or [
        ... stuff to do if vars is empty or if there was a break ...
    ]

Being able to use BREAK to give clear feedback to an ANY or an ALL is cool.  Consider a need in emulating R3-Alpha's FOREACH, when the vars are not a BLOCK! and don't contain SET-WORD! it acts normally (set-words in blocks for vars do something weird/bad):

        any [
            not block? vars
            for-each item vars [if set-word? item [break]] else [true]
        ] then [
            return for-each :vars data body ;; normal FOREACH
        ]

I think it's pretty solid, to "barify" the blanks/voids/falses that might drop out of the loop.  If you find code examples which suggest it's not in the interest of greater good, please let me know...

**Comment by hostilefork** [comment]
Reopening.  Because the more I've reviewed the special role of null (formerly "void"), the more I want to use it as a means of avoiding "random-seeming" mutations of in-band values.

Wanting a loop that never ran to return null came first, because it seemed like it had a lot in common with a branch that didn't run.  So later...when trying to make it possible to combine loops "from the outside" and have a way to determine breaks, I turned to falseyness...then making a loop that tried to return falsey results return a truthy bar.

But if a loop that didn't run even once would return blank, then the user has enough control to detect that situation--or not.  They could make the loop always return a non-blank.  Then, so long as null loop bodies always get blankified...the unique condition of null can be used to detect breaking.

You get nearly the same level of control, albeit having to be a bit more complicit.  Basically what used to be the blank signal becomes void (breaking), what used to be the void signal becomes blank (loop never running), and the loop user becomes responsible for any means of distinguishing the loop never running from whatever other run condition by way of returning something non-blank (and non-null, because that would just be blanked).

I imagine this seems like a saner plan...?

**Comment by hostilefork** [comment]
New rules begun here:

https://github.com/metaeducation/ren-c/commit/0e2337a8e19679711365dda488ac87a669aa23d8

*(I say "begun" because things like MAP-EACH still present a question, of if they should return NULL or the result so far on BREAK...or if REMOVE-EACH should not do the removals if there's a BREAK, etc.)*

The change means that if you say:

     while [condition] [...] else [...]

Then the ELSE has what will run if you BREAK.  If you wanted to distinguish your loop result in a way that differentiates runs at least once from never, you could say:

    while [condition] [... true] or [...]

Because currently (and if decided to ultimately be a good idea, indefinitely) OR with a BLOCK! on its right will tolerate null on the left.  So that would run the clause if the loop did a BREAK or never ran.  If you said:

    blank? while [condition] [... true] then [...]

You would get it to run the clause only if the loop never ran.

There are `while/opt` and other variants added for trying out, which basically never blankify... meaning a loop that never runs will be null, a loop whose last body run returns null will return null, and BREAK will return null.  Will see if anyone uses that.
