### ISSUE TITLE
Attempting to build R3 on ARM64 fails (struct alignment)

### ISSUE THREAD

**Issue by hoosierEE** [metaeducation/ren-c#631]
Following up a recent bit of [chat](https://chat.stackoverflow.com/transcript/message/39502218#39502218), I am attempting to build R3 from source on my ARM64/Linux machine.

    uname -a
    Linux localhost 3.18.0-14875-g438cb8ab27c6 #1 SMP PREEMPT Sat Sep 16 09:49:59 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux

Here's what I did:

1. download experimental Rebol3 binary for ARMhf from [here](http://www.rebolsource.net/), specifically this one: [r3-linux-armhf-g25033f8](http://www.rebolsource.net/downloads/experimental/r3-linux-armhf-g25033f8) (quick sanity check - the interpreter runs and evaluates simple expressions like 1 + 2)
2. clone [Rebol](https://github.com/rebol/rebol) at 25033f8
3. copy experimental R3 binary to rebol/make/r3-make
4. run `make clean` (succeeds)
5. run `make prep` (succeeds)
6. run `make r3` (succeeds?)
7. attempt to run resulting r3 binary: `./r3` (fails)

The failure is:

    REBOL Host Failure:
    Incompatible struct alignment

Step 6 _seems_ to succeed.  At least, no obvious error message appears.  There is one line at the very end of this last step that seemed a little weird to me: 

    nm: r3: no symbols

**Comment by hostilefork** [comment]
**If your goal is to build Red, none of the below will help.**  Red is built on Rebol2, and they intend to build Red-in-Red rather than port it to Rebol3. 

---

Generally this happens because your compiler is 64-bit, but the #define's which are needed to tell the interpreter that it is operating with 64-bit pointers aren't set.  So you either need those #define's or you need to compile with `-m32` and ask to generate a 32-bit executable.

I note that you tried removing the `-m32` and still had problems, but helping further has a problem because you are trying to build R3-Alpha, and not the branch we call "Ren-C":  There's not a whole lot of purpose in building R3-Alpha.  No one would process a pull request against it--the people empowered to do so disappeared.  You might notice the last commit was ` Mar 3, 2014`.  OTOH Ren-C is actively developed.

https://github.com/metaeducation/ren-c

Unfortunately, the build process is (currently) dependent on having a Ren-C interpreter available to generate the preparatory files.  And you're trying to build for a platform we don't auto-build executables for yet:

http://metaeducation.s3.amazonaws.com/index.html

So there is a bootstrap issue.  *(The hope is to make the build process again allow to use an R3-Alpha for bootstrap purposes, that just isn't done yet.)*

What needs to be done, then, is to use a platform where there *is* a binary, and tell the preparatory phase to build a GNU makefile.  Then transfer the files over and do a **make** on the ARM machine.  And if it still isn't working, then we could work on figuring out why.

Again, none of this is much help if you're trying to build Red.

**Comment by hoosierEE** [comment]
Thanks for the detailed explanation.  I did start with the intention of building Red, and now I see that I went the wrong way toward that goal.  However I've done a bit more reading and it seems like as far as Linux/ARM is concerned, Rebol or Ren-C might be the better match.  So I'll be going forward with the intention of building Ren-C for Linux/ARM64.

So to make it concrete, if I am using OSX as the prep machine, and Linux/ARM64 as the target machine, the steps to build Ren-C are:

1. get Ren-C interpreter for OSX
2. Using OSX, generate makefile for arm64: `make -f makefile.boot OS_ID=0.4.22` ( from [here](https://github.com/metaeducation/ren-c/blob/master/src/tools/systems.r#L139) )
3. transfer all the files to arm64, then run `make` there.

Is that right?

**Comment by hostilefork** [comment]
@hoosierEE Yup!

Sorry that you are catching this at a time where the build is not as streamlined as we would like it.  There was some redundancy between the build process being duplicated between CMake and GNU make configuration...and also a desire to be able to use a Rebol as the sole driver of the build and not need any make system installed.  *(That, plus building [TCC](https://en.wikipedia.org/wiki/Tiny_C_Compiler) into the rebol executable, could create a system that could build itself from source all on its own.)*

So it's kind of on the first iteration of that, and the documentation isn't updated, because it's not finished and it's rare to have people coming and trying to bootstrap it themselves.  But we can give support for any issues in chat.

**Comment by hoosierEE** [comment]
Small update: 

I attempted to do the build process as in my previous comment, using [r3-564aac0](http://metaeducation.s3.amazonaws.com/index.html), and got the following error:

```
gcc -c -I../src/include -DREB_API -DENDIAN_LITTLE -DHAS_LL_CONSTS -D_FILE_OFFSET_BITS=64 -DUSE_PIPE2_NOT_PIPE -D__LP64__ -DTO_LINUX -DTO_LINUX_AARCH64 -O2 -fvisibility=hidden -o objs/s-find.o ../src/core/s-find.c
../src/core/p-signal.c:122:20: error: use of undeclared identifier 'SIGPOLL'
            return SIGPOLL;
                   ^
1 error generated.
make[1]: *** [objs/p-signal.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [top] Error 2
```

I googled and found [a similar issue](https://github.com/howl-editor/howl/issues/68#issuecomment-134385095) when attempting to cross-compile from OSX, and installed gtk+3 and md5sha1sum via Homebrew as they suggested, but the error persisted.

I wasn't sure how to pass the `-r` flag as suggested in that thread, so I instead commented out the lines of `src/core/p-signal.c` which mention `SIGPOLL`.

Following that, I got 

```
../src/os/linux/dev-signal.c:102:21: error: variable has incomplete type 'struct timespec'
    struct timespec timeout = {0, 0};
```

...which I solved by adding `#include <time.h>` as suggested [here](https://stackoverflow.com/a/14415489/2037637).  This seemed to make some progress, until it got to the linking stage which failed with this error:

```
gcc -o r3 -fvisibility=hidden -rdynamic objs/a-constants.o objs/a-globals.o objs/a-lib.o objs/b-init.o objs/c-bind.o objs/c-do.o objs/c-context.o objs/c-error.o objs/c-eval.o objs/c-function.o objs/c-path.o objs/c-port.o objs/c-signal.o objs/c-value.o objs/c-word.o objs/d-crash.o objs/d-dump.o objs/d-eval.o objs/d-legacy.o objs/d-print.o objs/d-stack.o objs/d-stats.o objs/d-trace.o objs/f-blocks.o objs/f-deci.o objs/f-dtoa.o objs/f-enbase.o objs/f-extension.o objs/f-int.o objs/f-math.o objs/f-modify.o objs/f-qsort.o objs/f-random.o objs/f-round.o objs/f-series.o objs/f-stubs.o objs/l-scan.o objs/l-types.o objs/m-gc.o objs/m-pools.o objs/m-series.o objs/m-stacks.o objs/n-control.o objs/n-data.o objs/n-do.o objs/n-error.o objs/n-function.o objs/n-io.o objs/n-loop.o objs/n-math.o objs/n-native.o objs/n-protect.o objs/n-reduce.o objs/n-sets.o objs/n-strings.o objs/n-system.o objs/n-textcodecs.o objs/p-clipboard.o objs/p-console.o objs/p-dir.o objs/p-dns.o objs/p-event.o objs/p-file.o objs/p-net.o objs/p-serial.o objs/p-signal.o objs/s-cases.o objs/s-crc.o objs/s-file.o objs/s-find.o objs/s-make.o objs/s-mold.o objs/s-ops.o objs/s-trim.o objs/s-unicode.o objs/t-bitset.o objs/t-blank.o objs/t-block.o objs/t-char.o objs/t-datatype.o objs/t-date.o objs/t-decimal.o objs/t-event.o objs/t-function.o objs/t-gob.o objs/t-image.o objs/t-integer.o objs/t-library.o objs/t-logic.o objs/t-map.o objs/t-money.o objs/t-object.o objs/t-pair.o objs/t-port.o objs/t-string.o objs/t-time.o objs/t-tuple.o objs/t-typeset.o objs/t-varargs.o objs/t-vector.o objs/t-word.o objs/u-compress.o objs/u-md5.o objs/u-parse.o objs/u-sha1.o objs/u-zlib.o objs/tmp-boot-block.o objs/tmp-dispatchers.o objs/host-main.o objs/host-device.o objs/host-stdio.o objs/host-table.o objs/dev-net.o objs/dev-dns.o objs/generic/host-memory.o objs/generic/host-gob.o objs/posix/host-readline.o objs/posix/dev-stdio.o objs/posix/dev-file.o objs/posix/host-config.o objs/posix/host-error.o objs/posix/host-library.o objs/posix/host-process.o objs/posix/host-time.o objs/posix/host-exec-path.o objs/linux/host-browse.o objs/posix/dev-event.o objs/posix/dev-serial.o objs/linux/dev-signal.o objs/crypt/mod-crypt.o objs/crypt/aes/aes.o objs/crypt/bigint/bigint.o objs/crypt/dh/dh.o objs/crypt/rc4/rc4.o objs/crypt/rsa/rsa.o objs/crypt/sha256/sha256.o objs/crypt/ext-crypt.o objs/process/mod-process.o objs/process/ext-process.o objs/png/mod-lodepng.o objs/png/lodepng.o objs/png/ext-png.o objs/gif/mod-gif.o objs/gif/ext-gif.o objs/jpg/mod-jpg.o objs/jpg/u-jpg.o objs/jpg/ext-jpg.o objs/bmp/mod-bmp.o objs/bmp/ext-bmp.o objs/locale/mod-locale.o objs/locale/ext-locale.o objs/uuid/mod-uuid.o objs/uuid/libuuid/gen_uuid.o objs/uuid/libuuid/unpack.o objs/uuid/libuuid/pack.o objs/uuid/libuuid/randutils.o objs/uuid/ext-uuid.o objs/debugger/mod-debugger.o objs/debugger/ext-debugger.o -lm -ldl
Undefined symbols for architecture x86_64:
  "_pipe2", referenced from:
      _OS_Create_Process in mod-process.o
  "_sigtimedwait", referenced from:
      _Read_Signal in dev-signal.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [r3] Error 1
make: *** [top] Error 2
```

Not sure if this `Undefined symbols for architecture x86-64` is a bug, as I'm using MacOS (x86-64), but targeting Linux/ARM64.

**Comment by hostilefork** [comment]
> I'm using MacOS (x86-64), but targeting Linux/ARM64.

Well, that's not likely to work (unless you know something I don't...)

What *might* work would be to run `make clean`, then `make prep` on your mac, with the ARM target.  Once that's done, zip up the whole directory and take it over to your ARM64 machine, which is hopefully equipped with GNU make and GCC and such.  Then try `make`-ing over there.

Again: you might bump into a similar issue of no-one-ever-building-for-ARM64-before (nor building for ARM32 on an ARM64 compiler).  So the proper switches to make it run may not be there.  You can read a little summary of how platforms are *currently* configured in [`%systems.r`](https://github.com/metaeducation/ren-c/blob/756bb15a8a9c6c3be585f0d570be8267587ea2df/src/tools/systems.r)...and it may be we need to add a system and tinker with it...

**Comment by hostilefork** [comment]
I should mention that while it might seem the generated products would be nicely positioned in an "out-of-source" build location, Rebol didn't do that historically.  Hence they're sort of scattered around.  This is one of the many things that we need to address now that the CMake build system from Atronix and the R3-Alpha GNU make build system are being replaced by an all-Rebol "rebmake".

**Comment by hoosierEE** [comment]
> What might work would be to run `make clean`, then `make prep` on your mac, with the ARM target. 

...I tried that, but only zipped the `make` folder.  Will retry with the whole repo.  Thanks for the info!


---

For clarity, here's exactly what I've been doing up to now:

(on OSX machine):
1. clone ren-c from github
2. download an r3 binary ( r3-4291cd3 ) from [here](http://metaeducation.s3.amazonaws.com/index.html)
3. `cd ~/ren-c/make`
4. `cp ~/Downloads/r3-4291cd3 r3-make`
5. `chmod +x r3-make`
6. `cp makefile.boot makefile`  for some reaons `make -f makefile.boot` only works when no arguments are given
7. `make clean`
8. `make prep OS_ID=0.4.22`  After this step, the `make` folder appears unchanged but I presume a bunch of stuff has been placed in `src`.

So my next steps should be to zip the repo, transfer to the ARM machine, and:

(on ARM machine):
1. download ren-c experimental ARMhf binary (r3-7e8edcf0-debug)
2. `cp ~/Downloads/r3-7e8edcf0-debug ~/Downloads/ren-c/make/r3-make`
3. `cd ~/Downloads/ren-c/make`
4. `make`

Good plan?

For what it's worth, I've got Centos7 and Ubuntu16.04 vms on VirtualBox on the OSX machine. would either of those be a better cross-compile environment to start in?

**Comment by hostilefork** [comment]
> (on ARM machine):
> 
> download ren-c experimental ARMhf binary (r3-7e8edcf0-debug)

You shouldn't need it if you have GNU make, and went with the default of GNU makefile generation.  Just the `make` command should do.

> Good plan?

Overall well planned, though I regret that you're dealing with artifacts of outdated documentation and files we haven't gotten around to yet.  In fact, if you're having trouble with %makefile.boot doing anything other than a start-to-finish build, it's likely because it's marked for death and no one bothered to update it.

If you just take the appropriate executable and run it with %make-make.r that might go better.  In the make directory:

> ./r3-osx-x64-368bd5a-debug ../src/tools/make-make.r OS_ID=0.4.22 DEBUG=asserts REBOL_TOOL=./r3-osx-x64-368bd5a-debug 

Something like that.

It shouldn't matter what platform you start from, in theory.

**Comment by hostilefork** [comment]
Also, if you're handy with a debugger, you can instead say `DEBUG=symbols` and `OPTIMIZE=0` *(or DEBUG=sanitize if you want to get really fancy and build with [address sanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer), which the wiki says might work on ARM64, but is not actively tested or supported.)*

**Comment by hoosierEE** [comment]
Cool, thanks for the guidance.  I'm not going to pretend I'm handy with a debugger.  I understand the pain of cross-platform builds quite well, and compared to some other projects I've attempted to build I must say so far this experience has been pretty good.

**Comment by hostilefork** [comment]
> Compared to some other projects I've attempted to build I must say so far this experience has been pretty good.

I don't know if that says more about other projects, as opposed to saying that our build process is in great shape!  Here's a little historical background and a question about if anyone has "vision statements":

https://forum.rebol.info/t/what-should-the-experience-of-building-rebol-be-like/334

But I do think it *can* be good.  And the goal is to use the trial by fire of running on old platforms to double-check on the complexity creep.  If you look here at the [build matrix](https://github.com/metaeducation/ren-c/blob/e6cab210d6355f50b36fe6e15acc1f5859a95c30/.travis.yml#L60) for Travis CI we're trying to keep things going on old compilers, build as plain C or C++.  *([Here's some about that.](https://github.com/metaeducation/ren-c/wiki/On-Building-Ren-C-With-Cpp-Compilers))*  I use Haiku as a test case on occasion.

*(And I just realized due to this discussion we could actually use one of the instances that builds for Windows on Linux as a bootstrapping test, so I added that in.)*

While the history of the project is somewhat chaotic, I do believe there's something in it all.  Stop by SO chat if you want an earful on that.  :-)

**Comment by hostilefork** [comment]
@hoosierEE -- don't know if you still have interest in this--if not I can close the issue.

But if you *are* still interested, there have been some improvements to the build process...it now generates the "prep" files in a single directory under `%make/`.  This means bootstrapping to new platforms should be easier.

There's also some experiments now [with JavaScript Emscripten and Webassembly](http://giuliolunati.altervista.org/try-renc.html), which is interesting...so new stuff afoot.

**Comment by hoosierEE** [comment]
Hi, go ahead and close for now.  Not sure when I'll dive back in.  Thanks
for the update though!
