### ISSUE TITLE
Literal block within loop isn't locked.

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#633]
I was able to perform the following:

    >> repeat x 1 [append foo: [] x]                                     
    == [1]

Which as I understand shouldn't be possible as literal blocks should be locked by default.

**Comment by hostilefork** [comment]
Per chat discussion, this is due to an implicit deep copy of the body which is made of the body, to allow it to take on new bindings (e.g. the freshly-created **x** for this loop) without permanently mutating the binding of the passed in body.

See long explanation on [Copy_Body_Deep_Bound_To_New_Context()](https://github.com/metaeducation/ren-c/blob/e6cab210d6355f50b36fe6e15acc1f5859a95c30/src/core/n-loop.c#L132), which emphasizes that making these copies is bad for other reasons...so a better method is needed.

**Comment by hostilefork** [comment]
This particular issue is addressed by [the CONST/MUTABLE commit](https://forum.rebol.info/t/source-mutability-const-and-mutable/976), and now gives an error:

    >> repeat x 1 [append foo: [] x]
    ** Access Error: value is CONST (see MUTABLE): []

It's still making a copy.  But now it's not whether something has ever been copied from "being source" that makes a difference.  What matters is if a "wave of evaluation" ever passes through, and sees something that looks like a literal assignment...without a MUTABLE influencing step in the "wave" to mitigate the evaluator's default bias to constness.

There's still a lot to hammer out, but the new approach is a very promising direction.
