### ISSUE TITLE
Left-Arrow key miscounts prompt width at console corrupting input display

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#651]
At the console (tested with OS X Terminal app) when using arrow keys to navigate input, using the left arrow on input containing a wide UTF-8 character the cursor goes beyond the beginning of the prompt.

Excuse the quality of the screen grab:
![utf-behaviour](https://user-images.githubusercontent.com/986608/32966832-1cce94ea-cba9-11e7-9c85-fdebbf4f3f1b.gif)

**Comment by hostilefork** [comment]
Looks like a nice screen grab to me.  From [the commit message](https://github.com/metaeducation/ren-c/commit/c3bc297197a55bba7380974d9cdd1f264ba0a60e):

> It now supports UTF-8 entry...although the cursor-oriented commands need to be updated to account correctly for multibyte characters.  Though those cursor commands are unfinished, it is still a significant improvement.

My mentality was just kind of "show it possible and then, motivated individuals can fix it".  Bear in mind, I'd been avoiding touching any of this due to how awful the original code was.

But yes, it's a bug, so it belongs in the issues...

**Comment by hostilefork** [comment]
Resolved by @DanDLee in:

https://github.com/metaeducation/ren-c/pull/678/commits/3921132021b5f470e54b45016cb154c215ecf67a
