### ISSUE TITLE
Script Error: also is missing its code argument

### ISSUE THREAD

**Issue by geekyi** [metaeducation/ren-c#665]
```
>> print [system/build system/commit]
5-Dec-2017/4:29:03 bc8d0fc4994ce88dc039f0a81abbd4931247d127
```

## Prerequisite
 - Recent build
 - `>> also: :also-do`

## Minimal code

```rebol
>> 1 also [print 2]
** Script Error: also is missing its code argument
** Where: _
** Near: 1 also [print 2] ??
** File: ../src/core/c-eval.c
** Line: 1149
```

## Context
Following the [**ALSO** mini doc on trello](https://trello.com/c/Y03HJTY4/174-also-is-changed-to-infix-for-clarity-and-matching-then-and-else), the last snippet gives:

```rebol
>> switch x [
[       1 [print "it was one"]
[       2 [print "it was two"]
[   ] then [
[       print "it was either one or two"
[   ] also [
[       print "it was anything, this always runs"
[   ] else [
[       print "it was neither one nor two"
[   ]
it was two
it was either one or two
** Script Error: also is missing its code argument
** Where: _
** Near: [
    print "it was anything, this always runs"
] else [
   ...
** File: ../src/core/c-eval.c
** Line: 1149
```

**Comment by hostilefork** [comment]
Oh, no, you can't do this:

    also: :also-do

The reason you can't do that is because there's no such thing as an "enfix function".  There's only FUNCTION! and there's a particular way of setting things that ties the relationship between a function and a word to be enfixed.  You're not using one of those mechanisms here.

You have to say:

    set/enfix 'also :also-do

Or you can use the convenience wrapper called ENFIX which is, itself enfix:

    also: enfix :also-do

The trick there being that it quotes the left and then runs SET/ENFIX for you.  Fancy.  :-)
