### ISSUE TITLE
Unexpected behaviour of AND

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#673]
`all [_ undefined-word]` 
works fine, but
`_ and undefined-word` 
fails.

**Comment by hostilefork** [comment]
The very experimental behavior of AND to try and short-circuit is likely to be cut.  :-/  It was known that this method could never cover *all* cases, but thought it might be able to conservatively notice those cases and then--if it wouldn't work--suggest a GROUP!  But it seems that when the fully proper conservatism is applied, one would almost *always* need some grouping structure (or BLOCK!), unless you used just GET-WORD! or GET-PATH!s...otherwise, you don't know how much to skip of an "unknowable" operation.

This isn't to say the ability to "run the evaluator in neutral" is a *completely* useless tool, it may have a use.

We still might *consider* the idea that AND short-circuit, if it forced the right hand side to be in a GROUP!:

    if _ and (undefined-word) [
        ...
    ]

Which looks perhaps more natural than in a BLOCK!, but becomes a quoting operator.

But a non-short-circuit AND is not completely useless (sometimes you want to evaluate both sides, even though you are taking the logical result after the evaluation).  So it's probably best to back off the strange anomalous rule.

**However** that wasn't actually the main part of the change..  The main part of the change is to make the left side of AND enfix normal.  That's being kept, until someone sees a good reason not to keep it!

**Comment by hostilefork** [comment]
For now I've decided to keep short circuiting, but require a GROUP! on the right hand side...please see this:

https://github.com/rebol/rebol-issues/issues/1879

It's a little sad to need the "boilerplate".  But there's no real way around it if the feature is to actually work.

Fortunately, chaining works in left enfix normal, so you can do **xxx and (yyy) and (zzz)** and it will short circuit everything on the right once one clause fails.

If it looks too funny to think that the first expression doesn't need a GROUP!, you can put one on it optionally as a pattern.  **(xxx) and (yyy) and (zzz)**

Here's a commit getting rid of the DON'T experiment, and switching to just GROUP!

https://github.com/metaeducation/ren-c/commit/91b92ddae5f4b097992831c5ab419f1a92501acf

I will leave this open until you let me know what you think!  Good idea?  Bad idea?

**Comment by giuliolunati** [comment]
Having an alternative short circuit syntax is better than no. (...) and
(...) is visually better than all[... ...]. So ok for me!

Il 03 gen 2018 00:07, "Brian Dickens" <notifications@github.com> ha scritto:

For now I've decided to keep short circuiting, but require a GROUP! on the
right hand side...please see this:

rebol/rebol-issues#1879 <https://github.com/rebol/rebol-issues/issues/1879>

It's a little sad to need the "boilerplate". But there's no real way around
it if the feature is to actually work.

Fortunately, chaining works in left enfix normal, so you can do *xxx and
(yyy) and (zzz)* and it will short circuit everything on the right once one
clause fails.

If it looks too funny to think that the first expression doesn't need a
GROUP!, you can put one on it optionally as a pattern. *(xxx) and (yyy) and
(zzz)*

Here's a commit getting rid of the DON'T experiment, and switching to just
GROUP!

91b92dd
<https://github.com/metaeducation/ren-c/commit/91b92ddae5f4b097992831c5ab419f1a92501acf>

I will leave this open until you let me know what you think! Good idea? Bad
idea?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/metaeducation/ren-c/issues/673#issuecomment-354899617>,
or mute the thread

**Comment by hostilefork** [comment]
All right then.  I think I also like it better than using AND and OR for bitwise math, and I think non-short-circuit would throw people off.  There's a way, as I say, that this is kind of "instructional" about how you can bend the language; it works how it has to, and then people can learn from it when trying their own ideas.

Given it's not needed to force the GROUP! on the left, people can make up their own mind on whether they want to always put it.  But it might be that you have a short expression on the left and long on the right, so it would look natural:

    if some-flag and (longer expression here) [
        ...
    ]
