### ISSUE TITLE
Assert on accessing utc where date time has no zone.

### ISSUE THREAD

**Issue by codebybrett** [metaeducation/ren-c#680]
These lines cause an assertion:

    date-110: 7-aug-2017/03:00 ; DateTime
    date-110/utc

Assertion failed: [sys-time.h line 161](https://github.com/metaeducation/ren-c/blob/e7dfcc3bf644877463815141de60741027a0d3d2/src/include/sys-time.h#L161)

**Comment by hostilefork** [comment]
That's a bit of an odd case given that you're asking for UTC time from something that doesn't have a time zone.  So instead of adjusting a known time, R3-Alpha just tacked 0:00 onto it.

I patched up the assert and made it do what I think R3-Alpha does:

https://github.com/metaeducation/ren-c/commit/c60fdf6e299105ed0df89ff0b495a12fbfd4807f

But perhaps it's something you can add to your tests, as to whether this should be a legal operation, or if you want to do this kind of thing you need to do it explicitly by adding a timezone...

**Comment by codebybrett** [comment]
Thank you.  I reacted to the assert, but with jetlag had neglected to remember #608 straight away.

> But perhaps it's something you can add to your tests, as to whether this should be a legal operation

Yep, had it [in my proposed tests](https://github.com/codebybrett/reb/blob/master/test/dates.test.reb#L80-L81) as an error condition.

Will bump the [forum question](https://forum.rebol.info/t/how-to-deal-with-users-mutating-date-and-time-to-be-invalid/240/4).
