### ISSUE TITLE
EMIT-PROTO not being called for source-analysis.reb

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/ren-c#716]
I had noticed some of the checks weren't seeming to have found problems like mismatched function names in comments to the functions.  Thought I might tinker a little in the source-tools.reb just because I'm interested in seeing how recent new constructs might help shorten or improve the code.

But realized I was in unfamiliar territory with the PARSING-AT stuff, and I should probably just ask.  What seems to happen is that the IS-INTRO rule here is not triggering:

https://github.com/metaeducation/ren-c/blob/bc2b9ff75eb0ecd3824282533011b3481ac234af/make/tools/common-parsers.r#L262

It seems to get to doubleslashed-lines, but never past that.  So effectively, EMIT-PROTO never seems to get called in %source-analysis.reb...

**Comment by codebybrett** [comment]
PARSING-AT is a way to use arbitrary rebol code as a parse rule. The code must return the next parse position to indicate a match, or blank to indicate failure.

IS-INTRO is not matching because one of the conditions for a match is that DECODE-LINES [can do it's work without error](https://github.com/metaeducation/ren-c/blob/bc2b9ff75eb0ecd3824282533011b3481ac234af/make/tools/common-parsers.r#L330). The working assumption is that DECODE-LINES is written without error in itself and any error raised will be due to an incorrect input format. Unfortunately, a bug had been introduced into DECODE-LINES at some point, causing an error (join-of complaining of an argument). I do have [tests for DECODE-LINES](https://github.com/codebybrett/reb/blob/master/test/text-lines.test.reb#L30-L41), but I wasn't sure it was relevant to include them in ren-c so I never did. Maybe extending tests to anything the build depends upon is fair.

The reason the build works but source tools does not, is that we now have two versions of DECODE-LINES, one in common-parsers.r and one in %test/lib/text-lines.reb.  One more amended than the other.

My first reaction is "we really should be common source tools in a single shared folder", but then "ah, source analysis can use the latest ren-c, but the build may need to support older builds?, hmm...."

I'm a bit torn here.  The quickest fix is to delete DECODE-LINES from text-lines.reb, immediate problem solved.  But I'm wondering whether it's better to have a common %sourcetools/ folder (peer to %make/) that can be home for all source processing and related rebol scripts. This avoids duplication and highlights that scripts might be shared. If this was the case %common-parsers.r, %text-lines.reb, %source-tools.reb would move there.  Not sure how that'd sit with you and Giulio now that the build has a "from here down" structure.

There is some duplication other than decode-lines that needs removing too.

## line-from-pos/line-of ##

While looking for the bug I noticed that line-of was renamed to line-from-pos, but there's a couple of places in common-parsers.r where this wasn't done.

I also note my formulation of line-from-pos is unnecessarily wasteful of memory. So that needs cleanup. There's a similar function in the tests by Ladislav, so maybe only one of them is needed.

## parsers ##

While on the topic of the build source parsers/generators. It's clear that these scripts are getting quite complex.

I derived them from the original scripts, by performing small refactorings/rewrites to ensure that whatever was generated was exactly the same as the original scripts (not being a C person I wasn't sure of what was important or not). Goals were to avoid duplication yet extend features only when needed (performance), while also maintain the logic of the original scripts. I hoped that better variable naming and common routines would allow others behind me to more easily see opportunities for improvement.  I'm not sure but I fear that my original design has contributed to a path of evolving complexity.

Perhaps a new approach is needed, because as the code necessarily evolves the logic is becoming even more obscure than originally.  I know that language parsers are going to be complex, but it would be nice to have a simpler data flow. Maybe @rgchris  might run away screaming, but as an expert on elegance in Rebol and parsing, his input would be valuable should he have a moment to give some. 

Then there's the wider question of reusing parse rule grammars.  Specifically here c-lexicals.reb.  I did not want emit actions embedded in the grammar, because the grammar should be useable in multiple scenarios and emit actions have a side effect of tying grammars to particular purposes.  I wanted to reuse c-lexicals the other day with a different grammar/parser idea, but the existing object structure does not lend itself well to reuse. I'm wondering whether it should be block definitions only, building the parsers objects from there as needed.  Amongst your many thought lines, I would welcome any thoughts you have on what might be a "best practice" for parse grammar rule reuse for as yet unseen parsers.

**Comment by hostilefork** [comment]
> Unfortunately, a bug had been introduced into DECODE-LINES at some point, causing an error (join-of complaining of an argument). 

I've wondered about this problem before... and if there's some sort of category of errors that one would generally want to not consider ignoring.  Things like a typo or invalid type argument error are different from errors which originate from missing files or other things.  I'm not sure exactly, as it's a dodgy proposition to not know which specific errors you are ignoring...but it was a thought I had that maybe some error category/categories would not count by default.

> While on the topic of the build source parsers/generators. It's clear that these scripts are getting quite complex.

As with the build system, I think every little bit could help...just making a casual habit of going over the code and refactoring it.  I did a couple of tweaks while I was looking over things:

https://github.com/metaeducation/ren-c/commit/3533e8c508c4b9a6f34df32cdad2c8354f2069e5

I'm definitely not opposed to seeing them get simpler, and I've mentioned my feelings that PARSE itself needs some kind of renaissance-of-extensibility.  Firstly there is the reusability of parse rule axis.  Then I have misgivings about the idea that someone with an idea like COLLECT (with requisite rollback) would need to hack on C source code to get it.  And whatever exactly the desire that PARSING-AT is there to address, I'm sure, fits into my "there needs to be a better way."

But that's unfortunately all still just at the feeling stage.  :-/  I know there are just going to have to be some things that fall into the hands of future Rebol designers... so it's important to set one's sights onto how to make sure things are set up with the best precedent and best framework for trying new solutions as they are imagined.

> Not sure how that'd sit with you and Giulio now that the build has a "from here down" structure.

It's good to have the scripts that are specifically and solely used for building Rebol in one place.  I'm not sure how this applies to scripts that can be used for analyzing Rebol source.  But definitely we don't want repeated code.

Eliminating the repetition seems like the highest priority, and then we'll worry about how to make the file tree organization better later...

**Comment by hostilefork** [comment]
> 3533e8c has introduced a bug whereby no source files are found. 

Sorry if I messed something up, but FWIW it's working from here and finding bad eol-wsp's/etc.

**Comment by codebybrett** [comment]
NP, but that's a little weird it works for you but not me.  I reverted source-files-seq to my old code and it worked again for me.  I'll try to reapply your changes once I've got the rest done and see what I find.

**Comment by codebybrett** [comment]
I take it back. No problem with your changes. My build was inappropriate for running them.

**Comment by codebybrett** [comment]
This bug should be resolved by https://github.com/metaeducation/ren-c/pull/719
