### ISSUE TITLE
Assertion caused by ||

### ISSUE THREAD

**Issue by codebybrett** [metaeducation/ren-c#735]
The following causes an assertion failure:

    ||

**Comment by hostilefork** [comment]
Oh.... you accidentally used ONCE-BAR.  No one's thought about that since... when variadics were first made.  I won't say it's "fixed", but, changed here:

https://github.com/metaeducation/ren-c/commit/c17d8e25dac3f71e7dded65ff1841579fab3a95c

I also somewhat impulsively made a change I just thought of, which might be the "best of both worlds" option for conditional AND/OR.  The idea is that if you use a GROUP! on the right of the operator, that means you'll get a LOGIC! result.  And if you use a BLOCK! on the right of the operator, you'll get an ANY-VALUE! result (BLANK! or the last evaluated value).

     >> 1 or (2)
     == #[true]

     >> 1 or [2]
     == 1

     >> 1 and (2)
     == #[true]

     >> 1 and [2]
     == 2

Since the right hand is quoted and has to be a BLOCK! or a GROUP!, this gives you a source-level assurance of whether you're going to get a LOGIC! back or not.  This also means things can look a bit more normal with using OR as a "logic-driven-ELSE".  Compare:

        parse skip executable e_phoff [
            e_phnum [
                (mode: 'read) pos: program-header-rule
                (if p_offset >= offset [p_offset: p_offset + delta])
                (mode: 'write) :pos program-header-rule
            ]
            to end
        ] or [
            fail "Error updating offsets in program headers"
        ]

vs.

        unless parse skip executable e_phoff [
            e_phnum [
                (mode: 'read) pos: program-header-rule
                (if p_offset >= offset [p_offset: p_offset + delta])
                (mode: 'write) :pos program-header-rule
            ]
            to end
        ][
            fail "Error updating offsets in program headers"
        ]

I feel these little tweaks help with flow and reading comprehension.  When UNLESS comes first, it's like it's saying it's the most important thing...and it kind of overwhelms the PARSE--which is what's actually happening.  I feel similarly about the role of AND and OR being "in the middle" of conditionals instead of taking the forefront:

     if all [blah blah blah blah] [
         ...
     ]

vs.

    if blah blah and (blah blah) [
        ...
    ]

**Comment by codebybrett** [comment]
Yes parse ... or [fail ...] reads well.  Definitely an idiom I could get used to.
OR's group for logic, block for result looks good too.
