### ISSUE TITLE
Assertion failure in sys-context during ADD of wrong datatype

### ISSUE THREAD

**Issue by codebybrett** [metaeducation/ren-c#742]
The following causes an assertion to fail in sys-context line 284:

    add 1 [2]

**Comment by hostilefork** [comment]
Argh, this thing.  It's really just the same as:

https://github.com/metaeducation/ren-c/issues/311

Been on the agenda to figure out what the real mechanism should be...that assert has been a reminder to go do something about it.  But rather than have it crash, the issue can be the reminder.

Turned into an error here:

https://github.com/metaeducation/ren-c/commit/5a50029abd6cb0fb4bf0e3685ed3e9fbb4ee24f4
