### ISSUE TITLE
WHAT-DIR is incorrect in script.

### ISSUE THREAD

**Issue by dram** [metaeducation/ren-c#75]
In script, WHAT-DIR returns directory of the script instead of the directory where script lauched.

In REPL, WHAT-DIR works correctly.

**Comment by hostilefork** [comment]
> In script, WHAT-DIR returns directory of the script instead of the directory where script lauched.

This behavior is as Rebol2 and R3-Alpha do, so nothing new in the Ren/C branch.  

As for whether it's what it should do or not, that's another matter...and I'm sure a list of reasons why it should do one or the other would be welcome.  But for what it's worth, it is likely intentional and is how it has been.

> In REPL, WHAT-DIR works correctly.

It doesn't seem there's a comparison to be made with the REPL.  Note that if you `cd some-dir` and then say `what-dir` it will report the new directory, so there is an understanding that `what-dir` does change beyond the directory the interpreter was invoked in.

I would think the decision to make it that way is based on trying to establish a kind of predictable/local behavior.  So if you are going to make a script that does something to an arbitrary directory (vs. the one it expects to run in) that parameter is explicit.  I mention that because in trying to think of something like a `what-dir/launched-in` refinement...I wonder "what business of it is the running script what the launch directory of the original program was"?

*(This question came up recently for command line arguments...should an inner script you call have implicit access to the command line parameters of the outer script, or should they be invisible by default?  Isn't the directory the original script ran in kind of similarly a property it should be insulated from?)*

That's my leaning.  This isn't an area of my personal passion so you might survey what people on chat say.

**Comment by dram** [comment]
I think the demand to get the launch directory of a program is fairly common. For example, by running `/bin/ls`, user is more intended to list files in the current directory instead of `/bin/`.

Besides that, we can always get script directory from `system/script/path`, but we can not get the current directory if we can not get from `what-dir` or some other word.

**Comment by hostilefork** [comment]
You should be able to get the launch directory if you're the outermost script, but I'm not sure if a script you call should know unless it is told.  Or at least not sure if that should be the default.  But again, I'm probably not the person to ask.  Others would know better than I.

Perhaps it would make a good stackoverflow question of *how* to get the launch directory from a script, and that would provoke people into answering about it.

**Comment by dram** [comment]
I find that someone has already asked a similar [question](https://stackoverflow.com/questions/17760776/how-to-read-current-directory-from-rebol-script) in SO.

There is `system/options/path` which is exactly what I needed, so I'll close this issue.
