### ISSUE TITLE
trim/lines fails to remove ^M

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#781]
>> rebol/commit
== "8f0878b8cacf1b1a8047c8c95c6bd9a6eab2e1d2"

    `>> msg: trim/lines/tail input
    testing
    == "testing^M"`

Also input adds a ^M which is not seen in Atronix R3

**Comment by hostilefork** [comment]
I don't know that I consider this a problem with TRIM, as I consider baseline STRING!s in Rebol that have ^M in them to be generally "corrupt".  You shouldn't get them without asking, and if you do get them by asking they should stay corrupt unless you handle them specially.

*(so it's not bad for TRIM to have an option which lets you pass in character sets to trim with ^M in them, but you should be having to do that on purpose.)*

So from my point of view, the problem here is that INPUT gave back a ^M.  Should be addressed here:

https://github.com/metaeducation/ren-c/commit/e48223ad53979dd8676e793774c7b43c6c88adf5

**Comment by gchiu** [comment]
trim/with "test^M" "^M" removes the CR
