### ISSUE TITLE
module loading is broken

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#795]
````
>> do %test.r
Script: Version: Date:
== make map! [
    "a" 1
]

>> do <json>
Module: JSON Parser for Rebol 3 Version: 0.3.6.1 Date: 18-Sep-2015
ⓘ   Note: use WHY for error information
** Script Error: block did not return a value
** Where: all mixin? all case case load-module apply import either either _ do
** Near: [... mod 'options 'private ~~
    block? select mod ...]
** File: tmp-boot.r
** Line: 4991

>> do %test.r
** Script Error: invalid argument: 'error
** Where: lib-make make switch check-response switch take* any unless _ wake-up either while-not _ wait while-not sync-op else _ read if load _ do
** Near: [...
    lib-make :type :def ~~]
** File: tmp-boot.r
** Line: 7849
````

I get the same error when I try to do a local module, but the I can still use do afterwards.

I get the same error on linux x64 and arm.

**Comment by hostilefork** [comment]
The module code is beastly.  :-/  And actually, it has been a good testing ground for the TRY/null changes.  Basically, the more TRY you see popping up the more you can say that your code had no clear invariants.

Hopefully this will help, *though it won't patch the JSON module* ... which is still using TRY/EXCEPT vs. TRAP/WITH:

https://github.com/metaeducation/ren-c/commit/07726cbb7bfce13c484a337815c8a391aa611593

What we're going to have to do on some of these modules is decide if they want to live in the Rebol2/Red world or not.  I don't have a problem with the emulation, and that emulation needs to be easy and better (isolated modules can't use the `do <r3-legacy>` trick because they bind to lib, not the user context).

But TRY has been working well, it seems like the definite way forward.

    >> block: []                                   
    == []

    >> first block
    ;-- null result

    >> try first block
    == _

It is short and expresses well what you mean: to turn something that is prickly (but testable) into something less prickly.  You cannot SELECT out of a null, but you can SELECT out of a BLANK!, *and get a null back*.  So each time you make a step in an expression you have a chance to say you are willing to accept failure.

The balance is not 100%, but I believe it to be on the right track.

**Comment by IngoHohmann** [comment]
I confirm that with 07726cbb module loading works again for %file modules as well.
