### ISSUE TITLE
Corruption happening with read/lines

### ISSUE THREAD

**Issue by kealist** [metaeducation/ren-c#797]
e6df943e8bb69efd613e57b059582b8fc839c15e

Get some weird corruption happening when running:

    >> length-of read/lines %bens_cube.txt
    == 682

a file which has 720 lines.

I downloaded an older C++ debug build and `trace on` reveals:

```
>> trace on

>> length-of read/lines %bens_cube.txt
--> [anonymous]




<-- [anonymous] ==


...





 0: length-of


 : action! [value]





 1: read/lines





 2: %bens_cube.txt





--> read





--> [anonymous]





 0: case


 : action! [cases /all /only]





 1: [
    file? spec [
        name: pick [dir file] dir? spec
        spec: join-of [ref:] spec
    ]
    url? spec [
        spec: join decode-url spec [to set-word! 'ref spec]
        name: select spec to set-word! 'scheme
    ]
    block? spec [
        name: select spec to set-word! 'scheme
    ]
    object? spec [
        name: get in spec 'scheme
    ]
    word? spec [
        name: spec
        spec: []
    ]
    port? spec [
        name: port/scheme/name
        spec: port/spec
    ]
]





--> case





 0: file?


 : action! [value]





 1: spec


 : %bens_cube.txt





--> file?





<-- file? ==



true



-1: [
    name: pick [dir file] dir? spec
    spec: join-of [ref:] spec
]





 0: name:





 1: pick


 : action! [location picker]





 2: [dir file]





 3: dir?


 : action! [target]





 4: spec


 : %bens_cube.txt





--> dir?





 0: did


 : action! [optional]





 1: find


 : action! [series value /part limit /only /case /skip size /last /reverse /tail /match]





 2: "/\"





 3: last


 : action! [value]





 4: target


 : %bens_cube.txt





--> last





 0: if


 : action! [condition branch /opt]





 1: gob?


 : action! [value]





 2: value


 : %bens_cube.txt





--> gob?





<-- gob? ==



false



 3: [
    print {Caution: LAST on GOB! may not work, look over the code}
    wait 2
]





--> if





<-- if ==









 4: pick


 : action! [location picker]




Assertion failed!

Program: C:\Users\kealist\Documents\git\kealist\mse-proxy\r3-f75eaf6-debug.exe
File: ../src/core/d-eval.c, Line 124

Expression: not (f->flags.bits & DO_FLAG_FINAL_DEBUG)

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

[bens_cube.txt](https://github.com/metaeducation/ren-c/files/1997234/bens_cube.txt)

**Comment by hostilefork** [comment]
Thanks for finding/reporting this, it was not a particularly profound bug:

https://github.com/metaeducation/ren-c/commit/5cefc5543ed75724d2ed2fcb5537733689435447

We could use some test cases for this.  A big open question which I am reminded of looking at Split_Lines() is how to pick a good future-forward way of handling CR and LF.

What Rebol has been doing is trying to gloss over CR LF issues by making the CRs disappear.  This makes strings easier to handle in things like PARSE because you don't have to worry about CR LF, or just CR, or various malformed mixtures...each line break is one, uniform character.  But I think that when you pretend something is not there you are just causing problems.  People get mad if they read a file and write it out and don't get back what they put in.

My inclination is that files with CR in them be regarded as a foreign file format, and that the baseline system refuse to read them without some kind of codec use.  So utf8-cr-lf would be a special kind of loader, and you'd have to invoke it explicitly.  It would not be sloppy by default, so if you have some lines that are just CR or just LF or any combination, it would error.  You would have to use other options to accept a non-uniform CR LF file.

Then when you save, it would notice if any CR managed to get introduced into a string, and refuse to write it out.  Even if you tried to use the utf8-cr-lf codec to save, it would expect the string you are saving to only have LF in it.

The question is how to get that all started.  Just something to be thinking about.
