### ISSUE TITLE
fib.r demo fails under windows

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#800]
<pre>
>> do %fib.r
Script: Initial test for user natives by @ShixinZeng Version: Date:
Assertion failed!

Program: C:\Users\Graham\Documents\rebol\r3-2f7d52f-debug.exe
File: ../src/include/sys-array.h, Line 422

Expression: VAL_TYPE(v) == REB_0_REFERENCE or ANY_ARRAY(v)

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
</pre>

**Comment by hostilefork** [comment]
I'd never seen the fib.r demo ever work on Windows (and it certainly wouldn't have been able to work on any machine other than the one that built it).

But this issue should now be fixed.  There is also code to pack up some of the necessary redistributables (header files and libs) to do a compilation on Windows, that makes a zip file on Travis.

**64-bit debug build**

https://s3.amazonaws.com/metaeducation/travis-builds/0.3.40/r3-1aae0ad-debug.exe
https://s3.amazonaws.com/metaeducation/travis-builds/0.3.40/r3-1aae0ad-debug-tcc-encap.zip

**32-bit release build**

https://s3.amazonaws.com/metaeducation/travis-builds/0.3.1/r3-1aae0ad.exe
https://s3.amazonaws.com/metaeducation/travis-builds/0.3.1/r3-1aae0ad-tcc-encap.zip

**Instructions**

In order to test [fib.r](https://github.com/metaeducation/ren-c/blob/master/tests/misc/fib.r), you will need to unzip the "encap" data into a directory somewhere (e.g. "C:\Projects\tcc-encap-32\" or "C:\Projects\tcc-encap-64\").  You then need to either set an environment variable CONFIG_TCCDIR to the directory, or in %fib.r specify it as a `runtime-path`.

The `runtime-path` may be in local file format (as a TEXT! string) or in Rebol FILE! format.
