### ISSUE TITLE
STRING! unbound in modules

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#824]
`Rebol [Type: module] string!`

=> error: string! word is not bound to a context

NOTE: no error with `integer!` instead of string!

**Comment by giuliolunati** [comment]
Ok, string! is an alias for text!

**Comment by hostilefork** [comment]
> string! is an alias for text!

Yes--if you didn't catch why that is, explained here: [STRING! => TEXT!](https://forum.rebol.info/t/text-vs-string/612).

Unfortunately (or fortunately) the way modules work isn't importing the [compatibility tweaks in %sys-base.r](https://github.com/metaeducation/ren-c/blob/a449d3278f0d17a993f33634780f22743bd5340a/src/mezz/sys-start.r#L55).  That's because those changes are applied to the user context, and MODULEs get their own copies of LIB (not deep copies, just the list of what the words are assigned to).

As more work is being done on the modules, I want to see things like this addressed...and even have a fairly full Rebol2/Red compatibility mode.

It's just not there yet.
