### ISSUE TITLE
console errors on q

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#827]
** HOST-CONSOLE ACTION! ITSELF RAISED ERROR
** SAFE RECOVERY NOT LIKELY, BUT TRYING ANYWAY
** REVERTING TO DEFAULT SKIN
[#host-console-error]
** Error: BOUND? and BIND? have been replaced by `BINDING OF`.
** Where: lib-make make switch fail bound? if _ _ entrap
** Near: [...
    lib-make :type :def ~~]
** File: tmp-boot.r
** Line: 7778

This line needs to be changed to **binding of**.

https://github.com/metaeducation/ren-c/blob/f2a4fa199eb341315d856563a50aee040855e49f/src/os/host-console.r#L635

**Comment by hostilefork** [comment]
Hrmmm.  Y'know...I actually think that BOUND? is probably a good name for the operation of testing for a null binding, and giving back a LOGIC!.  It just wasn't good for coming back with a context...since it ends in `?`... so it got aggressively culled.  But here we see a perfectly reasonable use of it.

So I think the right thing to do here is:

    bound?: chain [specialize 'reflect [property: 'binding] | :value?]

It seems that BIND? was the more common thing for getting contexts before, so I don't think any real warning of "BOUND? now returns a LOGIC!" is necessary.

**Comment by hostilefork** [comment]
Ok, done...

https://github.com/metaeducation/ren-c/commit/f7b79152e557c78dd3075c161e8bc49b02b917ca

Thanks for reporting/PR-ing it!
