### ISSUE TITLE
READ %dir/ outcome omits trailing slashes

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#838]
Old behaviour was `read %dir/ => [%file.ext %subdir/ ... ]` , now is  `read %dir/ => [%file.ext %subdir ... ]` that make invisible  the type (file / dir) of entries. I wish old behaviour.

**Comment by hostilefork** [comment]
I get the slashes on both Linux and Windows, so this is likely a variance on Android.

If it's a recent behavior change, it likely relates to this:

https://github.com/metaeducation/ren-c/commit/00a4cabff9b042cf498d008f56e3d01e83347deb

The issue is that apparently some APIs (perhaps Android's file system API) do not want you to put a trailing slash on when you ask about the properties of something (such as "tell me is this a directory or not").  But if you omit the trailing slash from "/", you have just an empty string, which the API does not like.

So sounds like it needs another tweak.  Perhaps add back in the removal of trailing slashes, and then specifically override the empty string to assume it's just "/"?

https://github.com/metaeducation/ren-c/blob/master/src/os/posix/dev-file.c#L177

**Comment by hostilefork** [comment]
I assigned this to you since it doesn't reproduce for me.  But let me know if you don't see what I'm talking about...

**Comment by giuliolunati** [comment]
Surprisingly enough, the guilty commit isn't 00a4cab, but bc3dda1 !?

**Comment by hostilefork** [comment]
Hmmm?  Ok, well that's interesting.  :-/  What are the compiler command-line switches you've got in effect?

**Comment by giuliolunati** [comment]
I downloaded Travis builds from amozonaws....

Il sab 4 ago 2018, 19:50 Brian Dickens <notifications@github.com> ha
scritto:

**Comment by hostilefork** [comment]
If you change `rebLogic(file_req->modes & RFM_DIR)` to `rebLogic(did (file_req->modes & RFM_DIR))`:

https://github.com/metaeducation/ren-c/blob/8af4214b985bf7323167b959727592d7b3f842c2/src/os/posix/dev-file.c#L313

and I guess same for `rebLogic(req->modes & RFM_DIR)` to `rebLogic(did (req->modes & RFM_DIR))`:

https://github.com/metaeducation/ren-c/blob/8af4214b985bf7323167b959727592d7b3f842c2/src/os/posix/dev-file.c#L379

Does that change anything?

It is going to be bad if the API client does not build with the same settings that the API was built with, in terms of whether it's using an `#include <stdbool.h>` or not.  There could be misunderstandings, just like with uninitialized variables:

https://markshroyer.com/2012/06/c-both-true-and-false/

So I'd expect a problem if inside the API, it was built thinking it got a bool...in which case the `did` (!!) would likely be optimized out as a no-op.  But I don't understand why there'd be a problem if both the API client and API implementation are using the same definition of a bool.  This is the fake one:

https://github.com/metaeducation/ren-c/blob/8af4214b985bf7323167b959727592d7b3f842c2/src/include/reb-c.h#L532

**Comment by giuliolunati** [comment]
Got warning:
`In file included from ../src/include/reb-host.h:35:0,
                 from ../src/os/posix/dev-file.c:59:
../src/os/posix/dev-file.c: In function 'Open_File':
prep/include/rebol.h:425:34: warning: passing argument 1 of 'RL_rebR' makes pointer from integer without a cast
                     #define rebR RL_rebR
                                  ^
../src/os/posix/dev-file.c:379:22: note: in expansion of macro 'rebR'
             "wild:", rebR(did(rebLogic(req->modes & RFM_DIR))), // !!! necessary?
                      ^
In file included from ../src/include/reb-host.h:35:0,
                 from ../src/os/posix/dev-file.c:59:
prep/include/rebol.h:347:49: note: expected 'struct Reb_Cell *' but argument is of type 'int'
         EMSCRIPTEN_KEEPALIVE RL_API const void *RL_rebR(REBVAL *v);`

Then segfaults when booting.

**Comment by giuliolunati** [comment]
Sorry.

You solved in 798453e
