### ISSUE TITLE
Redefine MODULO so MOD is its infix form, Vary behavior by refinement

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#843]
MOD -3 -2 --> -3

**Comment by giuliolunati** [comment]
I'm decidedly  for `mod: enfix tighten modulo`

About signs, some semi-random thoughts:

1) obviously `x - (x mod d) / d` must be integer

2) I want `abs ((x mod d) - (y mod d))  < abs d` i.e. the range of the map `x -> (x mod d)` has to be minimal.

3) [2] implies that such a range can't be symmetrical around 0, so better to state it must be non-negative or non-positive

4) So my proposal is: `modulo x d` is ever non-negative, `remainder x d` has the same sign as `d`

E.g:

 `(-3 mod 2) = (remainder -3 2) = 1`

while

`(3 mod -2) = 1` but `(remainder 3 -2) = -1`


4) Then 



3)

**Comment by hostilefork** [comment]
Here is some more reading, from Red issues:

https://github.com/red/red/issues/2997 (discusses rounding modes, `fmod`)
https://github.com/red/red/issues/2708 (regarding result type matching input type, e.g. at 0)
https://github.com/red/red/issues/1515 (area to look at for bugs in extreme values)

Some of their tests for modulo can be found with this search:

https://github.com/red/red/search?q=modulo&unscoped_q=modulo

> I'm decidedly for `mod: enfix tighten :modulo`

(We might also consider `rem: enfix tighten :remainder`)

This is the main thing I want.  But it would be good before making changes to ensure that the decisions aren't losing any functionality.  As I've said, refinements are our new tool for getting there, since there is a way of calling infix with refinements now.

So if you can take this all into account, integrate them into the tests, try not to wind up leaving out any code that's there today...I'm happy with whatever you decide!

**Comment by giuliolunati** [comment]
What if REMAINDER was implemented as mezzanine, based on DIVIDE and ROUND?
Obviously, loss in performance; roughly 3 times for numbers, 10 times for pairs. But much less C code.

**Comment by giuliolunati** [comment]
Finally, I decided to not touch REMAINDER. MOD was bugged and its difference from MODULO apparently not interesting.

ac52a71d defines MOD as the enfix form of MODULO

**Comment by hostilefork** [comment]
> MOD was bugged and its difference from MODULO apparently not interesting.

I'll take your word for it (that's why I wanted you to look at it).

Works for me!

**Comment by hostilefork** [comment]
*Okay, sorry I lied, I'm going to get involved despite saying I wouldn't...mostly because [tests broke](https://github.com/metaeducation/ren-c/blob/master/tests/math/mod.test.reb) and then I checked with Wolfram Alpha and it looks like the old answers matched.  Don't be mad!  :-)*

> So my proposal is: modulo x d has the same sign as d (while remainder x d has the same sign as x / d)

Looking into it, it seems your definition *almost* agrees with Clojure/Haskell:

*Haskell and Scheme offer two functions, remainder and modulo – PL/I has mod and rem, while Fortran has mod and modulo; in each case, the former agrees in sign with the dividend, and the latter with the divisor.*: https://stackoverflow.com/a/28027235/211160

Would it be okay to go with their choice?

---

Something about the tests is that if we compare not just Haskell/Clojure, but also Wolfram Alpha, and Google.  Both of which say -3 mod -2 is -1.  :-/

http://www.wolframalpha.com/input/?i=-3+mod+-2
https://www.google.com/search?&q=-3+mod+-2

Additionally they believe that -562949953421312.75 mod 1 is 0.25.  By just setting MOD to enfix MODULO it seems to lose something a lot of people believe in.

If anything, it looks like this commit may be backwards, that MOD was the one that was right and MODULO is the one no one else knows about or agrees with.  Is there a reason not to flip it the other way?

**Comment by giuliolunati** [comment]
@hostilefork let me explain. 
MODULO tries to detect when the estimated error on result is >= of result itself, only in that case it rounds to integer returning 0. So difference with Wolfram seems due to different precision.

**Comment by hostilefork** [comment]
> MODULO tries to detect when the estimated error on result is >= of result itself, only in that case it rounds to integer returning 0. So difference with Wolfram seems due to different precision.

Hmmm, I see.  Interesting.  562949953421311.25 is from the %mod.test.reb.  I do see that Clojure seems to think this particular case is 0.25, where Rebol says 0.0:

    Clojure 1.8.0
    Java HotSpot(TM) 64-Bit Server VM 1.8.0_91-b14
    user=> (mod (double 562949953421311.25) (double 1))
    => 0.25

Take the last 1 off before the decimal point, and Rebol modulo also says 0.25:

    >> modulo 56294995342131.25 1  
    == 0.25

But add a 1 before the decimal point instead, and Clojure will say 0.0 too.

Getting micro-technical for a moment, Clojure says of the two numbers:

    (double 562949953421311.25)
    => 5.6294995342131125E14
   (double 5629499534213111.25)
    => 5.629499534213111E15

So adding the decimal digit is enough to push it over bitwise into no longer having the resolution for the .25 at that point.  Abstractly speaking, it seems like it may have the information to know in a case Rebol is reporting as 0.0, but if this really is just some edge case fringe behavior I'm very uninterested in whether it's optimal or not.  :-)

> I think this rounding-to-zero behaviour is better than returning a random result, due to approximation.

It looked like a lot of tests had started failing, but I guess it looks like maybe these tests were picked specifically to be on an edge of distinction between MOD and MODULO.

But if you wouldn't mind going over the tests and lining up the results are acting as you would expect, that would be helpful.  You suggested `(3 mod -2) = -1` which is consistent with the other sources but the committed code has `(3 mod -2) = 1`.

https://github.com/metaeducation/ren-c/blob/master/tests/math/mod.test.reb
https://github.com/metaeducation/ren-c/blob/master/tests/math/modulo.test.reb
https://github.com/metaeducation/ren-c/blob/master/tests/math/remainder.test.reb

Beyond the sign issues (and maybe the simpler/same rule for remainder as Clojure/Haskell), maybe making the tests make sense is as simple as knocking a digit off of those cases??

**Comment by giuliolunati** [comment]
About sign: I tried to be conservative, but if others agree with my humble opinion, then worst to change.

About precision, note that "MONEY" (I hate that name!) works in much higher precision,  so `$-562949953421312.75 mod $1= $0.25`, and you may other 9 figures!

**Comment by hostilefork** [comment]
> Better let the user decide.

Sounds good.  For the sake of arguing that we didn't throw anything out that was there before...can the "almost zero" detection be put under a refinement?  MOD/ADJUSTED might be better than MOD/CHECKED...

**Comment by giuliolunati** [comment]
Well, if so maybe worth to set `MOD: enfix tighten specialize :MODULO [adjusted: true]`

**Comment by giuliolunati** [comment]
Or better other way around, in line with old behaviour: `MOD: enfix tighten specialize :MODULO [STRICT: true]`, and if the user *trusts* the 'almost zero' detection can use MODULO

**Comment by hostilefork** [comment]
Note: Was resolved with `mod: enfix tighten :modulo` and near-zero behavior isolated to /ADJUSTED refinement...

https://github.com/metaeducation/ren-c/commit/700c646231fb29e7ad137bf5d63df645e8054197
