### ISSUE TITLE
clipboard extension not included by default in Windows build

### ISSUE THREAD

**Issue by Oldes** [metaeducation/ren-c#849]
As I was not able paste my code with multiline binary into console (see https://github.com/metaeducation/ren-c/issues/775), as a workaround I tried to read the code from a clipboard, but it looks that clipboard scheme is not working.

```
>> read clipboard://
** Script Error: get requires source argument to not be null
** Where: all _ read _
** Near: [... as word! name ~~]
** File: tmp-boot.r
** Line: 4552
```
```
**    Platform:  Windows win32-x86                                      **
**    Build:     28-Jul-2018/0:44:46                                    **
**    Commit:    1f77812a6654aaf68cfc8af685d209d638f4e6cf               **
```

**Comment by hostilefork** [comment]
The clipboard scheme exists as an extension, but it only works on Windows.  Hence it is disabled (-) in the default config:

https://github.com/metaeducation/ren-c/blob/master/make/default-config.r#L24

You can locally change that to a **+ Clipboard _**.  But because no one is really working on the design of the build system, an enablement strategy which enables extensions by default based on what platform you're building on doesn't exist yet.  It's a desirable thing, but it just doesn't have super high priority right now, so manually turning it on is the way for the moment.

**Comment by giuliolunati** [comment]
See [this commit](
https://github.com/metaeducation/ren-c/commit/bb988fd4aa1d8e5a0174c83b1c321a1999b15c92).
You can run `r3-make make.r .... extensions: "clipboard +"`

Il dom 2 set 2018, 17:37 Brian Dickens <notifications@github.com> ha
scritto:

**Comment by hostilefork** [comment]
I stand corrected...awesome!
