### ISSUE TITLE
Bad naming "any-scalar!"

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#861]
PAIR! and TUPLE! belong to ANY-SCALAR!, but seems to me they're no scalars at all.
My proposal is:
`any-scalar!: make typeset! [integer! decimal! percent! char! money! time!]`
and
`any-vector!: make typeset! [vector! pair! tuple!]`

**Comment by MarkEye** [comment]
Comment 1: Why isn't `date!` a scalar?
Comment 2: A vector (like any series) has variable length. Pairs are always of length 2, and tuples are always of length 10. It is actually just a shortcut that you can access their components via integers -- pair component access works perfectly well using the /x and /y refinements, and theoretically tuples could use /x /y /z /t /u /v /w /q /r and /s just as easily -- and is done by a completely different mechanism.
Comment 3: Another way of looking at it is that what makes scalars scalars is not that they are unitary in structure (most have components, e.g., time/hour) but they are fixed in size (they are always exactly one Rebol storage unit).
My vote is to close this issue, it is by design and it is unnecessary (and potentially confusing) to "fix" it.

**Comment by giuliolunati** [comment]
@MarkEye to 1: dunno, it's the current definition

**Comment by giuliolunati** [comment]
`scalar` = `not array` ?
