### ISSUE TITLE
PRINT 3 / 2

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#865]
*Error: print does not allow decimal! for its line argument*

The same for `print (3 / 2)`

**Comment by giuliolunati** [comment]
Sorry, my fault!

**Comment by hostilefork** [comment]
Hopefully you caught the reasoning behind the change.  If we let people get too comfortable saying `print value` for ANY-VALUE!, then it becomes risky that they will not realize they will be executing code if `value` unexpectedly becomes a BLOCK! one day.

By limiting it so that people do not think you can pass in ANY-VALUE!, they will say `print [3 / 2]` instead.  This will reduce the risk:

https://forum.rebol.info/t/limiting-print-to-block-text-perhaps-blank-to-opt-out/855
