### ISSUE TITLE
dump can't be adapted

### ISSUE THREAD

**Issue by transcend3r** [metaeducation/ren-c#881]
```
>> d1: adapt :dump [value: "test"]
== make action! [[:value dump-one: dump-val: clip-string: item: set-word: result: return:] [...]]

>> dump "test"                     
--- "test" ---

>> d1 "test"
** Script Error: d1 does not allow text! for its value argument
** Near: [d1 ~~ "test"]
** Line: 1
```

**Comment by hostilefork** [comment]
You must not be running a debug build (?) as this produces an assert.  I've fixed the assert.

However, the main problem is that DUMP is a variadic function (it takes an **[any-value! <...>]**, not an **[any-value!]**).  So it expects a VARARGS!, you'd have to say `value: make varargs! ["test"]`.

But we can do better than that.  This was initially done so that it could perform tricks like:

     >> dump long-variable-name: 1 + 2
     --- long-variable-name: 3 ---

It peeks at the first argument, remembers the name, and then does one unit of evaluation of the varargs if it's a SET-WORD!.

But we could make it easier to specialize and adapt by having the first parameter be fixed as quoted, then the varargs as the second parameter.  If you're specializing you'd leave that blank, and it would be okay...just don't specialize with a SET-WORD!, because then it will expect there to be something in the varargs.  *(As it's a specialization, each time you call it it would consume more out of that same varargs!  Not something you *usually* want to do--especially with how easily frame-based varargs expire--but you might get use out of it in some wacky cases.)*

I've gone ahead and fixed up some of the asserts, though function compositions and various other features have friction with invisibles.  They're issues that need to have carefully thought out answers, and I prefer to leave the asserts at any edge points where things haven't been thought out than to make a random incorrect decision.  But at least ADAPT and SPECIALIZE should work on invisibles.

Your case should work now:

    >> d1: adapt :dump [value: "overwritten"]

    >> d1 "passed in"
    "overwritten"

I've moved the DUMP implementation into its own mezzanine file.  Which should make it easier for you to work on it, as I'm going to appoint you the Czar of the DUMP!  :-P

https://forum.rebol.info/t/taking-a-thrilling-tour-through-the-dump/909
