### ISSUE TITLE
FIND on MAP! quits interpreter

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#893]
Using FIND to determine if a given key exists in a MAP! quits the interpreter (shell return code #255)

Example:

    find make map! [foo 0] 'foo

Commit: dcda199
Platform: 2.40

**Comment by hostilefork** [comment]
Fixed in https://github.com/metaeducation/ren-c/commit/d423bb63e421650810127c1dc1e4a9d603f7c54d

Thanks!  Keep those reports coming.  :-)

*(Note that you're not getting more output than that because you're not running a debug build.  You can add asserts to your build configuration--it can be passed to make.r with `debug=asserts` or alternate syntax `debug: asserts`.  That will slow things down somewhat, but give more informative messages, and also runs more internal diagnostics to be noisy about catching things that are wrong.)*
