### ISSUE TITLE
Crash on make map! ['a 1]

### ISSUE THREAD

**Issue by IngoHohmann** [metaeducation/ren-c#914]
Ren-c crashes on

    make map! ['a 1]

There's no error message, ren-c just stops

commit 35418a15
on linux

**Comment by giuliolunati** [comment]
R3-debug:

`C Source File ../src/core/s-crc.c, Line 382, Pointer 0x0`

**Comment by hostilefork** [comment]
MAP!s were not adjusted for dealing with generalized quoting on keys.  I did that, as well as cleaned up some more of the generalized map uncleanliness inherited from R3-Alpha...

https://github.com/metaeducation/ren-c/commit/0d014aa68e2ce886a6d4d087fccbd89a3c76a928

*I'm not sure if the rules on non-strict-equality for quoting are going to stick.*  But for the moment, since in R3-Alpha **(first ['a]) = (first [a])**, that's been kept.  It's been extended to where all quoting levels of lax-equal values are lax-equal.

This means if you put both a word and a lit-word with the same lax inequality as keys of a map, they will conflict unless you use SELECT/CASE to get the exact one you mean out.  Hence it is your job to canonize them via TO WORD! when putting them in if you mean for them too be the same thing and not need the /CASE refinement.

        b2: copy lit ''[x y]
        b4: copy lit ''''[m n o p]
        m: make map! compose [
            a 0 'a 1 ''a 2 '''a 3 ''''a 4
            ((b2)) II ((b4)) IIII
        ]
        true

    (0 = select/case m lit a)
    (1 = select/case m lit 'a)
    (2 = select/case m lit ''a)
    (3 = select/case m lit '''a)
    (4 = select/case m lit ''''a)

    ((trap [select m lit a])/id = 'conflicting-key)
    ((trap [m/(lit a)])/id = 'conflicting-key)

    ((trap [select m lit ''''a])/id = 'conflicting-key)
    ((trap [m/(lit ''''a)])/id = 'conflicting-key)

    ('II = m/[x y])
    ('IIII = m/[m n o p])

    ((trap [append b2 'z])/id = 'series-auto-locked)
    ((trap [append b4 'q])/id = 'series-auto-locked)

The initial MAKE MAP! is "synonym-key preserving", as if you had inserted everything with /CASE applicable.
