### ISSUE TITLE
Strange behavior of ' help '

### ISSUE THREAD

**Issue by no-e-in** [metaeducation/ren-c#919]
In Ren-C (commit 9b115f3 on windows7 ):

```
>> help "collect"
Found these related words:
   collect         action!   [ {Evaluate body, and return block of values ...
   collect-block   action!   [ body ]
   collect-lines   action!   [ body ]
   collect-text    action!   [ body ]
   collect-with    action!   Evaluate body, and return block of values col...
   collect-words   action!   Collect unique words used in a block (used fo...
```

COLLECT-WITH and COLLECT-WORDS look reasonable, but COLLECT shows its description molded as a string in a BLOCK!, while the COLLECT-BLOCK, COLLECT-LINES, and COLLECT-TEXT just say `[ body ]`.

**Comment by hostilefork** [comment]
When ACTION!s are specialized (adapted, chained, enclosed, etc.) they by default inherit the description of the thing whose interface they are deriving from (head of chain, etc).  It doesn't actually copy the description, but HELP has to "dig" to find it from the inheritance chain in the META OF information.

That chain was being consulted for plain HELP of an ACTION!, but here it wasn't going deeper...and doing some weird molding when it couldn't find any description.  I've changed it so that these descriptions now use the same "digging" process that HELP does.

@IngoHohmann also went in and gave these COLLECT variants some extended descriptions.

If you haven't read about COLLECT-LINES and COLLECT-TEXT, they're actually rather cool:

https://forum.rebol.info/t/collect-lines-an-adaptation-story/945

Thanks for the report, and please do feel very free to get involved...as you can see, improving this kind of userspace stuff is something anyone can do!
