### ISSUE TITLE
`deline` crashes silently

### ISSUE THREAD

**Issue by kealist** [metaeducation/ren-c#923]
A couple cases where deline crashes silently (Non-debug windows build):

1.  Building up a string:

`a: copy #{60} repeat i 27 [append a a print [length-of a] deline to-text a]`

2.  Reading a text with CRLF:

`deline to-text read %u-zlib.c`

**Comment by hostilefork** [comment]
Thanks for sticking with it and finding this!...

Even if it gets fixed, that won't help the bootstrap executable.  There may need to be custom code in %make/tools/bootstrap-shim.r to do a read and manually deline.

**Comment by hostilefork** [comment]
File under *"reasons why you really shouldn't be programming in low-level C unless you have to"*...simple bug!

https://github.com/metaeducation/ren-c/commit/d3b66112f061bb3ae4b37ff0c4608f2959313cfe

Will have to get a new bootstrap executable out for other reasons, but I'm wondering if there's somewhere better we can put it than in the make directory.  :-/

**Comment by hostilefork** [comment]
It's a good thing I didn't close this bug earlier, because your test of inserting-binaries-into-themselves [exposed a bug introduced by UTF-8 Everywhere](https://github.com/metaeducation/ren-c/commit/d959ab8e20fe3383f01cfdbb6058aa28ae134972)!

But, I've now gone ahead and [changed bootstrap-shim to DELINE with REPLACE/ALL](https://github.com/metaeducation/ren-c/commit/11e3c8e7cf1e03de60086d6505bb5d1432c4d678), so this can be closed.
