### ISSUE TITLE
Crash in PARSE encountering an unset word

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#934]
This will crash a fresh interpreter session:

```rebol
parse "a" [foo]
```

Shell return code is 255.

This is likely unrelated, but my terminal prompt (MacOS) will conceal keystrokes following the crash.

**Comment by hostilefork** [comment]
Pertains to an issue of nulls in arrays.  The debug build wouldn't crash (one often dumps nulls in the debugger), but it would display an ugly "You're trying to mold a null, and you can't" message...and the non-crashing may have led to it being glossed over as not being a problem. 

But the release build crashed hence bringing more attention to the problem.  Which is good.  But also, please be sure you're running debug builds if you can.  They have much more diagnostics and can catch anomalies in your every day usage that might go unnoticed otherwise.  And the information is better for bug reports.

Fixed here:

https://github.com/metaeducation/ren-c/commit/cb4f301d33409f2355762872720e790e8dccade2

> This is likely unrelated, but my terminal prompt (MacOS) will conceal keystrokes following the crash.

That happens a lot when terminals crash abnormally.  Address Sanitizer crashes always do it.  But we may be able to do some things to make it happen less often:

https://github.com/rebol/rebol-issues/issues/2360

**Comment by rgchris** [comment]
Is there a flag within the interpreter that will tell me if I've built said interpreter with debug option?
