### ISSUE TITLE
KEEP (Parse) does not work with SKIP

### ISSUE THREAD

**Issue by rgchris** [metaeducation/ren-c#935]
I get an error when I try `keep skip` together:

```
>> parse "abcd" [collect stuff [some [keep skip]]]
** Script Error: PARSE - invalid rule or usage of rule
** Where: subparse subparse subparse parse console
** Near: [keep ~~ skip]
** Line: 1
```

It'll work if I wrap `skip` in a block:

```
>> parse "abcd" [collect stuff [some [keep [skip]]]]
== ""

>> stuff
== ["a" "b" "c" "d"]
```

**Comment by hostilefork** [comment]
This was a weakness in general of R3-Alpha rule processing.  As discussed in chat, it's a back-burner process to improve such things...but...since it fit into some of [what I was doing anyway](https://github.com/metaeducation/ren-c/commit/fe26efa9cbd0c717840e5ed639a3de894331aea0), this one wasn't difficult to add after that...

Added here:

But like I say--the test writing and general userespace-test-suite-improving is in your court!  One thing that might be cool is that since Red names their tests, to make a parallel directory structure in Ren-C with files for their tests, listing the names of the ones that aren't expected to pass.  Then fetch the test from URL and run a simple emulation:

That would give the advantage of being able to run:

https://github.com/red/red/blob/873a756c98164da736ffebda298b46f040644c25/tests/source/units/parse-test.red

But without having to by hand convert those tests...just make annotations of the ones that are failing on purpose vs. bugs.
