### ISSUE TITLE
Problem with 'help collect' - regression

### ISSUE THREAD

**Issue by lkppo** [metaeducation/ren-c#954]
In ren-c on Debian with commits 0a29a2f and 5dfb2f7, maybe before.

>> help collect 
USAGE:
    COLLECT body 

DESCRIPTION:
    Evaluate body, and return block of values collected via KEEP function.
    Returns empty block if nothing KEEPed.
    COLLECT is a chained ACTION!

RETURNS: [<opt> block!]
    result block, or null if no KEEPs (prevent nulls with KEEP [])

ARGUMENTS:
** Error: ENSURE failed with argument of type tag!
** Where: fail _ ensure for-each print-args if help console
** Near: [
    fail [
        "ENSURE failed with argument of type"
 ...

**Comment by hostilefork** [comment]
Oops.  Mistaken use of splicing ((...)) instead of (...) for "COMPOSE/ONLY" behavior.

https://github.com/metaeducation/ren-c/commit/49203c18e0482d027abbfe314ae16bda29df5c9e

All the COMPOSE/ONLYs had to be changed, looked like that one went the wrong way.

Relates to:

https://forum.rebol.info/t/the-even-more-powerful-compose/1101

**Comment by lkppo** [comment]
Tested. It's ok.
