### ISSUE TITLE
do <something> fails with source error

### ISSUE THREAD

**Issue by gchiu** [metaeducation/ren-c#973]
Look up table is here https://github.com/r3n/renclib/blob/master/userutils.reb

>> do &lt;latest-of&gt;
** Script Error: source has no value
** Where: all _ do console
** Near: [... | file? source ~~]

but the direct link works

do https://raw.githubusercontent.com/gchiu/rebol-misc/master/latest-of.reb

using the replpad

**Comment by hostilefork** [comment]
Two things.

Main thing in your case is a typo.  `lastest-of` instead of `latest-of`

Second thing is the lack of a good error message.  That's because the ELSE is on the wrong clause, it's on the load instead of the SWITCH.  Needs a GROUP!:

https://github.com/metaeducation/ren-c/commit/504bd074456e00b7fdadca2d67aa3c6f8b5533d9
