### ISSUE TITLE
Make Unzip work for Zip Files Created via Stream

### ISSUE THREAD

**Issue by giuliolunati** [metaeducation/ren-c#978]
See [tests/string/compress.test.reb](https://github.com/metaeducation/ren-c/commit/c3f7744e46603cbeb2756f490cbef910449bed29)

The file is [test.docx](https://raw.githubusercontent.com/metaeducation/ren-c/master/tests/fixtures/test.docx)

**Comment by hostilefork** [comment]
I looked into this.  The problem is that when Zip files are being created via a pipe, where all the compressed data isn't being put into memory, they cannot patch up the bytes in headers they write.  They can only add more data to the stream.

So if a certain bit is set, the "local file header" contains 0 for the compressed size, uncompressed size, and CRC:

https://github.com/metaeducation/ren-c/commit/1212792b4998fedcfd38c538f1133dfa8c09278c

They then say they put the data in a descriptor after the compressed data.  But if you don't know how big the compressed data is, what good is that?

I gather that what you are probably (?) supposed to do is use the central directory entry instead.

Is this something you think you could work on?  There is a helpful tool called `zipinfo` that comes in handy for messing with this:

https://www.systutorials.com/docs/linux/man/1-zipinfo/

It's good to have some kind of hex dumper also.

**Comment by giuliolunati** [comment]
Sure what you pointed to is an issue that must be addressed. I did it some time ago, but that didn't solve the problem...

**Comment by giuliolunati** [comment]
I think I worked it out...

**Comment by hostilefork** [comment]
> Check please

Well, it took me a couple of years :-) but I finally got around to going over this!

What I did was convert the code to UPARSE.  I think it is really pretty neat how it's coming along...the commit message explains the gist:

https://github.com/metaeducation/ren-c/commit/83de33e9e8fa40db3f8df8d65dccc47ddedc0e78

It's a very powerful idea for parse to be able to have rules "synthesize" new values, and to have a BLOCK! rule give its last result.  There is also ELIDE in UPARSE...plus even groups of DO code that vanish will leave the last parse result!

    >> uparse "a" [
          x: [
              ["a" (<A>) | "b" (<B>)]
              (comment "GROUP! vaporizing")
          ]
       ]

    >> x
    == <A>

If you have any code that you can try and convert to UPARSE it would be helpful to get the feedback.  It has a /VERBOSE option for feedback, and also a /FARTHEST option so you can find out how far in the parse it got before it fails...so that can help with debugging.  There is no ANY at the moment, just WHILE and SOME...and I'm trying to see how that works out.
