### ISSUE TITLE
Windows build produce a broken binary (config: ../configs/mingw-x64-c++.r debug: asserts)

### ISSUE THREAD

**Issue by lkppo** [metaeducation/ren-c#986]
$../prebuilt/r3-windows-x86-8994d23.exe  ../make.r config: ../configs/mingw-x64-c++.r debug: asserts
$./r3.exe
C Source File ..\src\core\b-init.c, Line 75, Pointer 000000000077f170
At evaluator tick: 1
Rebol Internal Error
If you need to file a bug in the issue tracker, please give thorough
details on how to reproduce the problem:

    https://github.com/metaeducation/ren-c/issues

Include the following information in the report:

size of REBVAL is not sizeof(void*) * 4

**Comment by lkppo** [comment]
Same things with args :

../prebuilt/r3-windows-x86-8994d23.exe ../make.r config: ../configs/mingw-x64-c++.r debug: normal

**Comment by lkppo** [comment]
Same things with args :

../prebuilt/r3-windows-x86-8994d23.exe ../make.r config: ../configs/mingw-x64.r debug: normal

**Comment by lkppo** [comment]
The binary is ok for:

../prebuilt/r3-windows-x86-8994d23.exe ../make.r config: ../configs/mingw-x64.r debug: none

and

../prebuilt/r3-windows-x86-8994d23.exe ../make.r config: ../configs/mingw-x64-c++.r debug: none

**Comment by hostilefork** [comment]
What is the specific version of the compiler you are using, and link to where to install it?

**Comment by lkppo** [comment]
I use https://cygwin.com/index.html (https://cygwin.com/setup-x86_64.exe) with package mingw64-x86_64-*.

https://cygwin.com/packages/package_list.html

Now I try a build with tcc just for fun but windows header are not included.

**Comment by hostilefork** [comment]
The size not being right was due to a debug feature that doesn't seem to be able to work on that particular compiler combination for some reason.  It was trying to use [bit fields](https://en.cppreference.com/w/cpp/language/bit_field) to give some insight into which bits were set in value headers.

I limited the feature to Linux builds, where it seems to work:

https://github.com/metaeducation/ren-c/commit/77aef9c23e88c2126edcd77643b5cd68482415ef
